### ISSUE TITLE
Contribuição projeto

### ISSUE THREAD

**Issue by rafaeldalbosco** [Samuel-Oliveira/Java_NFe#100]
Olá @Samuel-Oliveira 

Gostaria de compartilhar com seu projeto, tenho um Fork dele e já fiz algumas melhorias que acredito que pode agregar no uso do mesmo, se possível lhe enviarei então um PullRequest;

A implementação basicamente consiste na criação de annotations e objetos utilitários os quais refletem a o layout fortemente tipado da NF-e, todos os atributos das classes são anotados, também implementei um objeto que faz a validação dos atributos um a um e no final retorna o valor booleano da validação e a lista completa das críticas, também todos os objetos são transformados para o objeto que você utilizou no framework isso para evitar problemas de compatibilidade.

Principal recursos :
- Execução de validadores dos campos;
- Validar obrigatoriedade do campo;
- Validar tamanho mínimo; 
- Validar tamanho máximo;
- Permitir personalizar o retorno da mensagem de validação;
- Recurso de execução de regras de negócio para o grupo de elementos do XML;
- Valor default para o campo;
- Facilitador para carregar o imposto nos objetos;
- Enum para padrões de valores de tags
- Geração automática da Chave de acesso;

O Código está disponível no meu fork do Github conforme link abaixo:
https://github.com/rafaeldalbosco/Java_NFe/tree/master/src/main/java/br/com/samuelweb/nfe/util

**Obs:** Todo esse código como o código da minha NF-e ainda está sendo homologado pela equipe de testes da empresa que trabalho.

`
Exemplo de uso do meu código:

        InfNFe infNFe = new InfNFe();
        infNFe.getIde().setCuf(41);
        infNFe.getIde().setNatOp("Venda de mercadoria adquirida ou recebida de terceiros");
        infNFe.getIde().setMod(ModeloDocumento.NFE.getValue());
        infNFe.getIde().setSerie(500);
        infNFe.getIde().setNnf(4);
        infNFe.getIde().setDhEmi(ZonedDateTime.parse("2018-05-28T00:00:00-03:00", DateTimeFormatter.ISO_OFFSET_DATE_TIME));
        infNFe.getIde().setDhSaiEnt(ZonedDateTime.parse("2018-05-28T17:19:20-03:00", DateTimeFormatter.ISO_OFFSET_DATE_TIME));
        infNFe.getIde().setTpNF(1);
        infNFe.getIde().setIdDest(1);
        infNFe.getIde().setcMunFG(4106902);
        infNFe.getIde().setTpImp(1);
        infNFe.getIde().setTpEmis(1);
        infNFe.getIde().setTpAmb(2);
        infNFe.getIde().setFinNFe(1);
        infNFe.getIde().setIndFinal(0);
        infNFe.getIde().setIndPres(1);
        infNFe.getIde().setProcEmi(0);
        infNFe.getIde().setVerProc("1.0.0.0");
        infNFe.getIde().setCnf("78501789");

        infNFe.getEmit().setCnpjCpf("00000000000000");
        infNFe.getEmit().setxNome("NOME DA EMPRESA EMITENTE DE TESTE");
        infNFe.getEmit().setxFant("NOME FANTASIA");
        infNFe.getEmit().getEnderEmit().setxLgr("XV DE NOVEMBRO");
        infNFe.getEmit().getEnderEmit().setNro("123");
        infNFe.getEmit().getEnderEmit().setxBairro("CENTRO");
        infNFe.getEmit().getEnderEmit().setcMun(4106902);
        infNFe.getEmit().getEnderEmit().setxMun("CURITIBA");
        infNFe.getEmit().getEnderEmit().setUf("PR");
        infNFe.getEmit().getEnderEmit().setCep(80000000);
        infNFe.getEmit().getEnderEmit().setcPais(1058);
        infNFe.getEmit().getEnderEmit().setxPais("BRASIL");
        infNFe.getEmit().getEnderEmit().setFone(00000000);
        infNFe.getEmit().setIe("0000000000");
        infNFe.getEmit().setCrt("3");

        infNFe.setDest(new Dest());
        infNFe.getDest().setCnpjCpf("00000000000000");
        infNFe.getDest().setxNome("NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL");
        infNFe.getDest().getEnderDest().setxLgr("RUA TESTE");
        infNFe.getDest().getEnderDest().setNro("000");
        infNFe.getDest().getEnderDest().setxBairro("CENTRO");
        infNFe.getDest().getEnderDest().setcMun(4106902);
        infNFe.getDest().getEnderDest().setxMun("Curitiba");
        infNFe.getDest().getEnderDest().setUf("PR");
        infNFe.getDest().getEnderDest().setCep(80000000);
        infNFe.getDest().getEnderDest().setcPais(1058);
        infNFe.getDest().getEnderDest().setxPais("BRASIL");
        infNFe.getDest().getEnderDest().setFone("00000000");
        infNFe.getDest().setIndIEDest(1);
        infNFe.getDest().setIe("0000000000");

        Det det = new Det();
        det.getProd().setcProd("862875");
        det.getProd().setCean("5601010111240");
        det.getProd().setxProd("SARDINHA RAMIREZ EM TOMATE 125G");
        det.getProd().setNcm("16041310");
        det.getProd().setCest("1708000");
        det.getProd().setCfop("5102");
        det.getProd().setuCom("UN");
        det.getProd().setqCom(new BigDecimal("5.4564564564"));
        det.getProd().setvUnCom(new BigDecimal("4.97"));
        det.getProd().setvProd(new BigDecimal("24.85"));
        det.getProd().setCeanTrib("5601010111240");
        det.getProd().setuTrib("UN");
        det.getProd().setqTrib(new BigDecimal("5"));
        det.getProd().setvUnTrib(new BigDecimal("4.97"));
        det.getProd().setIndTot(1);

        det.getImposto().setIcms(new ICMS());
        det.getImposto().getIcms().setOrig(OrigemMercadoria.NACIONAL.getValue());
        det.getImposto().getIcms().setCST(CSTIcms.valueOf("CST_00"));
        det.getImposto().getIcms().setModBC(DeterminacaoBaseIcms.VALOR_OPERACAO);
        det.getImposto().getIcms().setvBC(new BigDecimal("24.85"));
        det.getImposto().getIcms().setpICMS(new BigDecimal("7.00"));
        det.getImposto().getIcms().setvICMS(new BigDecimal("1.74"));

        det.getImposto().setIpi(new IPI());
        det.getImposto().getIpi().setcEnq("999");
        det.getImposto().getIpi().setCst(CSTIpi.valueOf("CST_53"));

        det.getImposto().setPis(new PIS());
        det.getImposto().getPis().setCST(CSTPis.valueOf("CST_01"));
        det.getImposto().getPis().setvBC(new BigDecimal("24.85"));
        det.getImposto().getPis().setpPIS(new BigDecimal("0.0"));
        det.getImposto().getPis().setvPIS(new BigDecimal("0.41"));

        det.getImposto().setCofins(new COFINS());
        det.getImposto().getCofins().setCst(CSTCofins.valueOf("CST_01"));
        det.getImposto().getCofins().setvBC(new BigDecimal("24.85"));
        det.getImposto().getCofins().setpCOFINS(new BigDecimal("0.0"));
        det.getImposto().getCofins().setvCOFINS(new BigDecimal("1.89"));

        infNFe.getDetList().add(det);

        infNFe.getTotal().setIcmsTot(new ICMSTot());
        infNFe.getTotal().getIcmsTot().setVbc(new BigDecimal("24.85"));
        infNFe.getTotal().getIcmsTot().setVicms(new BigDecimal("1.74"));
        infNFe.getTotal().getIcmsTot().setVicmsDeson(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVfcp(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVbcst(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVst(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVfcpst(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVfcpstRet(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setvProd(new BigDecimal("24.85"));
        infNFe.getTotal().getIcmsTot().setvFrete(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setvSeg(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setvDesc(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVii(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVipi(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVipiDevol(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVpis(new BigDecimal("0.41"));
        infNFe.getTotal().getIcmsTot().setVcofins(new BigDecimal("1.89"));
        infNFe.getTotal().getIcmsTot().setvOutro(new BigDecimal("0.00"));
        infNFe.getTotal().getIcmsTot().setVnf(new BigDecimal("24.85"));

        infNFe.getTotal().setRetTrib(new RetTrib());
        infNFe.getTotal().getRetTrib().setVbcirrf(new BigDecimal("24.85"));

        infNFe.getTransp().setModFrete(ModalidadeFrete.SEM_OCORRENCIA_DE_TRANSPORTE);
        infNFe.getTransp().setVol(new ArrayList<>());
        Vol vol = new Vol();
        vol.setqVol(5);
        vol.setnVol("5");
        vol.setPesoL(new BigDecimal("0.625"));
        infNFe.getTransp().getVol().add(vol);

        infNFe.setPag(new Pag());
        DetPag detPag = new DetPag();
        detPag.settPag(TipoPagamento.DINHEIRO);
        detPag.setvPag(new BigDecimal("24.85"));
        infNFe.getPag().getDetPag().add(detPag);

        infNFe.setInfAdic(new InfAdic());
        infNFe.getInfAdic().setInfAdFisco("-");
`        
`
       //VALIDADOR  DO DOCUMENTO

        NfeValidator validator = new NfeValidator();
        if (!validator.validarInfNfe(infNFe)) {
            List<ErrosValidacao> errosValidacaos = validator.getErrosList();
            for (ErrosValidacao errosValidacao : errosValidacaos) {
                System.out.println(errosValidacao.toString());
            }
        }

        // Inicia As Certificado
        Certificado certificado = CertificadoService.certificadoPfx("/home/dalbosco/certificado/certificado.pfx", "123");
        //Esse Objeto Você pode guardar em uma Session.
        ConfiguracoesWebNfe config = ConfiguracoesWebNfe.iniciaConfiguracoes(Estados.PR,
                ConstantesUtil.AMBIENTE.HOMOLOGACAO,
                certificado,
                MethodHandles.lookup().lookupClass().getResource("/schemas").getPath(),
                true);

        //Converte os dados para o objeto NFe
        TNFe nfe = new TNFe();
        nfe.setInfNFe(infNFe.build());

        // Monta EnviNfe
        TEnviNFe enviNFe = new TEnviNFe();
        enviNFe.setVersao("4.00");
        enviNFe.setIdLote("1");
        enviNFe.setIndSinc("1");
        enviNFe.getNFe().add(nfe);
        for (TNFe tnFe : enviNFe.getNFe()) {
            System.out.println(XmlUtil.objectToXml(tnFe));
        }
        // Monta e Assina o XML
        enviNFe = NfeWeb.montaNfe(config, enviNFe, true);`

**Comment by resplandes** [comment]
Interessante.

**Comment by Samuel-Oliveira** [comment]
Agradeço a Contribuição Rafael. 
Peço que vc aguarde eu terminar a versão 4.00.7, dai vc fará um merge e depois um pullrequest.

Devo terminar ela semana que vem. Dai eu te chamo aqui e te aviso!

**Comment by rafaeldalbosco** [comment]
Combinado.

**Comment by Samuel-Oliveira** [comment]
@rafaeldalbosco já subio para a branch de desenvolvimento a Versão que vai para produção.
Consegue atualizar e dar o pull request nesta branch?

https://github.com/Samuel-Oliveira/Java_NFe/tree/Desenvolvimento

**Comment by rafaeldalbosco** [comment]
@Samuel-Oliveira essa semana irei organizar para lhe enviar.

**Comment by Samuel-Oliveira** [comment]
Aceita com sucesso!
Estara na branch de desenvolvimento, e em breve subirei para master.
