### ISSUE TITLE
Caracteres especiais

### ISSUE THREAD

**Issue by edivaldoms** [Samuel-Oliveira/Java_NFe#101]
https://github.com/Samuel-Oliveira/Java_NFe/blob/6eac771a64e6630a044680ab1c3ae8f2f2c2935a/src/main/java/br/com/samuelweb/nfe/util/XmlUtil.java#L216

Na linha acima está indicando Unicode não seria? 
marshaller.setProperty(Marshaller.JAXB_ENCODING, "UTF-8");

Pois tenho um produto com a seguinte descrição:
COTOVELO A/C A-105 90º 6000LBS NPT 1/2"

Mas o método XmlUtil.objectToXml() retona:
COTOVELO A/C A-105 90E#186; 6000LBS NPT 1/2"

Qual seria a forma mais adequada de corrigir isso?

Alguns clientes exigem que a descrição do produto saia exatamente como a ordem de compra deles.
Pensei em substituir "º" por " " (espaço), pois não sei de outro carácter para representar o grau da curva.

O método "removeAcentos" poderia remover esses carácteres especiais?

**Comment by Samuel-Oliveira** [comment]
Beleza @edivaldoms ?

Eu não me lembro pq deve ser unicode agora de cor, mas sei que tinha um motivo.
De qlq maneira irei fazer um teste e te dou um feedBack.

MAs lembrando que a Sefaz orientar que não tenha caracteres especiais no XML.

**Comment by edivaldoms** [comment]
Se não me engano o Java por padrão trabalha com Unicode, mas a geração e escrita do XML da receita está em UTF-8, por isso acontece esse problema. Trocar as palavras acentuadas por palavras sem acento até já faço, mas alguns símbolos importantes, realmente não sei como poderia substituir pelo quê. Por enquanto, estou substituindo alguns caracteres especiais como "º" por " " (espaço), melhor que ficar "E#186;"

**Comment by Samuel-Oliveira** [comment]
A questão não era nem o Marshar com unicode, ele passa esses caracteres, Era na hora da assinatura.
Fiz algumas modificações e agora é possivel fazer envio de caracteres especiais.

Jà está na branch de desenvolvimento e em breve estará em produção!

**Comment by edivaldoms** [comment]
Os caracteres especiais ainda não são aceitos.

Fiz um teste enviando:
`<xProd>BARRA CHATA A-36 3" X 5/16" CCAA º ª ¿ I ¬ !@#$%¨ *()_+</xProd>`

Após assinar fica assim:
'<xProd>BARRA CHATA A-36 3" X 5/16" CCAA ï¿½ ï¿½ ï¿½ I ï¿½ !@#$%ï¿½ *()_+</xProd>'

E exibe esse erro:
Grave:   br.com.samuelweb.nfe.exception.NfeValidacaoException: Erro Na Validação do Xml: 
- O valor 'BARRA CHATA A-36 3 X 5/16 CCAA ? ? ? I ? !@#$%? *()_+' do elemento 'xProd' não é válido.
	at br.com.samuelweb.nfe.Enviar.montaNfe(Enviar.java:66)
	at br.com.samuelweb.nfe.Nfe.montaNfe(Nfe.java:170)

**Comment by Samuel-Oliveira** [comment]
@edivaldoms foram feitos diversos testes e POr causa das ferramentas utilizadas, Não é possivel ter caracteres especiais. Use a versão em desenvolvimento para que pare os erros: https://github.com/Samuel-Oliveira/Java_NFe/tree/Desenvolvimento
