### ISSUE TITLE
TProcEventoNFe invalido - Sem assinatura

### ISSUE THREAD

**Issue by Albertiano** [Samuel-Oliveira/Java_NFe#102]
Primeiramente, obrigado pela contribuição Samuel,

Nesse trecho do cancelamento:
```
            // Cria TProcEventoNFe
            TProcEvento procEvento = new TProcEvento();
            procEvento.setVersao("1.00");
            procEvento.setEvento(enviEvento.getEvento().get(0));
            procEvento.setRetEvento(retorno.getRetEvento().get(0));
```
Está retornado um TProcEvento sem assinatura, portanto inválido.
Minha solução foi externizar a assinatura semelhante ao que foi feito no método de enviar a nota, espero que possa ser adicionado na nova versão:

             // Monta e Assina o XML do Evento
            enviEvento= Nfe.montaEvento(enviEvento, false);

            // Envia a Nfe para a Sefaz
            TRetEnvEvento retorno = Nfe.cancelarNfe(enviEvento, false, ConstantesUtil.NFE);

**Comment by Samuel-Oliveira** [comment]
Irei estar Verificando!

**Comment by Samuel-Oliveira** [comment]
Realmente não ia a assinatura no Proc.
Porém da maneira que você citou vai quebrar o código de todos os usúarios atuais, então no lugar disso criei o método para criar o Proc no XmlUtil.
Segue exemplo de como utilizar:

            //Cria ProCEvento
            String proc = XmlUtil.criaProcEventoCancelamento(config, enviEvento, retorno.getRetEvento().get(0));

IMplementado na Branch Desenvolvimento e em breve em Produção!
