### ISSUE TITLE
Nfe.consultaCadastro

### ISSUE THREAD

**Issue by tixtecnologia** [Samuel-Oliveira/Java_NFe#103]
Ao realizar a consulta passando como parâmetro para o Nfe.consultaCadastro o estado de SC o mesmo retorna o erro: br.com.samuelweb.nfe.exception.NfeException: WebService de NfeConsultaCadastro_4.00 não encontrado para SC

Santa Catarina é atendido pelo SVRS - Sefaz Virtual do RS Para serviço de Consulta Cadastro conforme fazenda no link:
[http://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=](url)

```
ConfiguracoesIniciaisNfe.iniciaConfiguracoes(Estados.RS, AMBIENTE.PRODUCAO, certificado, "/src/schemas");			
			
TRetConsCad retornoSP = Nfe.consultaCadastro(ConstantesUtil.TIPOS.CNPJ, "99999999999999", Estados.SC);


```

**Comment by Samuel-Oliveira** [comment]
Obrigado pelo aviso!
A Correção já está disponível na branch de desenvolvimento.
Em breve na branch master!
