### ISSUE TITLE
Serialização dos Objetos

### ISSUE THREAD

**Issue by john182** [Samuel-Oliveira/Java_NFe#104]
Boa noite Samuel, recentemente crie uma API no qual eu passo a chave e devolvo uma nfeProcessada, pra aplicação cliente. porem quando eu mando serializar alguns objetos estão com valores não esperado exemplo o vTotTrib está recebendo um array assim comos os imposto.

	"infNFe": {
		"versao": "4.00",
		"Id": "NFe53180816925371000114650010000007521000007528",
		"ide": {
			"cUF": "53",
			"cNF": "00000752",
			"natOp": "VENDA",
			"mod": "65",
			"serie": "1",
			"nNF": "752",
			"dhEmi": "2018-08-21T10:11:41-03:00",
			"tpNF": "1",
			"idDest": "1",
			"cMunFG": "5300108",
			"tpImp": "4",
			"tpEmis": "1",
			"cDV": "8",
			"tpAmb": "2",
			"finNFe": "1",
			"indFinal": "1",
			"indPres": "1",
			"procEmi": "0",
			"verProc": "4.0.0.3"
		},
		"emit": {
			"CNPJ": "16925371000114",
			"xNome": "EMPRESA MATRIZ PARA TESTE",
			"xFant": "EMPRESA MATRIZ PARA TESTE",
			"enderEmit": {
				"xLgr": "logradouro",
				"nro": "11020",
				"xBairro": "centro",
				"cMun": "5300108",
				"xMun": "BRASILIA",
				"UF": "DF",
				"CEP": "49500970",
				"cPais": "1058",
				"xPais": "BRASIL"
			},
			"IE": "0762315200183",
			"CRT": "1"
		},
		"det": [{
			"nItem": "1",
			"prod": {
				"cProd": "1",
				"cEAN": "SEM GTIN",
				"xProd": "NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL",
				"NCM": "19053100",
				"CFOP": "5102",
				"uCom": "UN",
				"qCom": "1.0000",
				"vUnCom": "10.000000",
				"vProd": "10.00",
				"cEANTrib": "SEM GTIN",
				"uTrib": "UN",
				"qTrib": "1.0000",
				"vUnTrib": "10.000000",
				"indTot": "1"
			},
			"imposto": {
				"vTotTrib": ["0.00"],
				"ICMS": [{
					"ICMSSN102": {
						"orig": "0",
						"CSOSN": "102"
					}
				}],
				"PIS": [{
					"PISAliq": {
						"CST": "01",
						"vBC": "10.00",
						"pPIS": "1.65",
						"vPIS": "0.16"
					}
				}],
				"COFINS": [{
					"COFINSAliq": {
						"CST": "01",
						"vBC": "10.00",
						"pCOFINS": "3.00",
						"vCOFINS": "0.30"
					}
				}]
			}
		}],
		"total": {
			"ICMSTot": {
				"vBC": "0.00",
				"vICMS": "0.00",
				"vICMSDeson": "0.00",
				"vFCP": "0.00",
				"vBCST": "0.00",
				"vST": "0.00",
				"vFCPST": "0.00",
				"vFCPSTRet": "0.00",
				"vProd": "10.00",
				"vFrete": "0.00",
				"vSeg": "0.00",
				"vDesc": "0.00",
				"vII": "0.00",
				"vIPI": "0.00",
				"vIPIDevol": "0.00",
				"vPIS": "0.16",
				"vCOFINS": "0.30",
				"vOutro": "0.00",
				"vNF": "10.00",
				"vTotTrib": "0.00"
			}
		},
		"transp": {
			"modFrete": "9"
		},
		"pag": {
			"detPag": [{
				"tPag": "01",
				"vPag": "10.00"
			}]
		},
		"infAdic": {
			"infCpl": "Trib. Aprox. Federal R$ 0,00 e R$ 0,00 Estadual e R$ 0,00 Municipal Fonte IBPT"
		}
	},
	"infNFeSupl": {
		"qrCode": "http://dec.fazenda.df.gov.br/ConsultarNFCe.aspx?chNFe=53180816925371000114650010000007521000007528&nVersao=100&tpAmb=2&dhEmi=323031382d30382d32315431303a31313a34312d30333a3030&vNF=10.00&vICMS=0.00&digVal=667652392b38674d684644503449322f416b796452444c425877493d&cIdToken=000001&cHashQRCode=454DD34E3759CF874175BA05C26FA1349F25D749",
		"urlChave": "http://dec.fazenda.df.gov.br/ConsultarNFCe.aspx"
	}
}

Está vendo ainda minha aplicação cliente não esta conseguindo serializar o json.

**Comment by Samuel-Oliveira** [comment]
Beleza John? Dai vc tem q ver como esta sendo feito essa serialização, e comparar com o xml Original.

De qualquer maneira, não aconselho fazer a serialização completa.
Recomendo ou mandar o Xml como arquivo (byte) ou como String.

Isso vai evitar perdas, e dores de cabeça com serialização.

**Comment by john182** [comment]
Então Samuel  o primeiro problema seria que o TypeScript não saberia pega um byte e transforma em um objeto, segundo seria executado vários alguns procedimentos a mais para gera o xml, depois o bytes.

Agora tenho um projeto em C# que eu contribuo, la a gente escreveu as classe não e ta gerando de boa, acho que a se gente ao invez de cria as classe dos schemas criasse na mão teríamos, mais controle, eu posso me encarregar de tal fardo.

**Comment by Samuel-Oliveira** [comment]
Bom Eu tenho um Server Rest, que comunica com um TypeScript que faço o Procedimento com String.
Por exemplo: 
"objeto": { "xml" : "<NFe>....</Nfe>"} 

Criar os objetos na mão é insano para manutenção...

**Comment by john182** [comment]
Realmente da um pouco de trabalho mesmo sempre temos que manter atualizado os objetos. vc ta conseguindo com esse xml preencher os objetos no typeScript, por enquanto eu to usando essa sacada no meu monitor pra certificado A3. mando desse mesmo jeito pra enviar.

**Comment by Samuel-Oliveira** [comment]
É por que assim John, Eu não uso o XML pra alimentar algum Objeto no Typed. O XML é trafegado apenas para download e visualização. Na minha opinião quem monta e lida com o XML é sempre o Backend. 
No Front vc monta os objetos da nota, e no back vc preenche o xml com esses OBjetos!

**Comment by Samuel-Oliveira** [comment]
Tem mais Alguma observaçao sobre o Assunto John? Ou podemos fechar?

**Comment by Samuel-Oliveira** [comment]
Topico fechado, se houver algo a mais abriremos!
