### ISSUE TITLE
Exception incomplete BER/DER data

### ISSUE THREAD

**Issue by egioncpdsi** [Samuel-Oliveira/Java_NFe#110]
Olá Samuel tudo ok? Estou tentando configurar a aplicação para utilizar Smart Card utilizando o LEITOR_GEMPC_PERTO, porém esse Exception é jogado:

> Erro ao pegar KeyStore: Could not parse certificate java.io.IOException: Incomplete BER/DER data

Utilizando Java 8 com javafx, senha do certificado ja foi checada e está correta.

Desde já agradeço ! <3

**Comment by Samuel-Oliveira** [comment]
BOm dia, Pode dar mais Informações?
O código de como esta sendo feito a configuração, marca da leitora. Se tem o gerenciador de certificados instalado, se testando via Repositório do Windows funciona.

**Comment by egioncpdsi** [comment]
Método para configurar certificado : (Funciona com A3 Tokken e A1)
`private static Certificado certificado() throws CertificadoException {
        String tpCert = Main.prop.getProperty("tpCert");
        String dll = Main.prop.getProperty("DLLA3");
        String marcaA3 = "";
        String caminhoCertificado = Main.prop.getProperty("caminhoPFX");
        String dllA3 = "";
        String senha = Main.prop.getProperty("senhaCertificado");
        Certificado certificado = new Certificado();
        if (tpCert.equals("A3")) {
            switch (dll) {
                case "LEITOR_GEMPC_PERTO":
                    marcaA3 = TipoCertificadoA3.LEITOR_GEMPC_PERTO.getMarca();
                    dllA3 = TipoCertificadoA3.LEITOR_GEMPC_PERTO.getDll();
                    break;
                case "LEITOR_SCR3310":
                    marcaA3 = TipoCertificadoA3.LEITOR_SCR3310.getMarca();
                    dllA3 = TipoCertificadoA3.LEITOR_SCR3310.getDll();
                    break;
                case "TOKKEN_ALADDIN":
                    marcaA3 = TipoCertificadoA3.TOKEN_ALADDIN.getMarca();
                    dllA3 = TipoCertificadoA3.TOKEN_ALADDIN.getDll();
                    break;
                case "OBERTHUR":
                    marcaA3 = TipoCertificadoA3.OBERTHUR.getMarca();
                    dllA3 = TipoCertificadoA3.OBERTHUR.getDll();
                    break;
            }
            certificado = CertificadoService.certificadoA3(marcaA3, dllA3, senha);
        } else if (tpCert.equals("A1")) {
            certificado = CertificadoService.certificadoPfx(caminhoCertificado, senha);
        }
        return certificado;
    }

    public static ConfiguracoesIniciaisNfe iniciaConfigurações() throws CertificadoException {
        Certificado certificado = ConfiguracoesNFe.certificado();
        return ConfiguracoesIniciaisNfe.iniciaConfiguracoes(Estados.valueOf("DF"), Main.prop.getProperty("tpAmb"),
                certificado, ConfiguracoesNFe.schemasPath);
    }`
A leitora é da Comtac com um smart card Valid;
Utilizo SafeSign Token Administrator como gerenciador;
Listando o certificados pelo repositório, ele aparece;

**Comment by Samuel-Oliveira** [comment]
Alguem feedback sobre o erro?
(Se não for respondido em 5 dias, o tópico será fechado)
