### ISSUE TITLE
Pontuação

### ISSUE THREAD

**Issue by hrossi** [Samuel-Oliveira/Java_NFe#112]
Ola @Samuel-Oliveira 

Na linha abaixo, no replace, existe 2 palavras sem acentuação.

_Não_ e _válido_

Se concordar eu altero e abro um pr

https://github.com/Samuel-Oliveira/Java_NFe/blob/98e97e0056b1c2ffd13799c967a1bd69a86ace59/src/main/java/br/com/samuelweb/nfe/Validar.java#L141

**Comment by hrossi** [comment]
Tem essa palavra tb _obrigatorio_

**Comment by Samuel-Oliveira** [comment]
Pode fazer o Pull Request, mas faça na branch de Desenvolvimento por favor

**Comment by Samuel-Oliveira** [comment]
#113 
Feito!
