### ISSUE TITLE
consulta do QRCode

### ISSUE THREAD

**Issue by robsonlira** [Samuel-Oliveira/Java_NFe#114]
Samuel blz cara, 

Então eu notei que ao capturar o QRCode e ser remetido ao Site não via os dados da nota então resolvi consultar a Sefaz daqui de Pernambuco e lá consta o seguinte

Homologação - http://nfcehomolog.sefaz.pe.gov.br/nfce/consulta 
Produção - http://nfce.sefaz.pe.gov.br/nfce/consulta 

Sei que no xml temos duas tag´s <qrCode> e <urlChave> estou emitindo em Homologação

**Comment by Samuel-Oliveira** [comment]
Corrigido
