### ISSUE TITLE
Endereços de WS MT Homologação estão errados

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#115]
Olá @Samuel-Oliveira , os endereços dos WS de Homologação da UF MT estão faltando ?wsdl no final, isso faz com que gere erro ao emitir ou testar serviços, veja.

`Api Java Nfe Versão 4.00.7 - Samuel Olivera - samuk.exe@hotmail.com
Certificado: ARQUIVO_BYTES - MATIAS E MATIAS LTDA:10658657000102 - Vencimento: 2019-04-27
Ambiente: Produção - Estado: Mato Grosso
Xml Status: <?xml version="1.0" encoding="UTF-8"?><consStatServ versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><cUF>51</cUF><xServ>STATUS</xServ></consStatServ>
WebService - https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4?wsdl
Status:107
Motivo:Servico em Operacao
Data:2018-10-01T08:08:56-04:00`

agora o de homologação

`Api Java Nfe Versão 4.00.7 - Samuel Olivera - samuk.exe@hotmail.com
Certificado: ARQUIVO_BYTES - MATIAS E MATIAS LTDA:10658657000102 - Vencimento: 2019-04-27
Ambiente: Homologação - Estado: Mato Grosso
Xml Status: <?xml version="1.0" encoding="UTF-8"?><consStatServ versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><cUF>51</cUF><xServ>STATUS</xServ></consStatServ>
WebService - https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4
Erro:unknown`

**No arquivo WebServicesNfe.ini está assim**

**[NFe_MT_P]**
**NfeInutilizacao_4.00=https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao4?wsdl**
**NfeConsultaProtocolo_4.00=https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta4?wsdl**
**NfeStatusServico_4.00=https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4?wsdl**
**NfeConsultaCadastro_4.00=https://nfe.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro4?wsdl**
**RecepcaoEvento_4.00=https://nfe.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento4?wsdl**
**NFeAutorizacao_4.00=https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao4?wsdl**
**NFeRetAutorizacao_4.00=https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao4?wsdl**

**[NFe_MT_H]**
**NFeRetAutorizacao_4.00=https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao4**
**RecepcaoEvento_4.00=https://homologacao.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento4**
**NfeConsultaProtocolo_4.00=https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta4**
**NFeAutorizacao_4.00=https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao4**
**NfeInutilizacao_4.00=https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao4**
**NfeConsultaCadastro_4.00=https://homologacao.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro4**
**NfeStatusServico_4.00=https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4**

**Lista dos endereços de Produção e de homologação corretos**
**Produção**

Serviço | Versão | URL
-- | -- | --
RecepcaoEvento | 1.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento?wsdl
NfeRecepcao | 2.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeRecepcao2?wsdl
NfeRetRecepcao | 2.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeRetRecepcao2?wsdl
NfeInutilizacao | 2.00 / 3.10 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao2?wsdl
NfeConsultaProtocolo | 2.00 / 3.10 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta2?wsdl
NfeStatusServico | 2.00 / 3.10 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2?wsdl
NfeConsultaCadastro | 2.00 / 3.10 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro2?wsdl
NFeAutorizacao | 3.10 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao?wsdl
NFeRetAutorizacao | 3.10 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao?wsdl
NfeInutilizacao | 4.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao4?wsdl
NfeConsultaProtocolo | 4.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta4?wsdl
NfeStatusServico | 4.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4?wsdl
NfeConsultaCadastro | 4.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro4?wsdl
RecepcaoEvento | 4.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento4?wsdl
NFeAutorizacao | 4.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao4?wsdl
NFeRetAutorizacao | 4.00 | https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao4?wsdl

**Homologação**

Serviço | Versão | URL
-- | -- | --
NfeRecepcao | 2.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRecepcao2?wsdl
NfeRetRecepcao | 2.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRetRecepcao2?wsdl
NfeInutilizacao | 2.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao2?wsdl
NfeConsultaProtocolo | 2.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta2?wsdl
NfeStatusServico | 2.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2?wsdl
RecepcaoEvento | 2.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento?wsdl
NfeInutilizacao | 3.10 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao2?wsdl
NfeConsultaProtocolo | 3.10 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta2?wsdl
NfeStatusServico | 3.10 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2?wsdl
NfeConsultaCadastro | 3.10 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro2?wsdl
RecepcaoEvento | 3.10 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento?wsdl
NFeAutorizacao | 3.10 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao?wsdl
NFeRetAutorizacao | 3.10 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao?wsdl
NfeInutilizacao | 4.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao4?wsdl
NfeConsultaProtocolo | 4.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta4?wsdl
NfeStatusServico | 4.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4?wsdl
NfeConsultaCadastro | 4.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro4?wsdl
RecepcaoEvento | 4.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento4?wsdl
NFeAutorizacao | 4.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao4?wsdl
NFeRetAutorizacao | 4.00 | https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao4?wsdl

**Comment by resplandes** [comment]
@Samuel-Oliveira  fiz a mudança aqui no projeto, testei mas ainda gerou o erro :(

`Api Java Nfe Versão 4.00.7 - Samuel Olivera - samuk.exe@hotmail.com`
`Certificado: ARQUIVO_BYTES - MATIAS E MATIAS LTDA:10658657000102 - Vencimento: 2019-04-27`
Ambiente: Homologação - Estado: Mato Grosso`
`Xml Status: <?xml version="1.0" encoding="UTF-8"?><consStatServ versao="4.00"` `xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb>`<cUF>51</cUF>`<xServ>STATUS</xServ></consStatServ>`
`WebService - https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4?wsdl`
`Erro:unknown`

**Comment by resplandes** [comment]
Aparentemente é o serviço mesmo mas é necessário a correção sim dos endereços, obrigado!

**Comment by Samuel-Oliveira** [comment]
Corrigido, Já Disponível na Branch de Desenvolvimento e em breve Em Produção.
