### ISSUE TITLE
Rejeição 395 - QRCode diverge do previsto

### ISSUE THREAD

**Issue by robsonlira** [Samuel-Oliveira/Java_NFe#119]
Olá boa noite,

Samuel eu fiz uma atualização para a Lib atualizada e começou a ocorrer rejeição Endereço do site da UF da consulta via QRCode diverge do previsto.

Antes qdo abri a issue anterior eu conseguia autorizar a nota, apenas o leitor de QRCode nao enviava para o site, apos vc fazer a correção eu baixei a nova lib e começou a ocorrer este problema,

**Comment by robsonlira** [comment]
Eu abri o jar da versão nova extrai o arquivo .ini e alterei o mesmo ficando com estas informações

[NFCe_PE_P]
Usar=NFCe_SVRS_P
URL-QRCode=http://nfce.sefaz.pe.gov.br/nfce-web/consultarNFCe
URL-ConsultaNFCe=http://nfce.sefaz.pe.gov.br/nfce/consulta

[NFCe_PE_H]
Usar=NFCe_SVRS_H
URL-QRCode=http://nfcehomolog.sefaz.pe.gov.br/nfce-web/consultarNFCe
URL-ConsultaNFCe=http://nfce.sefaz.pe.gov.br/nfce/consulta

Salvei e copiei ele novamente pra dentro do jar , testei e autorizou

**Comment by Samuel-Oliveira** [comment]
Corrigido , ja esta na branch de Homologação e em breve a de produção.
