### ISSUE TITLE
O que seria este erro ?

### ISSUE THREAD

**Issue by pedrohlira** [Samuel-Oliveira/Java_NFe#120]
Erro ao Assinar Nfe O nome da entidade deve seguir imediatamente o '&' na referência da entidade.

Obrigado.

**Comment by Samuel-Oliveira** [comment]
Provavelmente seu XML Contem & (e comercial). E ele não é aceito no XML.

**Comment by pedrohlira** [comment]
Entendi, bem mas assim como o tratamento é feito para acentos, poderia ser feito para caracteres especiais como & > < e etc ?

existe uma função que remove tudo isso estou colocando abaixo.

```
public static String removeAcentos(String texto) {
        if (texto != null && !texto.equals("")) {
            texto = Normalizer.normalize(texto, Normalizer.Form.NFD);
            return texto.replaceAll("[\\p{InCombiningDiacriticalMarks}]", "");
        } else {
            return texto;
        }
    }
```

**Comment by Samuel-Oliveira** [comment]
Já Existe isso no Sistema. 
Para remover os Acentos utilize:
config.setRemoveAcentos(true);

Onde Config são as Configurações iniciais da Nfe.

**Comment by Samuel-Oliveira** [comment]
Foi feito a correção e já está na Branch de Desenvolvimento, em breve em produção!
Favor testar.
