### ISSUE TITLE
Da versão 4.00.3 para a 4.00.8 o sistema parou de reconhecer meu certificado A1.

### ISSUE THREAD

**Issue by Bonissauro** [Samuel-Oliveira/Java_NFe#122]
Olá, Samuel!

Voltei a me deparar com a situação descrita na issue 

https://github.com/Samuel-Oliveira/Java_NFe/issues/97

Da primeira vez que enfrentei isso, mantive a versao 4.00.3 e segui a vida. Agora, preciso gerar o qrcode2 e preciso MESMO atualizar.

**Comment by rreynoud** [comment]
Mas qual é o erro que esta dando?

**Comment by Samuel-Oliveira** [comment]
@Bonissauro já solicitei que me adicionasse no Skype! Ainda estou aguardando.

**Comment by Samuel-Oliveira** [comment]
@Bonissauro mais uma vez... Se não responder aqui ou no Skype. Vou fechar a Issue!

**Comment by Bonissauro** [comment]
Opa! Estamos desencontrando! Se quiser agora, estou online.

Se não puder ser agora, vamos marcar.

**Comment by Bonissauro** [comment]
Resolvido. Não sei se seria a forma "mais elegante", como se diz, de resolver a coisa, mas acabei copiando o arquivo "sunpkcs11.jar" da minha jdk (jre/lib/ext) do Mac para a WEB-INF/lib do meu projeto. Enfim, funcionou a vou seguir a vida! 

Obrigado, Samuel!
