### ISSUE TITLE
Erro ao enviar NFC-e para o estado do DF

### ISSUE THREAD

**Issue by GustavoAlves1993** [Samuel-Oliveira/Java_NFe#123]
Efetuei o download da bilbioteca java-nfe-4.00.08 para efetuar as alterações no QRCODE, e após isso aparece o seguinte erro:

Erro ao Assinar Nfe referência à entidade "B" deve terminar com o delimitador ';'

e me gera a exceção :

Ambiente: Produção - Estado: Distrito Federal
[Fatal Error] :1:1153: A referÛncia Ó entidade "B" deve terminar com o delimitador ';'.
out 17, 2018 4:21:17 PM br.com.odbo.ui.FinalizarVenda gerarNFCe
GRAVE: null
br.com.samuelweb.nfe.exception.NfeException: Erro ao Assinar NfeA referÛncia Ó e
ntidade "B" deve terminar com o delimitador ';'.
at br.com.samuelweb.nfe.Assinar.assinaDocNFe(Assinar.java:91)
at br.com.samuelweb.nfe.Assinar.assinaNfe(Assinar.java:61)
at br.com.samuelweb.nfe.Enviar.montaNfe(Enviar.java:54)
at br.com.samuelweb.nfe.Nfe.montaNfe(Nfe.java:170)

Como disse estou usando a ultima versão da lib, e os ultimos Schemas, alguém passou por isso?

Eu efetuei os testes no estado de SP e foi normalmente usando meu certificado em homologação, esse ero está ocorrendo em um cliente em produção no DF

obrigado desde já.

**Comment by Samuel-Oliveira** [comment]
Isso ai é por causa de Carácter especial.
Corrigi já na branch de desenvolmento: https://github.com/Samuel-Oliveira/Java_NFe/tree/Desenvolvimento

**Comment by Samuel-Oliveira** [comment]
#120

**Comment by GustavoAlves1993** [comment]
Obrigado Samuel, deu certo.
