### ISSUE TITLE
Na operacao de consulta de situacao dos servicos - erro intermitente DOCTYPE NOT ALLOWED

### ISSUE THREAD

**Issue by Bonissauro** [Samuel-Oliveira/Java_NFe#126]
Samuel,

tenho quase certeza que se trate de problema no sistema da SEFAZ, mas vou perguntar por aqui (até pra deixar registrado):
 
estou recebendo com intermitência aqui no DF um erro "DOCTYPE NOT ALLOWED", ao tentar verificar o estado atual dos webservices da SEFAZ DF.

Meu código é este:

`public static void verificaSeServicosSefazEstaoOnline(ConfiguracoesIniciaisNfe config) throws NfeException, ServicoSefazInoperanteException{
		
		TConsStatServ consStatServ = new TConsStatServ();
		consStatServ.setTpAmb(config.getAmbiente());
		consStatServ.setCUF(config.getEstado().getCodigoIbge());
		consStatServ.setVersao(config.getVersaoNfe());
		consStatServ.setXServ("STATUS");

		TRetConsStatServ retorno = Nfe.statusServico(ConstantesUtil.NFCE);
		System.out.println("Status:" + retorno.getCStat()+"    "+"Motivo:" + retorno.getXMotivo()+"    "+"Data:" + retorno.getDhRecbto());
		
		if (!retorno.getCStat().equalsIgnoreCase("107")){
			throw new ServicoSefazInoperanteException("Servico esta inoperante em sua SEFAZ. Caso isto se repita algumas vezes num curto espaco de tempo, considere a ATIVACAO DO MODO DE CONTINGENCIA!");
		}

		return;
		
}`

Stacktrace:

`[0m[0m13:15:12,023 INFO  [stdout] (default task-31) WebService - https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx
[0m[0m13:15:33,047 INFO  [stdout] (default task-8) Api Java Nfe Versão 4.00.8 - Samuel Olivera - samuk.exe@hotmail.com
[0m[0m13:15:33,047 INFO  [stdout] (default task-8) Ambiente: Produção - Estado: Distrito Federal
[0m[0m13:15:33,067 INFO  [stdout] (default task-8) Xml Status: <?xml version="1.0" encoding="UTF-8"?><consStatServ versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><cUF>53</cUF><xServ>STATUS</xServ></consStatServ>
[0m[0m13:15:33,068 INFO  [stdout] (default task-8) WebService - https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx
[0m[31m13:15:34,437 ERROR [stderr] (default task-8) br.com.samuelweb.nfe.exception.NfeException: javax.xml.stream.XMLStreamException: DOCTYPE is not allowed
[0m[31m13:15:34,437 ERROR [stderr] (default task-8) 	at br.com.samuelweb.nfe.Status.statusServico(Status.java:63)
[0m[31m13:15:34,437 ERROR [stderr] (default task-8) 	at br.com.samuelweb.nfe.Nfe.statusServico(Nfe.java:67)`

**Comment by Samuel-Oliveira** [comment]
Bom dia, pode me informa se o erro continua?

**Comment by Bonissauro** [comment]
Pelo menos, meu usuário (único, por enquanto, kkk) não reclamou mais.

Na verdade, não tinha a ver com tua biblioteca, Samuel. Piração do autorizador, parece. 

O fato é que eles tem muito que avançar nesse sistema deles. Por exemplo, em NENHUMA nota que vi aqui do DF (em todos os lugares que testei, de estacionamentos a supermercados) está funcionando a leitura do QRCode. Todos, independente do sistema, estão retornando a mensagem "Nota não encontrada" quando o usuário tentar verificar. Também a informação dos valores pagos e troco não estavam sendo exibidas em notas (de homologação, pelo menos) do RS. E por aí vai,

Enfim, isso não tem a ver contigo e estou fechando esta issue.

Abraço!
