### ISSUE TITLE
Detalhe evento de cancelamento na consulta NF-e

### ISSUE THREAD

**Issue by demerval** [Samuel-Oliveira/Java_NFe#127]
Samuel,

Na consulta da NF-e pelo XML (Nfe.consultaXml), quando existe evento de cancelamento não é retornado a tag "detEvento", e verificando as informações que retornam do servidor existe esta informação no retorno, parece que esta informação e perdida quando é feito o unmarshal da resposta do servidor.

**Comment by Samuel-Oliveira** [comment]
Boa Tarde, pode montar e enviar o Código de exemplo?
Lembrando que é importante informar seus imports.

**Comment by demerval** [comment]
Boa Tarde, Samuel!

Me desculpa, na realidade as informações estão corretas eu que não estava sabendo como encontra-las,
consegui recupera-las com o código abaixo, não sei se o correto, mas está funcionando.

```java
DetEvento detEvento = new DetEvento();

detEvento.setDescEvento(detEventoRet.getAny().get(0).getFirstChild().getNodeValue());
detEvento.setNProt(detEventoRet.getAny().get(1).getFirstChild().getNodeValue());
detEvento.setXJust(detEventoRet.getAny().get(2).getFirstChild().getNodeValue());
detEvento.setVersao(detEventoRet.getOtherAttributes().values().toArray()[0].toString());

```
Agradeço pela atenção.
