### ISSUE TITLE
Erro no campo InfAdProd da tag Det

### ISSUE THREAD

**Issue by TiagoZaro** [Samuel-Oliveira/Java_NFe#128]
Após atualizar para versão v4.00.8, além de ter alguns problemas com acentuação, que contornei manualmente, estou com problemas agora ao enviar infos adicionais no produto,  voltando a versão o mesmo  não ocorre. O que pode ser? OBS: só ocorre em produção e olhando o xsd não entendi pq ocorre!

br.com.samuelweb.nfe.exception.NfeValidacaoException: Erro Na Validação do Xml: - O valor 'Resolucao do Senado Federal n. 13/12, numero do FCI: 1643D9D5-1912-444A-BD57-17835E592F6F ' do elemento 'infAdProd' não é válido. - O valor 'Resolucao do Senado Federal n. 13/12, numero do FCI: 507967DC-61AB-43DE-A94C-E903641A8C74 ' do elemento 'infAdProd' não é válido. at br.com.samuelweb.nfe.Enviar.montaNfe(Enviar.java:66) at br.com.samuelweb.nfe.NfeWeb.montaNfe(NfeWeb.java:172) at

**Comment by Samuel-Oliveira** [comment]
Blz? Use a versão da branch de Desenvolvimento: https://github.com/Samuel-Oliveira/Java_NFe/tree/Desenvolvimento

**Comment by TiagoZaro** [comment]
Fala Samuel, tudo certo. Vi que vc subiu a  java-nfe-4.00.9. Então, de imediato o que eu fiz foi na chamada do NfeWeb.montaNfe passei false para não validar. Estranho que olhei o XSD por cima e estaria tudo correto. Vou dar uma olhada nessa versão que vc passou. Obrigado

**Comment by Samuel-Oliveira** [comment]
Fechado Por inatividade!
