### ISSUE TITLE
Erro - Retorno 298 - Assinatura difere do padrao do Projeto

### ISSUE THREAD

**Issue by claudiosann** [Samuel-Oliveira/Java_NFe#129]
Olá! 
Estou testando o Nfce em modo de homologação, no estado do Paraná.
E depois que habilitei o QRCode 2.0 começou a dar erro na nota com o retorno de cStat: 298 - Assinatura difere do padrão do Projeto, antes com o QRCode na versão antiga estava enviando a nota normalmente.
Estou utilizando a classe  NfeWeb para assinar e enviar.
Já verifiquei o uso caracteres especiais e tudo mais e nada.
Desde já grato pela atenção.

**Comment by resplandes** [comment]
Bom dia @claudiosann sempre que tive esse problema foi devido algum caracter especial ou no campo observação da nfe tinha um espaço, teve caso deu enviar o campo obsNFe vazio e também deu esse problema.

**Comment by claudiosann** [comment]
Já verifiquei os caracteres especiais. Esse problema só começou a acontecer depois que passei a utilizar o QRCode 2.0.

**Comment by resplandes** [comment]
Veja como te falei, eu tive esse problema como citei sem caracteres especiais, era a tag de observação vazia.

**Comment by claudiosann** [comment]
Valeu a dica vou verificar...

**Comment by claudiosann** [comment]
Resolvido!
Realmente estava num teste enviando um \n junto e em outro mandei a observação vazia.
Muito Obrigado!
