### ISSUE TITLE
NF-e de devolução para pessoa fisíca

### ISSUE THREAD

**Issue by GustavoAlves1993** [Samuel-Oliveira/Java_NFe#133]
Estou tentando fazer uma NF-e de devolução para pessoa física, e ele está dando erro no campo do documento (CNPJ ou CPF), segue o erro abaixo:

br.com.samuelweb.nfe.exception.NfeValidacaoException: Erro Na ValidaþÒo do Xml:

```
- O valor '16404570890' do elemento 'CNPJ' nÒo Ú vßlido.
        at br.com.samuelweb.nfe.Enviar.montaNfe(Enviar.java:66)
        at br.com.samuelweb.nfe.Nfe.montaNfe(Nfe.java:170)
        at br.com.odbo.ModuloNFe40.EnviaNFe.EnvioAssincrono.enviar(EnvioAssincro
no.java:81)
        at br.com.odbo.ModuloNFe40.EnviaNFe.GerarNFe.GerarNFe(GerarNFe.java:138)

        at br.com.odbo.ModuloNFe40.NFe_UI.ExibeInfosNFe$EnviaNFe.run(ExibeInfosN
Fe.java:228)
        at java.lang.Thread.run(Unknown Source)
```

Analisando o código, vi que a tag de documento no grupo de devolução só tem setCNPJ, gostaria de saber se estou fazendo algo de errado ou se realmente não tem suporte para CPF.

**Comment by resplandes** [comment]
Boa tarde, quando se emite um a nfe para PF não se preenche a tag CNPJ e sim a Tag CPF.

**Comment by GustavoAlves1993** [comment]
Sim, porém não tem o campo CPF, apenas CNPJ.

RefNF fNF = new RefNF();
fNF.set

não tem CPF, apenas o campo CNPJ

**Comment by Samuel-Oliveira** [comment]
Tudo Bom Chefe @GustavoAlves1993 ?

RefNF é para referenciar uma Nota fiscal Modelo 1/1A

É isto mesmo que você quer fazer? Por que eu desconheço Nota Modelo 1 com emitente pessoa Física.

**Comment by GustavoAlves1993** [comment]
Boa tarde @Samuel-Oliveira , tudo na paz e por ai?

Não, seria uma devolução em cima de uma NF-e de venda mesmo, eu tenho usado esse grupo para fazer todas as NF-e de devolução no meu sistema, porém esse é o primeiro caso para uma pessoa física. Qual grupo seria o indicado para trabalhar com a parte de devolução?

**Comment by Samuel-Oliveira** [comment]
Para devolução de Nota fiscal Eletrônica, você deve usar o grupo NFref. Onde você informa apenas a chave da nota que esta devolvendo!

**Comment by GustavoAlves1993** [comment]
Vou pesquisar sobre o assunto, assim que conseguir resolver dou um feedback, obrigado pela dica desde já.

**Comment by Samuel-Oliveira** [comment]
Ok, qualquer coisa nos avise! Abraços!
