### ISSUE TITLE
Certificado digital A1 de homologação

### ISSUE THREAD

**Issue by Greelings** [Samuel-Oliveira/Java_NFe#141]
Bom dia, como posso gerar um certificado digital A1 de homologação para testes (emissão de notas fiscais NFC-e)? Obrigado.

**Comment by fredwilliamtjr** [comment]
Não existe certificado de homologação e nem alguma forma de gerar certificado gratuito. Você precisa adquirir um certificado digital para sua empresa e usar ele para emitir nota fiscal em homologação.
