### ISSUE TITLE
Permitir enviar manifestação do destinatário em lote

### ISSUE THREAD

**Issue by eltonmmoreira** [Samuel-Oliveira/Java_NFe#143]
Permitir enviar manifestação do destinatário em lote. Hoje framework permite enviar uma única manifestação por vez, mas a receita aceita um lote de até 20 eventos. Acho interessante a possibilidade de realizar envio em lote, assim evitamos abrir várias requisições quando necessitamos enviar mais de uma manifestação.

**Comment by Samuel-Oliveira** [comment]
Interessante vou Estudar isso para a Proxima versão.

**Comment by eltonmmoreira** [comment]
> Interessante vou Estudar isso para a Proxima versão.

Já desenvolvi funcionalidade e vou fazer um pull request

**Comment by Samuel-Oliveira** [comment]
Quando fizer. Utilize a branch Desenvolvimento.

**Comment by Samuel-Oliveira** [comment]
@eltonmmoreira PArece estar tudo ok. Sò vou te pedir um favor.
Escreva um teste (nos mesmos padrões da wiki) e me enviei por email (samuel@swconsultoria.com.br) . Para que outros usuários saibam como usar esta nova funcionalidade. 
https://github.com/Samuel-Oliveira/Java_NFe/wiki
