### ISSUE TITLE
Rejeição 464 NFCe Minas Gerais

### ISSUE THREAD

**Issue by phillipig** [Samuel-Oliveira/Java_NFe#146]
Olá boa tarde,

Estou usando a versão mais recente da Lib, com todas as URLs de acordo com http://www.sped.fazenda.mg.gov.br/spedmg/nfce/web-services/. 

Na hora de autorizar a NFCe , recebo a rejeição 464: Código de Hash no QR-Code difere do calculado.

Já testei com dois clientes de MG diferentes, CSC diferentes, mas com o mesmo problema. Os demais estados que temos clientes, está funcionando normalmente.

Alguém já passou por isso? Pode me dar uma luz?

**Comment by phillipig** [comment]
Problema encontrado, erro do contador ao informar os CSCs. Finalizando essa issue

**Comment by Samuel-Oliveira** [comment]
Sem problemas, Eu estarei gerando uma nova versão na branch de Desenvolvimento em 30 minutos, onde vai corrigir um erro de URL de consulta de MG. Lembre se de pegar ela. E breve vou colocar em Produção.
