### ISSUE TITLE
Manifestação NFe, erro na validação do xml

### ISSUE THREAD

**Issue by HaiFish** [Samuel-Oliveira/Java_NFe#148]
Copiei o exemplo 11 da wiki, e adaptei para fazer um teste de ciencia de nota fiscal recebida.
Porém quando vou executar ele exibe o seguinte erro:
# Erro: Erro Na Validação do Xml: 
sch-props-correct.2: Um esquema não pode conter dois componentes globais com o mesmo nome; este esquema contém duas ocorrências de 'http://www.portalfiscal.inf.br/nfe,TCOrgaoIBGE'.

Pelo que vi ele duplica isso xmlns="http://www.portalfiscal.inf.br/nfe".

Obrigado pela atenção.

**Comment by HaiFish** [comment]
Na versão 4.00.9 estava funcionando bem, agora na 4.00.10 que começou a dar esse problema

**Comment by Samuel-Oliveira** [comment]
Tudo bom? Na verdade este é um erro dos Schemas, Que a Sefaz manda essa Tag "TCOrgaoIBGE" Duplicada.

Já corrigi lá, só baixar os Schemas.rar novamente.

**Comment by HaiFish** [comment]
Testei aqui e funcionou, obrigado.
