### ISSUE TITLE
Exception Específica em ConfiguracoesNFe

### ISSUE THREAD

**Issue by andersonscherrrer** [Samuel-Oliveira/Java_NFe#149]
No método criarConfiguracoes, poderia ser lançado a excetpion CertificadoException ao invés da exception genérica Exception?
`
public static ConfiguracoesNfe criarConfiguracoes(EstadosEnum estado, AmbienteEnum ambiente, Certificado certificado,
                                                String pastaSchemas) throws Exception {
`

**Comment by Samuel-Oliveira** [comment]
Opa, escapou esse erro na Refatoração. Obrigado por avisar.
Já foi corrigido na versão Snapshot:

Para usar, adicione o repositorio de Snapshot ao Maven:
```
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
<dependency>
    <groupId>br.com.swconsultoria</groupId>
    <artifactId>java-nfe</artifactId>
    <version>4.00.11-SNAPSHOT</version>
</dependency>
```
Ou baixe o Jar aqui: https://github.com/Samuel-Oliveira/Java_NFe/raw/master/java-nfe-4.00.11-SNAPSHOT.jar
