### ISSUE TITLE
Implementação da emissão de NFe produtor rural

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#150]
**### Implementar a emissão de NF-e para produtor rural ###**

1. Deve-se ter alteração da chave da NFe que deve conter o CPF do emissor completados por 0(zeros) até atingir tamanho 14, deve-se também validar a séria da NFe que é destinada para produtor rural sendo 920-969 
Segue o link dos detalhes de alteração que logo de inicio deve-se ser na Chave da NFe e na série conforme manual, também lembrando que deve-se aceitar a assinatura do XML com um certificado e-CPF

[http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=9OYnBfONR2s=](http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=9OYnBfONR2s=)

**Comment by Samuel-Oliveira** [comment]
Feito: Testar usando:

Para usar, adicione o repositorio de Snapshot ao Maven:
```
<repositories>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
<dependency>
    <groupId>br.com.swconsultoria</groupId>
    <artifactId>java-nfe</artifactId>
    <version>4.00.11-SNAPSHOT</version>
</dependency>
```
Ou baixe o Jar aqui: https://github.com/Samuel-Oliveira/Java_NFe/raw/master/java-nfe-4.00.11-SNAPSHOT.jar
