### ISSUE TITLE
Erro da data no cancelamento

### ISSUE THREAD

**Issue by pedrohlira** [Samuel-Oliveira/Java_NFe#151]
Bom dia, Samuel.

Parabéns novamente pela atualização da API, estou com um problema na hora de cancelar, usando a versão 4.00.10 onde o erro retornado é este:

**578 - Rejeicao: A data do evento nao pode ser maior que a data do processamento**

O código usado do seu exemplo:
```
                Evento cancela = new Evento();
                cancela.setChave(chave);
                cancela.setProtocolo(nota.getProtocolo());
                cancela.setCnpj(chave.substring(6, 20));
                cancela.setMotivo(NFe.normalizar(motivo));
                cancela.setDataEvento(LocalDateTime.now());
                cancela.setSequencia(1);
                // envio do evento
                TEnvEvento enviEvento = CancelamentoUtil.montaCancelamento(cancela, NFe.CONFIG);
                TRetEnvEvento retorno = Nfe.cancelarNfe(NFe.CONFIG, enviEvento, true, DocumentoEnum.getByModelo(chave.substring(20, 22)));
                RetornoUtil.validaCancelamento(retorno);
```
Este valor aqui que esta causando o problema cancela.setDataEvento(LocalDateTime.now());

Como estou testando em ambiente de homologacao, então ja conferi várias vezes o horario e esta igual ao de brasilia ate os segundos e nao estamos em horario de verao.

Bem antes como eu criava e nao tinha problemas.
`infEvento.setDhEvento(Util.formatarDate(Util.getCalendario().getTime(), Util.DATA_HORA_FORMAT) + "-03:00");`

**Comment by pedrohlira** [comment]
So para completar o mesmo problema ao emitir CCe, sobre a data estar maior que o processado.

**Comment by Samuel-Oliveira** [comment]
Beleza?
O LocalDateTime pega o Locale do Java, e nem sempre o now traz a timezone correta.
O Certo é sempre vc informar a timezone.
Exemplo:

`LocalDateTime.now(ZoneId.of("America/Sao_Paulo")`

Testa e Confirma por favor.

**Comment by pedrohlira** [comment]
Perfeito, era isso mesmo tem que forçar a ZONA, rsrs

Muito Obrigado, valeu e até mais.

**Comment by pedrohlira** [comment]
Boa tarde Samuel, creio que alguma coisa esta dando errado na data de evento, após a mudança de horario de verão que não existiu.

// gerar o objeto
                Evento cancela = new Evento();
                cancela.setChave(chave);
                cancela.setProtocolo(nota.getProtocolo());
                cancela.setCnpj(chave.substring(6, 20));
                cancela.setMotivo(NFe.normalizar(motivo));
                **cancela.setDataEvento(LocalDateTime.now(ZoneId.of("GMT-03")));**
                cancela.setSequencia(1);
                // envio do evento
                TEnvEvento enviEvento = CancelamentoUtil.montaCancelamento(cancela, NFe.CONFIG);
                TRetEnvEvento retorno = Nfe.cancelarNfe(NFe.CONFIG, enviEvento, true, DocumentoEnum.getByModelo(chave.substring(20, 22)));
                RetornoUtil.validaCancelamento(retorno);

Mas o xml gerado agora está vindo com -02 no campo da data do evento e com isso da erro 577 ou 578 e não consigo cancelar uma NFCe.

`<?xml version="1.0" encoding="UTF-8"?><envEvento xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00"><idLote>1</idLote><evento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infEvento Id="ID1101112719112999945900020365001000000005115730640001"><cOrgao>27</cOrgao><tpAmb>2</tpAmb><CNPJ>29999459000203</CNPJ><chNFe>27191129999459000203650010000000051157306400</chNFe><dhEvento>2019-11-06T15:14:21-02:00</dhEvento><tpEvento>110111</tpEvento><nSeqEvento>1</nSeqEvento><verEvento>1.00</verEvento><detEvento versao="1.00"><descEvento>Cancelamento</descEvento><nProt>327190000037473</nProt><xJust>teste de homologacao</xJust></detEvento></infEvento>...</evento></envEvento>`

**Comment by Samuel-Oliveira** [comment]
Tudo bom? Todos estamos passando por isso, e infelizmente é problema de maquina.

Para resolver utilize o TzUpdate.

**Comment by resplandes** [comment]
@pedrohlira  eu resolvi da seguinte maneira, em ambiente "Windows", abri o cmd como administrador, naveguei até a pasta bin do meu jdk ["C:\Program Files\Java\jdk1.8.0_131\bin\java.exe"] apos isso executei o comando "C:\Program Files\Java\jdk1.8.0_131\bin\java.exe" depois executei o mesmo comando porem sem navegar até a pasta apos isso normalizou ou seja os comandos executados como administrador foi 
"C:\Program Files\Java\jdk1.8.0_131\bin\java.exe" -jar tzupdate.jar -f
java -jar tzupdate.jar -f
