### ISSUE TITLE
Sugestão para evitar quebra de código

### ISSUE THREAD

**Issue by edivaldoms** [Samuel-Oliveira/Java_NFe#152]
Sugiro criar projetos separados dos schemas por versão maior. Exemplo:
Para o pacote de esquemas do  "nfe_v4.00.xsd" criar um projeto no Github com o nome SchemaNFeV4 e seguir o mesmo nome de pacote já criado "br.com.swconsultoria.nfe.schema_4.enviNFe".

Quando o Fisco criar a versão 5 do XML, basta criar um novo projeto mudando o número da versão: "nfe_v5.00.xsd" -> "SchemaNFeV5" e "br.com.swconsultoria.nfe.schema_5.enviNFe"

Isso permitirá que no futuro possa se utilizar mais de uma versão quando for necessário ler XML da versão 4 e 5 quando estiver em transição.

Além do mais, separar os schemas por projetos, minimiza a compilação a facilidade dar manutenção por não haver grande quantidade de arquivos.

Cada schema e versão seria um novo projeto. Ex.: "SchemaEventoCancV1", "SchemaEventoCCeV1", "SchemaEventoManifestaDestV1", etc.

Importante para não haver conflito quando houver mudança de versão do schema é colocar a versão maior dentro de pacote específico.

Outra vantagem de optar por separar em projetos, é que cada desenvolvedor poderá utilizar o projeto que precisar. sem precisar utilizar todas as classes de schemas e as classes de comunicação com a Sefaz.

**Comment by Samuel-Oliveira** [comment]
Tudo Bom @edivaldoms ?
Entendo o seus questionamentos e vou lhe explicar por infelizmente não podemos fazer assim.

Os métodos da API são totalmente baseados nos Objetos. Para enviar a Nfe ela recebe o Objeto do Envio NFe. Dito isso, para ter versões diferentes desse Objeto (v4/v5) iria trazer uma quebra gigantesca na arquitetura. Onde eu iria ter que generalizar todo projeto e ter a insegurança de não receber o Objeto correto!

Sobre retirar os Schemas que não se utilizam seguem o mesmo conceito, para se compilar tem que existir no projeto todas os Objetos que os métodos precisam. Então a unica maneira de funcionar assim, seria alem de criar schemas em projetos separados seria criar as funções tbm. Então seria um projeto só para envio, outro só para cancelamento, e assim vai.

Então infelizmente para a arquitetura que trabalho isso seria muito inviável.
Além do que a manutenção disso seria muito mais trabalhosa.
Tendo tudo dentro de um projeto só me economiza muito!

De qlq maneira obrigado pela sugestão e espero que entenda este cenário!
Abraços!

**Comment by edivaldoms** [comment]
A versão anterior utilizava a dependência "nfe-xsd-9-v1.60c.jar" com as classes geradas dos schemas com o seguinte pacote: 
"br.inf.portalfiscal.nfe.schema_4"

Na versão atual o nome do pacote foi alterado para: 
"br.com.swconsultoria.nfe.schema_4."

Com isso tivemos que mudar todas nossa aplicação para se adequar.

Não seria mais adequado somente ter atualizado o projeto/dependência "nfe-xsd-9-v1.60c" com as novas especificações dos schemas sem ter alterado o nome do pacote? (ou criar/utilizar outra dependência atualizada).

No futuro quando vier a v5, não irá quebrar o código ou ter conflito. Hoje a classe "br.com.swconsultoria.nfe.Nfe" é a principal ponte de comunicação com a nossa aplicação, caso venha ter a versão 5, bastaria criar o pacote "br.com.swconsultoria.nfe.v5.Nfe" (exemplo).

Só estou fazendo uma análise de futurologia para evitar possíveis problemas lá na frente.

Mas quero parabenizar pela iniciativa desse projeto, realmente está bem simples e funcional.

**Comment by Samuel-Oliveira** [comment]
Então o que deveria ser feito é retirar a versão. 
Deixar sempre "br.com.swconsultoria.nfe.schema", e quando alterar para 5 por exemplo, manter assim.
Dai o usuário não teria que fazer refatoração.

**Comment by edivaldoms** [comment]
Não Samuel, não aconselho a retirar a versão, pois quando surgir uma nova versão, a adesão seria parcial por parte dos contribuintes. Em determinado momento teria que fazer marshel/unmarshel da v4 ou v5 e o projeto do desenvolvedor teria que ter as classes do schema v4 e v5. Por isso deveria separar essas classes de schemas em dependências separadas como estavam antes.

**Comment by Samuel-Oliveira** [comment]
Entendi, bom nessa versão vamos deixar pois já tivemos migração d+.
Mas na próxima alteração de versão traremos versionamento de volta.
Obrigado!
