### ISSUE TITLE
Erro ao consultar Cadastro na UF MT

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#153]
Olá, estou tentando consultar cadastros da uf MT e estou recebendo uma exceção de NullPointException
Outros estados estão OK;
`java.lang.NullPointerException
	at br.com.swconsultoria.nfe.util.RetornoUtil.validaConsultaCadastro(RetornoUtil.java:138)
	at com.softjava.helpers.nfe.ConsultaCadastroContribuinteSefaz.consultarRetornoCliente(ConsultaCadastroContribuinteSefaz.java:77)`

**Comment by Samuel-Oliveira** [comment]
@resplandes PArece ser um erro da sua sefaz.

Envie um email pra eles passando o XML de envio e o de retorno, e peça para acusarem onde esta o erro de XML por favor.

**Comment by Samuel-Oliveira** [comment]
@resplandes Algumas Resposta da Sefaz?

**Comment by resplandes** [comment]
Olá @Samuel-Oliveira  , então, pediram para esperar :?

**Comment by resplandes** [comment]
@Samuel-Oliveira  pedi mais informações, a Sefaz me pediu mais 7 dias, tendo visto que os 12 dias já corrido do Ticket não foi suficiente, creio que pegou fogo em uma parte dos servidores rsrsrs

**Comment by resplandes** [comment]
@Samuel-Oliveira 
Sefaz disse que no MT o XML correto para consulta de cadastro é
XML correto:
<consultaCadastro xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4%22%3E
                <nfeDadosMsg>
                               <ConsCad versao="2.00" xmlns="http://www.portalfiscal.inf.br/nfe%22%3E
                                               <infCons>
                                                               <xServ>CONS-CAD</xServ>
                                                               <UF>MT</UF>
                                                               <CNPJ>99999999999999</CNPJ>
                                               </infCons>
                               </ConsCad>
                </nfeDadosMsg>
</consultaCadastro>

e o nosso está sendo enviado dessa maneira aqui
<?xml version="1.0" encoding="UTF-8"?>
<ConsCad versao="2.00" xmlns="http://www.portalfiscal.inf.br/nfe%22%3E
    <infCons>
        <xServ>CONS-CAD</xServ>
        <UF>MT</UF>
        <CNPJ>10658657000102</CNPJ>
    </infCons>
</ConsCad>

**Comment by Samuel-Oliveira** [comment]
Corrigido na Versão 4.00.11-SNAPSHOT
