### ISSUE TITLE
Suporte a modulos

### ISSUE THREAD

**Issue by HaiFish** [Samuel-Oliveira/Java_NFe#154]
Esse projeto tem suporte aos módulos do java (>9) ?, estou tentando usar com um modulo que criei porem ocorrem vários erros de módulos que leem de 2 pacotes diferentes.

error: module javafx.baseEmpty reads package org.apache.axis2.jaxws from both axis2.metadata and axis2.jaxws
error: module javafx.baseEmpty reads package org.apache.axis2.jaxws.wsdl from both axis2.metadata and axis2.jaxws
error: module javafx.baseEmpty reads package org.apache.axis2.jaxws.registry from both axis2.metadata and axis2.jaxws

Obrigado.
Anderson

**Comment by Samuel-Oliveira** [comment]
Beleza @HaiFish ?

Sim já está compatível com Java 11.
O que parece estar acontecendo em seu erro é conflito de bibliotecas.
Verifique se no seu pom tem Axis2 e retire.
Ou apenas coloque a Biblioteca NFe como primeira importação.

**Comment by HaiFish** [comment]
Opa, obrigado pela atenção, continuando os testes, nas dependências do projeto só tem o java-nfe declarado, e no module-info.java, coloquei as dependências do java.nfe e javafx.controls.

O module-info.java fica assim:
module fxapp {
    requires java.nfe;
    requires java.base;
    requires java.logging;

    requires transitive javafx.base;
    requires transitive javafx.graphics;
    requires transitive javafx.controls;

    exports fxapp;
}

O projeto que peguei como exemplo é esse:
https://github.com/brunoborges/javafx-jlink-starter-gradle

Apenas coloquei o java.nfe como dependência e declarei no module-info.java, e já ocorre esses erros, acredito que o problema possa ser nas dependências do próprio java.nfe. Pelo que pesquisei ele da esse erro quando 2 módulos oferecem o mesmo pacote.

**Comment by Samuel-Oliveira** [comment]
Conseguiu alguma solução?

Lendo o erro com mais calma ele reclama o JavaFx entra em conflito com a Nfe.
Experimente retirar os requires do JavaFx e teste por favor.

**Comment by HaiFish** [comment]
Opa, tentei sem o JavaFX e também da erro, colocando só o require java.nfe já da os erros, a solução que encontrei foi não criar o module-info.java para não criar o módulo da aplicação, e compilar da maneira antiga (classpath).

**Comment by Samuel-Oliveira** [comment]
Entendi, bom irei fechar aqui.
Caso tente novamente e encontre a solução me avise que reabrimos!
