### ISSUE TITLE
Erro ao enviar o lote 

### ISSUE THREAD

**Issue by uilhianet** [Samuel-Oliveira/Java_NFe#164]
org.apache.axis2.AxisFault: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target...

**Comment by Samuel-Oliveira** [comment]
Beleza? 
1º Pra não sujar tanto o visual, eu resumi suas postagem, tranquilo?
2º Toda vez que vc executa, no console mostra as informações da Biblioteca.
Pode colocar um print dela aqui?

**Comment by uilhianet** [comment]
Tranquilho, Obrigado pela dica. Conseguir resolver.   CertificadoService.inicializaCertificado(certificado, new FileInputStream(new File("Cacert")));

**Comment by Samuel-Oliveira** [comment]
Está errado, aqui é o procedimento certo: https://github.com/Samuel-Oliveira/Java_NFe/wiki/01-:-Configuracoes
