### ISSUE TITLE
Cancelamento com CPF

### ISSUE THREAD

**Issue by hrossi** [Samuel-Oliveira/Java_NFe#166]
Olá

Precisei fazer o cancelamento de uma NF utilizando CPF ao inves de CNPJ e descobri que a classe CancelamentoUtil não abrange isso, abrange apenas CNPJ.

Irei abrir um PR com a alteração para avaliação se cabe ou não ser adicionado ao código.

**Comment by Samuel-Oliveira** [comment]
Duplicado #167
