### ISSUE TITLE
Erro consulta cadastro RJ

### ISSUE THREAD

**Issue by queirozrphl** [Samuel-Oliveira/Java_NFe#169]
Senhores, preciso de uma ajuda.
Estou tentando fazer a consulta de cadastro por CNPJ, de uma empresa do RJ. 
Porém, recebo um retorno: "Estado não possui Consulta de Cadastro". 

A ideia é buscar as notas emitidas contra meu CNPJ, alguém consegue me ajudar com isso?

Configurações: 

```
ConfiguracoesNfe.criarConfiguracoes(EstadosEnum.RS`` , AmbienteEnum.HOMOLOGACAO, certificado, "XXX/schemas");
TRetConsCad`` retorno_2 = Nfe.consultaCadastro(config, PessoaEnum.JURIDICA, "XXXXXXXXXXXXX", EstadosEnum.RJ);

```

**Comment by Samuel-Oliveira** [comment]
Olá, você está se confundindo., consulta cadastro busca os dados da empresa (Endereço, Inscrição , CNPJ, etc) e realmente não existe para o Rio.

O que vc quer é o DistribuiçãoDfe: https://github.com/Samuel-Oliveira/Java_NFe/wiki/12-:-Download-Nfe-(DistDfe)

**Comment by queirozrphl** [comment]
Muito obrigado! 

Desculpe a confusão.

**Comment by queirozrphl** [comment]
Só mais uma questão, quando tento fazer essa consulta do tutorial, ele me pede uma chave. 
Essa chave está contida no arquivo pfx? Se sim, estou tentando utilizar mas está codificado como sha1, não e não funciona. 

Consegue me ajudar com isso?

**Comment by Samuel-Oliveira** [comment]
A chave, seria a chave da Nota a ser Consultada.

Caso queira consultar todas as notas, utilize a consulta via NSU.
E leia o manual, pelo jeito você esta tentando acertar no chute, é melhor você entender o que esta fazendo!

**Comment by diegocatalao** [comment]
Ao que me parece, o NSU refere-se a uma única nota. A busca de todas as notas fiscais contra o CNPJ com o certificado e a senha é possível? Esta funcionalidade foi implementada?

**Comment by Samuel-Oliveira** [comment]
Então @diegocatalao. O que me parece, é uma falta de conhecimento sobre o assunto. Peço por gentileza que tbm de uma estudada nas NT e Manuais. 
A Biblioteca trabalha com tudo relacionado a NFe. TUDO.

**Comment by diegocatalao** [comment]
Boa noite.
Obrigado pela resposta, @Samuel-Oliveira.
@queirozrphl você consegue gerar no máximo 50 notas referentes à 90 dias com nsu igual a zero (String NSU = "0"). A biblioteca retornará o referido e depois você deve juntar todos os NSUs buscando as notas.


Espero ter ajudado,
Att

**Comment by Samuel-Oliveira** [comment]
Se houver mais questões Avisem.
