### ISSUE TITLE
NFC-e em produção no estado de MG

### ISSUE THREAD

**Issue by GustavoAlves1993** [Samuel-Oliveira/Java_NFe#171]
Olá Samuel, estou com um problema ao enviar NFC-e em produção no estado de MG utilizando como forma de envio o modelo Assíncrono, ele faz o envio da NFC-e porém não consegue receber o XML de retorno, eu tentei aumentar o tempo da Thread.sleep para 3000, aumentei o número de tentativas no laço porém não funcionou. Ao tentar enviar a NFC-e no mesmo número porém de forma Síncrona a NFC-e apontou duplicidade, ou seja ela foi emitida. Após isso eu emiti outra NFC-e de forma Síncrona e ele funcionou perfeitamente, o que me leva a crer que exista algum problema no envio Assíncrono.

**Comment by Samuel-Oliveira** [comment]
Tudo bom @GustavoAlves1993 ? O Envio Assíncrono normalmente não é utilizado para estados que não são obrigatórios, já que é bem mais lento. 
Existe algum motivo que querer utiliza-lo?

Em todo caso o envio Assíncrono funciona em outras UFs, e como MG tem o servidor recente de NFCe, talvez contenha um erro que não foi identificado por ser pouco utilizado.
Caso insista em utilizar Assíncrono,  recomendo capturar o erro e entrar em contato com a Sefaz para obter resposta do ocorrido!

Abraços!

**Comment by GustavoAlves1993** [comment]
Olá @Samuel-Oliveira eu não sabia dessa diferença entre os envios e que o Síncrono era o mais utilizado pela SEFAZ, passarei então a utilizar apenas o envio síncrono, e em casos isolados o assíncrono obrigado pela atenção e por compartilhar seu conhecimento.
