### ISSUE TITLE
NF-e

### ISSUE THREAD

**Issue by GustavoAlves1993** [Samuel-Oliveira/Java_NFe#172]
Fiz a atualização da biblioteca ontem da versão 4.00.9 para a versão 4.00.11 e após colocar em dois clientes venho recebendo o retorno 297 - Rejeição: Assinatura difere do calculado, porém já olhei campo por campo dentro do XML e não consegui achar nenhum caractere especial ou espaços que possam estar travando a NF-e, segue XML para analise.

[NFe35190796453881000175550010000018011232817317.zip](https://github.com/Samuel-Oliveira/Java_NFe/files/3448251/NFe35190796453881000175550010000018011232817317.zip)

**Comment by Samuel-Oliveira** [comment]
Tudo Bom Gustavo?
Pode me enviar o conteúdo completo do console quando o erro ocorre?
Desde a inicialização da API até o COnteudo do retorno.

**Comment by GustavoAlves1993** [comment]
@Samuel-Oliveira  segue arquivo solicitado, obrigado desde já pelo feedback.

[LOG NF-E 4.00.11.txt](https://github.com/Samuel-Oliveira/Java_NFe/files/3461355/LOG.NF-E.4.00.11.txt)

**Comment by Samuel-Oliveira** [comment]
@GustavoAlves1993, nessa Observação tem quebra de Linhas?
Vc monta o Objeto pelo Objeto ou importa via String?

**Comment by Samuel-Oliveira** [comment]
@GustavoAlves1993 Liberei agora a versão 12, que corrige problemas de assinatura quando existe quebra de linha e espaços em branco.

Testa ela e me de um feedback por favor.

**Comment by GustavoAlves1993** [comment]
@Samuel-Oliveira testei com a nova versão da biblioteca liberada e deu certo, muito obrigado e parabéns pela excelente biblioteca.
