### ISSUE TITLE
Lentidão ao listar certificados no windows

### ISSUE THREAD

**Issue by GustavoAlves1993** [Samuel-Oliveira/Java_NFe#173]
Olá Samuel, estou com outro problema, tenho um cliente que possuí 9 certificados ativos instalados na mesma maquina e ao usar o a função **List<Certificado> certificados = CertificadoService.listaCertificadosWindows();** para carregar os certificados ele demora uma media de 47 segundos para listar os certificados, a emissão de NF-e está demorando de 5 a 10 minutos. 

Eu fiz uma função seguindo esse exemplo: **http://www.javac.com.br/jc/posts/list/915-dados-do-certificado-digital-a1-e-a3-repositorio-do-windows.page** e demorou 7 segundos para carregar os certificados.

Já passou por algum caso assim? será que pode ser algum bug ou algum problema no Windows?

Obrigado desde já.

**Comment by Samuel-Oliveira** [comment]
Fala Gustavo Tudo bem?
Sim, é um Bug Chato do Windows.
Quanto mais certificados instalados mais o tempo cresce, já tentei verificar um jeito de contornar isso, mas como é um comando que o próprio windows retorna. Não encontrei solução.

Recomendo que utilize os outros métodos!

**Comment by GustavoAlves1993** [comment]
Fala Samuel, bom dia. Quais seriam esses outros métodos? Existe uma forma de pegar o certificado sem ser listando todos que o Windows possuí?

**Comment by Samuel-Oliveira** [comment]
- Pegar através do caminho do certificado (pfx)
- Pegar através do CNPJ

**Comment by GustavoAlves1993** [comment]
pfx eu tenho conhecimento, até tenho isso no sistema também, o problema é que todos certificados da pessoa são A3.

você teria algum exemplo ou algum link com exemplo de como pegar o certificado utilizando o CNPJ?

**Comment by Samuel-Oliveira** [comment]
Para A3, ai que não recomendo o Windows Mesmo.
O cliente teria que digitar a senha toda vez.
Você pode fazer via DLL
Aqui todos os modos: 

https://github.com/Samuel-Oliveira/Java_Certificado/wiki

**Comment by GustavoAlves1993** [comment]
Das 7 opções listadas você tem alguma de sua preferência que acha ser o melhor caminho? vou analisar todas e efetuar testes, pergunto apenas para saber sua opinião devido a sua experiência.

**Comment by Samuel-Oliveira** [comment]
Melhor sempre é :
- A1 : Arquivo ou Byte
- A3 : Via DLL.

Tem mais alguma dúvida ou posso fechar?

**Comment by GustavoAlves1993** [comment]
Por momento não Samuel, obrigado pelos esclarecimentos.
