### ISSUE TITLE
Erro Consulta Cadastro do ES

### ISSUE THREAD

**Issue by marcoprodata** [Samuel-Oliveira/Java_NFe#175]
Ao efetuar a consulta do cadastro de contribuintes do ES retorna a Exception "Estado não possui Consulta Cadastro."

Link da SEFAZ com instruções a respeito.
https://internet.sefaz.es.gov.br/informacoes/nfe/ws_consulta_cadastro.php

**Comment by Samuel-Oliveira** [comment]
Corrigido na versão 4.0.13-SNAPSHOT em breve em Produção.
