### ISSUE TITLE
Alterações nos endpoints do estado do Pará

### ISSUE THREAD

**Issue by washingtonphp** [Samuel-Oliveira/Java_NFe#177]
Conforme publicado no portal oficial da Secretaria da Fazenda do Pará, o ambiente de autorização de Nota Fiscal eletrônica (NF-e) e de Nota Fiscal Avulsa eletrônica (NFA-e) para contribuintes do Pará foi transferido para a Sefaz Virtual do Rio Grande do Sul – SVRS.

Essa transição ocorrerá no dia 2 de setembro de 2019, data em que os web services de NF-e da SEFA-PA serão desativados. Sendo assim, empresas de software que atendem contribuintes paraenses deverão atualizar seus módulos de emissão.

SEFA Virtual Rio Grande do Sul ( SVRS) - Homologação
--
Serviços | Versão | URL
Nfelnutilização | 4,00 | https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx
NfeConsultaProctocolo | 4,00 | https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta4.asmx
NfeStatusServico | 4,00 | https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx
RecepcaoEvento | 4,00 | https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx
NFeAutozicao | 4,00 | https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx
NFrRetAutorização | 4,00 | https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx

SEFA Virtual Rio Grande do Sul ( SVRS) - Produção
--
Serviços | Versão | URL
Nfelnutilização | 4,00 | https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asmx
NfeConsultaProctoc | 4,00 | https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeNfeConsulta4.asmx
NfeStatusServico | 4,00 | https://nfe.svrs.rs.gov.br/ws/NfeStatudServivo/NfeStatusServico4.asmx
NfeConsultaCadastro | 4,00 | https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro4.asmx
RecepcaoEvento | 4,00 | https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento4.asmx
NFeAutozicao | 4,00 | https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NfeAutorizacao4.asmx
NFrRetAutorização | 4,00 | https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao4.asmx

Fontes
--
https://blog.tecnospeed.com.br/sefaz-do-para-altera-nfe-svrs/?utm_campaign=news_200819&utm_medium=email&utm_source=RD+Station
http://sefa.pa.gov.br/index.php/ambiente-de-homologacao-da-nf-e
http://sefa.pa.gov.br/index.php/noticias/15474-autorizacao

**Comment by Samuel-Oliveira** [comment]
Disponível na versão 4.0.13-SNAPSHOT em breve em Produção.
