### ISSUE TITLE
WebServices NFC-e

### ISSUE THREAD

**Issue by Samuel-Oliveira** [Samuel-Oliveira/Java_NFe#18]
Adicionar endereços de WebServices exclusivos para NFc-e

**Comment by SamuelRonha** [comment]
Estes são os webServices de homologação e de produção das NFC-e do Paraná:
http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=97

**Comment by Samuel-Oliveira** [comment]
Obrigado @SamuelRonha Vou estar adicionando todos os Endereços Até Amanha!

**Comment by SamuelRonha** [comment]
Certo Samuel, qualquer coisa que eu puder ajudar, estou a disposição!!

**Comment by Samuel-Oliveira** [comment]
Adicionados
