### ISSUE TITLE
Certificado Digital em Nuvem

### ISSUE THREAD

**Issue by GustavoAlves1993** [Samuel-Oliveira/Java_NFe#180]
A biblioteca suporta o uso de certificado digital em nuvem? Se sim aonde consigo material sobre como proceder para incluir essa função na aplicação.

**Comment by resplandes** [comment]
Como assim em nuvem ?
Se vc tiver acesso ao certificado é só vc transformar ele em byte e passar para a aplicação

**Comment by Samuel-Oliveira** [comment]
@GustavoAlves1993 Não existe um certificado em Nuvem. Certificados ou são A3 (Dispositivos físicos) ou A1 (Arquivos digitais);

A biblioteca suporta os dois tipos.
Caso vc vá trabalhar em Nuvem (Sistema Web) vc deverá trabalhar apenas com A1. Onde irá savar o certificado no banco (byte[]) ou salvar localmente no servidor.

**Comment by fredwilliamtjr** [comment]
Amigos acho que ele está falando sobre as tecnologias NeoID da Serpro ou RenoteID da Certisign.

**Comment by GustavoAlves1993** [comment]
Exato, um cliente comprou esse RemoteID da Certisign, ainda estou efetuando algumas pesquisas porém está um pouco confuso para mim como ele funciona.

**Comment by fredwilliamtjr** [comment]
Pelo que li existe uma API Rest, onde você pega o certificado em base64.

https://drive.google.com/file/d/1889P63bLWmaSHpQebWDKMd01rlqROODK/view?usp=drivesdk

**Comment by Samuel-Oliveira** [comment]
@GustavoAlves1993 A duvida foi respondida? Issue será fechada em 7 dias se não tiver retorno.

**Comment by GustavoAlves1993** [comment]
Foi sim, obrigado.
