### ISSUE TITLE
Configurar connection retry

### ISSUE THREAD

**Issue by matheusmahl** [Samuel-Oliveira/Java_NFe#181]
Estava simulando um possível problema na rede durante a emissão de NFC-e, e me deparei com uma demora grande no retorno do serviço de autorização. Mesmo setando o timeout nas configurações, ainda demora para retornar a requisição.

Conforme os logs, o client está fazendo o retry da requisição quando ocorre o timeout. Segue:

![timeout](https://user-images.githubusercontent.com/7575309/66828204-d867fc80-ef26-11e9-99cb-d999ba08c8e4.JPG)

Pesquisei um pouco e verifiquei que é possível fazer algumas implementações para tirar esse retry. Segue:

https://www.guj.com.br/t/desabilitar-retry-de-httpclient-notafiscaleletronica-resolvido/139392

https://stackoverflow.com/questions/2211578/axis2-how-to-set-connection-retry

https://stackoverflow.com/questions/43122983/how-to-stop-camel-http-retry

http://acodapella.blogspot.com/2009/01/problem-axis2-retries-3-times-before.html

Minha sugestão seria colocar um parâmetro nas configurações, assim como é feito para o timeout, para remover esse retry.

Não sei se funciona mesmo, então se precisar testar a implementação estou à disposição.

Obrigado.

**Comment by mikaelboff** [comment]
+1

**Comment by mikaelboff** [comment]
@Samuel-Oliveira algum retorno?

**Comment by ebaptistella** [comment]
+1

**Comment by Samuel-Oliveira** [comment]
Olá Pessoal!
O retry é um padrão mesmo do Axis2, e eu não alterei ele neste projeto.

A Ideia é bacana mas o tempo é curto, vou colocar ai na minha lista de a fazer, mas caso algum de vocês queira implementar e fazer um pull request, fique a disposição.

**Comment by Samuel-Oliveira** [comment]
#184

**Comment by Samuel-Oliveira** [comment]
Liberado para testes em SNAPSHOT. Em breve em produção;.
