### ISSUE TITLE
Erro de validação de NFe

### ISSUE THREAD

**Issue by leonardorocha96** [Samuel-Oliveira/Java_NFe#182]
Boa tarde, tudo bem?

Estou tentando este projeto para a geração de NFe. Porem, ao chamar a seguinte função:
"Nfe.montaNfe(config, enviNFe, **true**);"
Possuo um erro de validação no campo "cBenef", pois estou informando "SEM CBENEF" (permitido para o estado do RS até 04/2019). Ao enviar para a SEFAZ, a nota é validada corretamente. Teria como colocar alguma excessão nesta validação para o estado do RS?

Obrigado e parabéns pelo desenvolvimento deste projeto.

**Comment by Samuel-Oliveira** [comment]
Tudo bom?
A validação ocorre através dos arquivos XSD, Então vc pode adicionar essa regra no seus Arquivos XSD até a Sefaz corrigi-los!

Abraços!
