### ISSUE TITLE
Download de XML

### ISSUE THREAD

**Issue by icjunior** [Samuel-Oliveira/Java_NFe#183]
Olá pessoal...

Uma dúvida sobre o download do XML. O download da nota completa só é liberado após a manifestação de ciência ou confirmação, onde antes disso é somente a nota simplificada.

Mas existem ferramentas que afirmam que conseguem ler XMLs de "outras fontes oficiais do governo" somente com a chave de acesso.

Que fontes seriam essas? Alguém conhece algo parecido?

Obrigado.

**Comment by resplandes** [comment]
Boa tarde. Isso para baixar ela completa a mesma deve está manifestada, caso contrário e  resumido, as fontes "Mágicas" são ilegais, como fazem ? Não sei("O tio da sefaz deu acesso ao tio do sistema"), tem um meio legal que é pago esse sim. Mas é caro. Paga-se diretamente para a sefaz.

**Comment by samuelpc7** [comment]
Ou meio ilegal que paga, ou se não alguma falha no servidor da Sefaz que permite buscar essa informação, provávelmente algum webservice não divulgado provavelmente

Athene Sistemas e Informática ME

________________________________

**Comment by icjunior** [comment]
@resplandes , esse meio legal que é direto com a SEFAZ, você tem o nome?

**Comment by samuelpc7** [comment]
ainda é possivel carregar a pagina do SEFAZ Consulta completa em um WebBrowser dentro de sua aplicação, informar a chave de acesso, informar o captcha e carregar a nota, dai em diante vc tem todo o codigo HTML da pagina, se souber trabalhar com ele e só ir montando as informações...

Athene Sistemas e Informática ME

________________________________

**Comment by icjunior** [comment]
@samuelpc7 certo.. até aí sem problemas.. é que realmente estava querendo entender toda essa "mágica" dessas plataformas..rsrs.. muito obrigado pela ajuda.

**Comment by Samuel-Oliveira** [comment]
Duvida solucionada? Se não responder Em 3 dias a Issue será fechada.

**Comment by icjunior** [comment]
Sim.. pode fechar.. 

Obrigado @Samuel-Oliveira
