### ISSUE TITLE
Cancelamento de NFC-e estado AM

### ISSUE THREAD

**Issue by GustavoAlves1993** [Samuel-Oliveira/Java_NFe#185]
Olá Samuel, estou passando por um dificuldade e já tentei de N formas corrigir a mesma mais sem sucesso, no evento de cancelamento da NFC-e o campo DataEvento é do tipo LocalDateTime porém ao tentar efetuar um cancelamento de NFC-e recebo a rejeição **Rejeição 579: A data do evento não pode ser menor que a data de autorização para NF-e não emitida em contingência**, após analisar o XML reparei que a tag dhEvento preenche da seguinte forma: **2019-11-22T10:16:29-03:00**, está retornando com -03:00 porém no estado do AM o correto séria -04:00, é algum bug da biblioteca ou estou fazendo algo de errado? passo o valor da seguinte maneira 

Evento cancela = new Evento();
cancela.setDataEvento(LocalDateTime.now());

Tenho a mesma função funcionando em outros estado como por ex: SP, MG, DF

**Comment by lazaru** [comment]
ZoneId meuZoneId = sete a zona(rsrs) que vc quer -2:00 -3:00 conforme sua necessidade
cancela.setDataEvento(LocalDateTime.now(meuZoneId));

atualmente uso isso para setar
static {
      timeZonePorEstado.put("RO", TimeZone.getTimeZone("America/Porto_Velho"));
      timeZonePorEstado.put("AC", TimeZone.getTimeZone("America/Rio_Branco"));
      timeZonePorEstado.put("AM", TimeZone.getTimeZone("America/Manaus"));
      timeZonePorEstado.put("RR", TimeZone.getTimeZone("America/Boa_Vista"));
      timeZonePorEstado.put("PA", TimeZone.getTimeZone("America/Belem"));
      timeZonePorEstado.put("AP", TimeZone.getTimeZone("America/Belem"));
      timeZonePorEstado.put("TO", TimeZone.getTimeZone("America/Bahia"));
      timeZonePorEstado.put("MA", TimeZone.getTimeZone("America/Bahia"));
      timeZonePorEstado.put("PI", TimeZone.getTimeZone("America/Bahia"));
      timeZonePorEstado.put("CE", TimeZone.getTimeZone("America/Fortaleza"));
      timeZonePorEstado.put("RN", TimeZone.getTimeZone("America/Bahia"));
      timeZonePorEstado.put("PB", TimeZone.getTimeZone("America/Bahia"));
      timeZonePorEstado.put("PE", TimeZone.getTimeZone("America/Recife"));
      timeZonePorEstado.put("AL", TimeZone.getTimeZone("America/Maceio"));
      timeZonePorEstado.put("SE", TimeZone.getTimeZone("America/Bahia"));
      timeZonePorEstado.put("BA", TimeZone.getTimeZone("America/Bahia"));
      timeZonePorEstado.put("MG", TimeZone.getTimeZone("America/Sao_Paulo"));
      timeZonePorEstado.put("ES", TimeZone.getTimeZone("America/Sao_Paulo"));
      timeZonePorEstado.put("RJ", TimeZone.getTimeZone("America/Sao_Paulo"));
      timeZonePorEstado.put("SP", TimeZone.getTimeZone("America/Sao_Paulo"));
      timeZonePorEstado.put("PR", TimeZone.getTimeZone("America/Sao_Paulo"));
      timeZonePorEstado.put("SC", TimeZone.getTimeZone("America/Sao_Paulo"));
      timeZonePorEstado.put("RS", TimeZone.getTimeZone("America/Sao_Paulo"));
      timeZonePorEstado.put("MS", TimeZone.getTimeZone("America/Campo_Grande"));
      timeZonePorEstado.put("MT", TimeZone.getTimeZone("America/Cuiaba"));
      timeZonePorEstado.put("GO", TimeZone.getTimeZone("America/Sao_Paulo"));
      timeZonePorEstado.put("DF", TimeZone.getTimeZone("America/Sao_Paulo"));
   }

**Comment by Samuel-Oliveira** [comment]
Obrigado Por compartilhar @lazaru 
@GustavoAlves1993 O LocalDateTime.now() traz a TimeZone do seu servidor, Se o estado exige uma diferente, Você tem, que setar isso manualmente.

Certo?

**Comment by GustavoAlves1993** [comment]
Primeiramente obrigado @lazaru e @Samuel-Oliveira pela ajuda.

eu fiz o seguinte, em cima da dica do @lazaru criei essa função

`
public ZoneId returnZone(String uf) {
        String zoneString = "";
        
        switch(uf.toUpperCase()) {
            case "RO":
                zoneString = "America/Porto_Velho";
                break;
            case "AC":
                zoneString = "America/Rio_Branco";
                break;
            case "AM":
                zoneString = "America/Manaus";
                break;
            case "RR":
                zoneString = "America/Boa_Vista";
                break;
            case "PA":
            case "AP":
                zoneString = "America/Belem";
                break;
            case "TO":
            case "MA":
            case "PI":
            case "RN":
            case "PB":
            case "SE":
            case "BA":    
                zoneString = "America/Bahia";
                break;
            case "CE":
                zoneString = "America/Fortaleza";
                break; 
            case "PE":
                zoneString = "America/Recife";
                break;
            case "AL":
                zoneString = "America/Maceio";
                break;             
            case "MG":
            case "ES":
            case "RJ":
            case "SP":
            case "PR":
            case "SC":
            case "RS":
            case "GO":
            case "DF":    
                zoneString = "America/Sao_Paulo";
                break;
            case "MS":
                zoneString = "America/Campo_Grande";
                break;
            case "MT":
                zoneString = "America/Cuiaba";
                break;
        }  
        
        ZoneId zone = ZoneId.of(zoneString);
        
        return zone;
    }
`

e na chamada ficou assim

`cancela.setDataEvento(LocalDateTime.now(fNFCe.returnZone("AM")));`

porém mesmo assim no XML de cancelamento ele gerou com -03:00, fiz o teste diretamente na maquina do cliente em Manaus.

**Comment by resplandes** [comment]
Bom dia, você precisa atualizar seu java com o tzupdate segue um passo a passo.
[https://we.tl/t-Mz0xCpblXq](url)

**Comment by GustavoAlves1993** [comment]
Bom dia @resplandes o link que mandou está quebrado, poderia reenviar para eu dar uma olhada?

**Comment by Samuel-Oliveira** [comment]
#151

**Comment by resplandes** [comment]
@GustavoAlves1993 nao está quebrado amigão, copia e cola na url

**Comment by GustavoAlves1993** [comment]
java -jar validar-hora.jar
2019-11-28T10:03:25.842
2019-11-28T11:03:25.847

java -jar tzupdater.jar -f
Using https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz as source for tzdata bundle.
Cant rename {0} to {1}.

Ambas as datas estão corretas(AM e SP), porém mesmo assim executei o comando do tzupdater por garantia, porém mesmo assim o cancelamento não foi, gerou novamente com -03:00

**Comment by lazaru** [comment]
boa noite isso aqui funcionou perfeitamente para mim, so verifique se o horario na maquina do cliente esta correto.
aqui imprimiu:
AM:2019-11-28T19:11:54.060
SP:2019-11-28T21:11:54.062

exatamente o mesmo horario impresso aqui: https://www.timeanddate.com/worldclock/brazil

`import java.time.LocalDateTime;
import java.time.ZoneId;

public class TimeTest {
	public static ZoneId returnZone(String uf) {
        String zoneString = "";
        
        switch(uf.toUpperCase()) {
            case "RO":
                zoneString = "America/Porto_Velho";
                break;
            case "AC":
                zoneString = "America/Rio_Branco";
                break;
            case "AM":
                zoneString = "America/Manaus";
                break;
            case "RR":
                zoneString = "America/Boa_Vista";
                break;
            case "PA":
            case "AP":
                zoneString = "America/Belem";
                break;
            case "TO":
            case "MA":
            case "PI":
            case "RN":
            case "PB":
            case "SE":
            case "BA":    
                zoneString = "America/Bahia";
                break;
            case "CE":
                zoneString = "America/Fortaleza";
                break; 
            case "PE":
                zoneString = "America/Recife";
                break;
            case "AL":
                zoneString = "America/Maceio";
                break;             
            case "MG":
            case "ES":
            case "RJ":
            case "SP":
            case "PR":
            case "SC":
            case "RS":
            case "GO":
            case "DF":    
                zoneString = "America/Sao_Paulo";
                break;
            case "MS":
                zoneString = "America/Campo_Grande";
                break;
            case "MT":
                zoneString = "America/Cuiaba";
                break;
        }  
        
        ZoneId zone = ZoneId.of(zoneString);
        
        return zone;
    }
	
	public static void main(String[] args) {
		System.out.println("AM:"+LocalDateTime.now(returnZone("AM")));
		System.out.println("SP:"+LocalDateTime.now(returnZone("SP")));
	}

}`

**Comment by samuelpc7** [comment]
Nunca tive esse problemas com relação a data, o único que tive foi com relação ao horário de verão desses dias que foi abolido pelo Bolsonaro, em algums PCs com windows tive que desabilitar o ajuste altomatico pro horário de verão e pronto.
Para os meus clientes Linux não tive problema com essa mudança ..

Athene Sistemas e Informática ME

________________________________

**Comment by matheusmahl** [comment]
Sei que está fechado mas vale destacar:

Mesmo mandando a data certa no Evento, acabava enviando o timezone errado, por causa da remoção do horário de verão, o qual algumas máquinas não estavam preparadas e atualizadas para isso.

Além de colocar a data certa no Evento de cancelamento, é possível colocar a  timezone na função que monta o cancelamento:

CancelamentoUtil.montaCancelamento(eventoCancelamento, configuracoesNFe, **ZoneId.systemDefault()**);

Nesse caso irá pegar o timezone do sistema.

Caso não for setado, é usado o ZoneId.of("Brazil/East"), conforme o método XmlNfeUtil.dataNfe().

**Comment by GustavoAlves1993** [comment]
@matheusmahl estava fechado porém eu ainda estava com problema relatado, e graças a sua colaboração finalmente consegui resolver o problema, estava acontecendo exatamente como vc falou, mesmo eu passando o timezone ele estava enviando o timezone errado, após alterar o método CancelamentoUtil.montaCancelamento inserindo o timezone finalmente a nfc-e foi cancelada, muito obrigado.

**Comment by lazaru** [comment]
@GustavoAlves1993 bom dia, vc não tem que alterar método da lib para funcionar ninguém aqui esta fazendo isso, vc tem que resolver na fonte o seu problema e no meu caso era atualizar a jre do cliente para a mais recente, o java tem seu proprio mecanismo de data com o horario de verão, quando se alterou isso via decreto o algorítimo ficou errado, por isso precisa fazer update.
se por acaso por algum motivo não pode colocar uma nova jre tem como rodar um fix para corrigir, me procure que passo o link(não tenho agora), mas a maneira mais facil e ir para uma jre mais recente.
Mas vc vai precisar informar a data com o zoneId sempre(e mais seguro).
