### ISSUE TITLE
Erro processo ManifestacaoUtil.criaProcEventoManifestacao

### ISSUE THREAD

**Issue by juceliocalado** [Samuel-Oliveira/Java_NFe#186]
A seguinte mensagem é retornada na rotina : 
# Erro: br.com.swconsultoria.nfe.schema.envConfRecebto.TProcEvento cannot be cast to br.com.swconsultoria.nfe.schema.envEpec.TProcEvento

Dependência usada :
		<dependency>
			<groupId>br.com.swconsultoria</groupId>
			<artifactId>java-nfe</artifactId>
			<version>4.00.12</version>
			<exclusions>
				<exclusion>
					<artifactId>jaxb-xjc</artifactId>
					<groupId>com.sun.xml.bind</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jaxb-impl</artifactId>
					<groupId>com.sun.xml.bind</groupId>
				</exclusion>
			</exclusions>
		</dependency>

Se for possível poderia dar uma olhada para realizar correção nas próximas versões Samuel, Vlw.

**Comment by Samuel-Oliveira** [comment]
Tudo bom @juceliocalado 
Vou resolver isso essa semana!

Obrigado por notificar.

**Comment by Samuel-Oliveira** [comment]
Feito e acabei de lançar a versão.
