### ISSUE TITLE
Conflito de dependencias

### ISSUE THREAD

**Issue by MarkusLuan** [Samuel-Oliveira/Java_NFe#187]
Brother, tudo blz? Estou usando sua dependencia aqui num projeto maven. E percebi que tinha conflito de dependencias (usando o graph do netbeans), flui excluindo dependencia por dependencia e depois adicionando só uma. Aí quando testo com a tua dá bem uns 4 conflitos. Espero que essa informação possa te ajudar. Vlw, brother.

**Comment by Samuel-Oliveira** [comment]
Olá, E quais são os COnflitos?

**Comment by Samuel-Oliveira** [comment]
Fechado por inatividade.
