### ISSUE TITLE
Dúvida sobre A1 e A3

### ISSUE THREAD

**Issue by clayderson** [Samuel-Oliveira/Java_NFe#189]
Olá, bom dia!

Gostaria de saber se eu posso assinar um XML localmente usando um A3 de uma empresa X e depois enviar esse XML pra um sistema web que faria a comunicação com a SEFAZ usando um A1 estático da empresa Y.

Se funcionar, no caso de uma emissão de nota por exemplo, ela seria emitida no nome da empresa X que assinou o XML com o A3 ou da empresa Y que fez a requisição usando um A1?

Desculpe se não fui claro. Meu objetivo é construir uma API web que emita notas fiscais com suporte a certificados A3 por meio de um plugin instalado localmente no cliente.

Obrigado!

**Comment by Samuel-Oliveira** [comment]
Bom dia @clayderson 
Não pode.
Tanto a Assinatura quanto o envio devem pertencer a Empresa Emitente.
Vc precisará ter um Sistema local no cliente que efetua as duas operações.
