### ISSUE TITLE
Converter TRetConsCad pra XML

### ISSUE THREAD

**Issue by clayderson** [Samuel-Oliveira/Java_NFe#190]
Viabilizar a conversão de objetos TRetConsCad pro formato XML usando a classe XmlNfeUtil.

**Comment by fredwilliamtjr** [comment]
Cara isso é simples, porque você não faz e sobe pro Samuel aprovar?

**Comment by clayderson** [comment]
O próprio Samuel se propôs a fazer me pediu para que criasse o issue.

Além disso, coisas que são simples para uns são complexas para outros, afinal, ninguém sabe tudo. Talvez você possa fazer já que, aparentemente, conhece o processo!? Seria de grande valia!

Obrigado!

**Comment by fredwilliamtjr** [comment]
Desculpe no meio de um processo já combinado,  sim eu poderia fazer, se ninguém maia tiver tempo segunda eu faço.

**Comment by Samuel-Oliveira** [comment]
Fala Pessoal. Já Fiz e acabei de lançar a versão.
