### ISSUE TITLE
Erro em ambiente Multithread

### ISSUE THREAD

**Issue by ElizioRezende** [Samuel-Oliveira/Java_NFe#191]
Utilizando a biblioteca na versão 4.00.13 em ambiente web com múltiplas empresas ocorre constantemente o erro: CNPJ do transmissor do lote difere do CNPJ do transmissor da consulta

Vi que anteriormente criaram a Issue https://github.com/Samuel-Oliveira/Java_NFe/issues/66, mas aparentemente não foi resolvida.

Alguém mais se deparou com esse erro?

**Comment by Samuel-Oliveira** [comment]
Aqui tenho varios ambiente web. Alguns com emissão absurda.
E não vejo tal erro.

Favor criar um projeto que simule tal erro e me enviar por gentileza.

**Comment by ElizioRezende** [comment]
Ok. Obrigado, vou fazer isso. Só a título de informação o meu ambiente tem 300 CNPJ's com 3 PDV's cada enviando vendas o tempo inteiro. Assim que o projeto de teste tiver pronto para tentar simular esse ambiente de produção eu posto aqui.

**Comment by Samuel-Oliveira** [comment]
Se Está issue não for respondida em 5 dias, será fechada por inatividade.

**Comment by Samuel-Oliveira** [comment]
Fechado por inatividade
