### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by felipeparente** [Samuel-Oliveira/Java_NFe#192]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by br.com.swconsultoria.nfe.dom.ConfiguracoesNfe (file:/Users/felipeparente/wspaces/workspace_java/NFe/src/main/lib/java-nfe-4.00.13.jar) to field java.nio.charset.Charset.defaultCharset
WARNING: Please consider reporting this to the maintainers of br.com.swconsultoria.nfe.dom.ConfiguracoesNfe
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Estou recebendo essas mensagens sempre que executo algo.
Não tenho ideia do que pode ser, se é erro meu ou na biblioteca.

**Comment by Samuel-Oliveira** [comment]
Tdo bom?
Não é erro, é um aviso caso vc esteja usando versões mais novas do Java. Em um futuro proximo uma das operações que eu uso no projeto será desabilitada. Chuto uns 5 anos +-

Pode continuar normalmente, que isso não atrapalha em nada o projeto.

**Comment by felipeparente** [comment]
OK obrigado....
