### ISSUE TITLE
Envio em contingência

### ISSUE THREAD

**Issue by HudsonRomualdo** [Samuel-Oliveira/Java_NFe#193]
Olá pessoal.
Tenho uma dúvida com relação a "quando" devo enviar a NFe em contingência.

Ao chamar o método "enviarNfe" da classe "Nfe" e a SEFAZ está fora do ar, ela me retorna uma exceção do tipo "NfeException".
A mensagem da exceção varia. (já peguei "null", e "Connection reset")

**Então fica a pergunta:**
Nesse objeto existe alguma mensagem que identifique que eu deva enviar a NFe em contingência ou só o fato de ter retornado essa exceção já é motivo para o envio em contingência?

**Comment by fredwilliamtjr** [comment]
@HudsonRomualdo, o NfeException retorna muitas coisas inclusive avisos de validação da Sefaz!
Você precisa tratar que tipos de retornos você vai decidir tratar como contingencia.
Ou você pode correr o risco de emitir uma NFCe em contingencia com erro de validação.

Eu já vi alguns sistemas que emitem em contingencia por qualquer motivo, ai depois tem que ficar ajustando o XML para poder transmitir ele para Sefaz!

O que eu faço e colocar um try e se for esses abaixo eu trato como contingencia!

`if (e.getMessage().contains("No route to host: connect") || e.getMessage().contains("Read timed out") || e.getMessage().contains("Connection timed out: connect") ||
                    e.getMessage().contains("nfce.svrs.rs.gov.br") || e.getMessage().contains("nfe.svrs.rs.gov.br") ||
                    e.getMessage().contains("nfce-homologacao.svrs.rs.gov.br") || e.getMessage().contains("nfe-homologacao.svrs.rs.gov.br")) {
`

Se for uma dessas acima eu faço os ajustes e imprimo como contingencia, se não eu dou um throw e; na maioria das vezes isso termina com uma mensagem para usuário!

**Comment by HudsonRomualdo** [comment]
Ola @fredwilliamtjr.
Obrigado pelo retorno.

Meu try está dessa forma para contingência:
`if(e.getMessage().toLowerCase().contains("connection")){`

Mas dessa vez a SEFAZ me retornou "nfe.sefaz.go.gov.br"???

Mas foi bacana perceber que:
- 1º não sofro sozinho. =)
- 2º vc está tratando no mesmo formato. (procurando Strings na mensagens retornada)

**Comment by fredwilliamtjr** [comment]
> Ola @fredwilliamtjr.
> Obrigado pelo retorno.
> 
> Meu try está dessa forma para contingência:
> `if(e.getMessage().toLowerCase().contains("connection")){`
> 
> Mas dessa vez a SEFAZ me retornou "nfe.sefaz.go.gov.br"???
> 
> Mas foi bacana perceber que:
> 
> * 1º não sofro sozinho. =)
> * 2º vc está tratando no mesmo formato. (procurando Strings na mensagens retornada)

e.getMessage().contains("nfce.svrs.rs.gov.br") || e.getMessage().contains("nfe.svrs.rs.gov.br") || e.getMessage().contains("nfce-homologacao.svrs.rs.gov.br") || e.getMessage().contains("nfe-homologacao.svrs.rs.gov.br"

São os retornos padrões da Lib quando ela nem pinga nesses endereços, pelo menos aqui foi sempre assim!
E tem os outros que pelo meu entendimento e quando o endereço esta pingando mais o retorno demora ou não responde como deveria!
