### ISSUE TITLE
Erro na ConsultaCadastro no MS - Rejeicao: 587 

### ISSUE THREAD

**Issue by dausech** [Samuel-Oliveira/Java_NFe#196]
XML Enviado:

``<?xml version="1.0" encoding="UTF-8"?>
<ConsCad versao="2.00"
    xmlns="http://www.portalfiscal.inf.br/nfe">
    <infCons>
        <xServ>CONS-CAD</xServ>
        <UF>MS</UF>
        <CNPJ>37577145000160</CNPJ>
    </infCons>
</ConsCad>``

Rejeicao: 587 
Usar somente o namespace padrao da NF-e

**Comment by ElizioRezende** [comment]
Boa tarde. Hoje tive esse problema e fui dar uma investigada. Depois de muito quebrar a cabeça consegui fazer a consulta da nota em MS. Teria que analisar o impacto e se é a forma correta de fazer.
Abs

**Comment by arimolo** [comment]
@Samuel-Oliveira, boa tarde. Você viu esse problema? Tem planos para lançar uma versão com algum tipo de correção? Desde já agradeço muito pela atenção.

**Comment by arimolo** [comment]
@ElizioRezende, bom dia.
Você deixou de usar a lib e importou todo o código para fazer essa alteração? 
E essa alteração na NFeConsultaProtocolo4Stub que você disse que resolveu para MS não quebrou a consulta para as demais UF's?

Obrigado! 
Bom final de semana!

**Comment by Samuel-Oliveira** [comment]
Olá pessoal, Desculpe a demora.
Esse tipo de erro já ocorreu, e eh uma particularidades de Alguns servidores.
Então tenho que criar um novo stub somente para estes estados.
Farei isso nesse final de semana e aviso aqui.

**Comment by ElizioRezende** [comment]
@arimolo Desculpe a demora.
Eu baixei o projeto do Samuel e recompilei com a alteração.
Se quiser posso te enviar o jar até o @Samuel-Oliveira publicar uma nova versão.
Abs

**Comment by Samuel-Oliveira** [comment]
Merge efetuado, liberado para snapshot em breve em produção.
