### ISSUE TITLE
Erro ao enviar epec

### ISSUE THREAD

**Issue by carolpiovesan** [Samuel-Oliveira/Java_NFe#198]
Estou tentando enviar um epec onde o destinatário tem CPF, porém a classe EventoEpec somente tem a função setCnpjDestinatario. Outro problema que encontrei é que quando tento mandar a Epec com destinatário com CNPJ ele da o erro "491 - Rejeicao: O tpEvento informado invalido". Pelo que eu pesquisei esse erro da por conta do cOrgao que no meu caso está como 43 mas na documentação consta que esse campo dever ser informado como 91. Desde já agradeço

**Comment by Samuel-Oliveira** [comment]
OKs. Vou criar as correções em breve

**Comment by Samuel-Oliveira** [comment]
Liberado para SnapShot em breve em produção.
