### ISSUE TITLE
Erro de validação de CNPJ ao cancelar NFe com emitente PF

### ISSUE THREAD

**Issue by sillassanttos** [Samuel-Oliveira/Java_NFe#199]
**Erro de validação de CNPJ ao cancelar NFe com emitente PF**

O emitente é produtor rural, possui CPF e IE, consigo autorizar as NFe com sucesso passando a série 920 ou superior. 
Porem, nao consigo cancelar a mesma NF-e, pois o evento de cancelamento exige CNPJ, mas o emitente possui apenas o CPF.

Já tentei acrescentar zeros a esquerda para passar 14 dígitos, mas cai na validação do cpf do certificado.

**Testei sem sucesso com as versões: 4.00.11 e 4.00.13**

![image](https://user-images.githubusercontent.com/60371134/97513342-5d6f5980-1962-11eb-9429-eef8eb0657d6.png)

XML de envio de cancelamento:
`<?xml version="1.0" encoding="UTF-8"?><envEvento xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00"><idLote>1</idLote><evento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infEvento Id="ID1101115320100007875274419155920000000011162271509701"><cOrgao>53</cOrgao><tpAmb>2</tpAmb><CNPJ>78752744191</CNPJ><chNFe>53201000078752744191559200000000111622715097</chNFe><dhEvento>2020-10-28T21:09:25-03:00</dhEvento><tpEvento>110111</tpEvento><nSeqEvento>1</nSeqEvento><verEvento>1.00</verEvento><detEvento versao="1.00"><descEvento>Cancelamento</descEvento><nProt>353200000243660</nProt><xJust>CANCELAR NF POR CAUSA DE DADOS INCORRETOS</xJust></detEvento></infEvento><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#ID1101115320100007875274419155920000000011162271509701"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>AIVQfRPpB4N1ebFfVhTJMv0HSOQ=</DigestValue></Reference></SignedInfo><SignatureValue>hWTRE/jMwz0+nvs5YOHFM89sRlT86rBCMrzU+TEG8UjGubks+vT3wHLXAjX/8jjQdZAk0KtiaYDYC2PN1ipJqA2V9LsF/BvJ91EYjc7MVmVUnem5VkCUsGga4ruxJsHrog5xdnRRs8tzrCu33yoviTwmr0TqDBC6/T2FUep1i3oTFfsK0FXktZWV9aJlsECZwcILIbNpv6vLxKxV0T0IKlnymH6nloyfrxRKiS8q43pYT+Z39590pIb5DVBUPdrJfInotL/7x8rjY7WYe/2bzKi/2eYcTXkJYSKs9YHV5waU3xSM63UQNXgGHYu4i+w+R5sdSF/s/vpBe7kpgfz8og==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHbjCCBVagAwIBAgIIa2XAUuiiUF0wDQYJKoZIhvcNAQELBQAwdjELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEaMBgGA1UEAxMRQUMgU0FGRVdFQiBSRkIgdjUwHhcNMjAwMjI4MTk1NjQ4WhcNMjEwMjI4MTk1NjQ4WjCBzTELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEVMBMGA1UECxMMUkZCIGUtQ1BGIEExMRQwEgYDVQQLEwsoRU0gQlJBTkNPKTEXMBUGA1UECxMOMjM2MTE5MDcwMDAxOTIxKzApBgNVBAMTIkZBQklPIFRBS0FTSEkgWUFNQU1PVE86Nzg3NTI3NDQxOTEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK5iPEG0wF6gO5XJN8K/DoE7sZu+5hUlLgpIvrsRfnPFQH1XAIeX5FE8ze5iDIieqU3hSq9574GtowTkJ85S/T9OIG/bYn4JUKoXF4teD9K6W2QNs2xNdseOK4taBJG562aY8Le2/lhNgMosXe7g73YLE0C7sICMjN62dpHIc3h0LTnErERA4D5vvS2Gp/GV8eX4/cXjewtL0HiAzC72PVHMpbnC64OcjqWJp30/0kFiizYHmisyyZTmhUUKeRREkCwWaECk11ZKRvTAOhN1qUBBhx8hTpARqsly7B6LUrDe9vSypqxnUzMh/N4783kzAjclAfTCJWfNQiL2HsTBANAgMBAAGjggKmMIICojAfBgNVHSMEGDAWgBQpXkvVRky7/hanY8EdxCby3djzBTAOBgNVHQ8BAf8EBAMCBeAwbQYDVR0gBGYwZDBiBgZgTAECATMwWDBWBggrBgEFBQcCARZKaHR0cDovL3JlcG9zaXRvcmlvLmFjc2FmZXdlYi5jb20uYnIvYWMtc2FmZXdlYnJmYi9hYy1zYWZld2ViLXJmYi1wYy1hMS5wZGYwga4GA1UdHwSBpjCBozBPoE2gS4ZJaHR0cDovL3JlcG9zaXRvcmlvLmFjc2FmZXdlYi5jb20uYnIvYWMtc2FmZXdlYnJmYi9sY3ItYWMtc2FmZXdlYnJmYnY1LmNybDBQoE6gTIZKaHR0cDovL3JlcG9zaXRvcmlvMi5hY3NhZmV3ZWIuY29tLmJyL2FjLXNhZmV3ZWJyZmIvbGNyLWFjLXNhZmV3ZWJyZmJ2NS5jcmwwgYsGCCsGAQUFBwEBBH8wfTBRBggrBgEFBQcwAoZFaHR0cDovL3JlcG9zaXRvcmlvLmFjc2FmZXdlYi5jb20uYnIvYWMtc2FmZXdlYnJmYi9hYy1zYWZld2VicmZidjUucDdiMCgGCCsGAQUFBzABhhxodHRwOi8vb2NzcC5hY3NhZmV3ZWIuY29tLmJyMIGWBgNVHREEgY4wgYuBFkZBQklPVEFLQVNISUBHTUFJTC5DT02gOAYFYEwBAwGgLxMtMTAwNDE5Nzc3ODc1Mjc0NDE5MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwoB4GBWBMAQMFoBUTEzAwMDAwMDAwMDAwMDAwMDAwMDCgFwYFYEwBAwagDhMMNzg3NTI3NDQxMDAxMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDAJBgNVHRMEAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQAcvZGIfTZrvJUzM07f4NYLZ/HQaUVcERqcqhcy46EGoY/O7LmCb+dD6CLbDWz1V0ZSp4hnOVwBsuydQ69iWdV0iDqAEkHz27tPt8rJ2kIhMha8/N9JBNhVXINhj5rFmPlQ2yyPoQkD2dgUS+P4tOD4rKk63LjTFlnCFfqqeFjZbwgDifEVmIGVxb4e1dW7BsdROduupi5BQ6e3jhwmOIqzU7d9DujPg/CQd+rwljGXDO+3V+MoMO7EFv6RjK1dekQbktIQ6F+KRuXoj5BmEmuQxagth0Kk8NlOFLuXhkPIzenZ4bzgIBSfPRv2Q6O/tQuDlOAuGooFP6GZ0txTG2BuQozYZ7OdvQPKySoknMBy4HpQyHPmPmL4hyD0ofnb2AMwrz6IAb9lvXMjbIJgxYoTv0sqmQOp3hr9OzLX+U+wMEB1598ruVdktzuZ+Ed4suThphKz9Q0qLT8a/sP9Tgna8cVE3BWOIlsgtlKnVL9knorG0zZAR3X4qNaKSnLDGTR/Y4cXkKTzA5Z65VP9WYu1qo4U/8dzazAxWOe/6xGuaEBCaXOXCMNpXZDdJL64/pZfzCjFtAbQ43MI+5Xbpwjoai5yEv6t8fjb/pmFrd8Vx3djk9du2NSvI56jD37Wa3St8B9Ni27MH8PkEOaB4rXcAD1inySI3I0wvbRdeV36jA==</X509Certificate></X509Data></KeyInfo></Signature></evento></envEvento>`

**Comment by Samuel-Oliveira** [comment]
Tudo bom? 
O Objeto evento tem o campo CPF.
