### ISSUE TITLE
URLs Contingencia para estados que utilizam o SVRS

### ISSUE THREAD

**Issue by MatiGavazzoni** [Samuel-Oliveira/Java_NFe#201]
Bom dia, ontem me deparei com um problema no servidor SVRS. Ao tentar usar a contingencia, mesmo marcando como "true" o parâmetro contingenciaSCAN, o método getURL(), não devolvia a URL do SVC-AN, fazendo testes em homologação e produção, com diversos estados, me parece que o problema só ocorre para os estados que utilizam o Sefaz Virtual RS, os demais ao marcar ContigenciaSCAN a URL parece vir correta. Para resolver o problema acabei usando o parâmetro ArquivoWebServices, e  no meu arquivo para o estado de SC coloquei as URLs do Sefaz Virtual Contingencia AN. Não sei se é isso mesmo que deve ser feito, ou o método getURL() tem um pequeno bug.

**Comment by Samuel-Oliveira** [comment]
Corrigido Em Snapshot em breve em produção
