### ISSUE TITLE
Dúvida sobre nfeDistDFeInteresse

### ISSUE THREAD

**Issue by kaoecoito** [Samuel-Oliveira/Java_NFe#203]
Estou tentando pegar a nota por chave e sempre recebo a mensagem: Rejeicao: NF-e indisponivel para o emitente

Fiz alguns testes e me parece que o próprio emissor não pode pegar dados da nota, somente os terceiros, é isso mesmo?
Tenho um sistema secundário que não tem acesso físico ao XML da nota e pensei em usar esta chamada paga pegar a nota, consegue confirmar se realmente não é possível mesmo?

Obrigado

**Comment by Samuel-Oliveira** [comment]
Boa Noite. Somente o Destinatário,Envolvidos na operação (Transportadora) e cnpj listados no autXml podem ter acesso ao XML.
A sefaz não permite que o próprio emitente tenha acesso!
