### ISSUE TITLE
Fazer download XML com o certificado do emitente .

### ISSUE THREAD

**Issue by RafaelPavanati** [Samuel-Oliveira/Java_NFe#205]
Estou tentando fazer o download do XML pela chave de acesso de uma nota fiscal com o certificado do emitente, e recebo o erro "Rejeicao: NF-e indisponivel para o emitente", existe algum recurso que possa resolver esse problema ?

**Comment by resplandes** [comment]
Boa tarde, quem emite não consegue fazer down somente quem recebe ou
autorizado, quem emite tema  obrigação de guardar o XML.



*Willian Resplandes Matias*

Professor Esp. em Tecnologias para desenvolvimento de Aplicações Web e
Docência no Ensino Superior

Sócio Proprietário da SoftJava – Programador Java Sênior

SoftJava Consultoria e Serviços em Informática

( Fone: 66.3575.266

( Celular: 66 99971-6730 <(66)%2099971-6730>

Skype: willian.matias.frialto

w <willian.matias@frialto.com.br>illianresplandes@gmail.com

Antes de imprimir, lembre-se do seu compromisso com o meio ambiente




Em seg., 11 de jan. de 2021 às 14:07, Rafael Vieira Pavanati <
notifications@github.com> escreveu:
