### ISSUE TITLE
Especificando IPI [PERGUNTA]

### ISSUE THREAD

**Issue by naiteon** [Samuel-Oliveira/Java_NFe#206]
Há alguma maneira de adicionar o IPI individualmente em cada produto?

Por que notei que há o metodo setVIPI no totalizador de ICMS.

**Comment by dmitrukbr** [comment]
Segue um exemplo.

TIpi tIpi = new TIpi();

IPITrib ipiTrib = new IPITrib();

tIpi.setIPITrib(ipiTrib);

JAXBElement<TIpi> ipiConvertido = new
ObjectFactory().createTNFeInfNFeDetImpostoIPI(tIpi);
imposto.getContent().add(ipiConvertido);

Em sex., 15 de jan. de 2021 às 11:55, Rodrigo Teixeira <
notifications@github.com> escreveu:

**Comment by naiteon** [comment]
Muito obrigado @dmitrukbr ! Um abraço!
