### ISSUE TITLE
Download NFE Chave

### ISSUE THREAD

**Issue by Samuel-Oliveira** [Samuel-Oliveira/Java_NFe#21]
Atualizar Lib para Pegar o Novo WebService de NFeDistribuicaoDFe. E adicionar download de Nfe Por Chave.

**Comment by Samuel-Oliveira** [comment]
Alterações feitas, mas o WebService em Produção ainda não está aceitando a versão 1.01.
Aguardando a liberação para Subir a Nova Versão.

**Comment by Igor-A-Nunes** [comment]
Tem a possibilidade do download xml completo com os itens?

**Comment by Samuel-Oliveira** [comment]
Concluido e Adicionado na Versão 3.10.6
