### ISSUE TITLE
Gerar HTML/PDF a partir do XML da NFCe

### ISSUE THREAD

**Issue by abadvincula** [Samuel-Oliveira/Java_NFe#212]
Possibilidade de gerar um DANFE em HTML/PDF a partir do XML de retorno da SEFAZ. Existe um modelo parcial [aqui](https://www.javac.com.br/jc/posts/list/2532-danfce-impressao-para-nfce.page), autor: **phlfulgore**. E artigo sobre [XLM to HTML](https://www.baeldung.com/java-convert-xml-to-html). A ideia de usar HTML possibilita uma aplicação mais leve minimizando a necessidade de bibliotecas adicionais.

**Comment by Samuel-Oliveira** [comment]
Tdo Bom? 
@abadvincula gerar danfe pdf é um desejo que tenho a algum tempo para a lib, e pretendo fazer utilizando Jasper. Porém para Html eu já não tenho conhecimento, você tem? Quer fazer essa parte?

**Comment by abadvincula** [comment]
Pois é @Samuel-Oliveira, tambem nao tenho conhecimento (ainda) em html... Vou estudar aqui, no pouco tempo que tenho, é tentar fazer... vlw!

**Comment by jean-merelis** [comment]
@Samuel-Oliveira Aproveitando tua experiência com o Jasper, gostaria de tirar uma dúvida sobre o DANFE utilizando o Jasper.

No caso das informações complementares não caberem no espaço reservado, como que passo para próxima página somente o restante do texto que não foi impresso na primeira?

**Comment by Samuel-Oliveira** [comment]
Feito na Biblioteca https://github.com/Samuel-Oliveira/Java_Danfe
