### ISSUE TITLE
Erro na consulta CTe e NFe

### ISSUE THREAD

**Issue by thomasmazon** [Samuel-Oliveira/Java_NFe#213]
Ao utilizar a API estou recendo o erro:

br.com.swconsultoria.nfe.exception.NfeException: Implementation of JAXB-API has not been found on module path or classpath.
br.com.swconsultoria.nfe.DistribuicaoDFe.consultaNfe(DistribuicaoDFe.java:101)

**Comment by Samuel-Oliveira** [comment]
Olá @thomasmazon esta usando MAven ou External jar;

**Comment by thomasmazon** [comment]
esta usando gradle

**Comment by Samuel-Oliveira** [comment]
Bom isso é algum conflito de bibliotecas. Envie aqui todas as dependencia do gradle que vc usa.

**Comment by thomasmazon** [comment]
Vou enviar o arquivo gradle, mas para conhecimento, localmente ele roda com sucesso. Apenas em docker usando openJDK

Segue dependencias


dependencies {
    /* batch dependencies */
    implementation("org.springframework.boot:spring-boot-starter-batch")
    runtimeOnly("org.hsqldb:hsqldb")

    "scm"("org.eclipse.jgit:org.eclipse.jgit:4.9.2.201712150930-r")

    implementation("org.springframework:spring-oxm:4.3.10.RELEASE")
    implementation("com.thoughtworks.xstream:xstream:1.4.11.1")

    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-resource-server")
    implementation("org.springframework.security:spring-security-oauth2-client") {
        exclude("org.springframework.security", "spring-security-web")
    }
    implementation("org.springframework.boot:spring-boot-starter-webflux")

    implementation("org.springframework.boot:spring-boot-starter-freemarker")

    implementation(platform("software.amazon.awssdk:bom:2.16.8"))
    implementation("software.amazon.awssdk:s3")

    implementation(platform("com.amazonaws:aws-java-sdk-bom:1.11.964"))
    implementation("com.amazonaws:aws-java-sdk-s3")


    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.flywaydb:flyway-core")

    implementation("io.springfox:springfox-swagger2:2.9.2")
    implementation("io.springfox:springfox-swagger-ui:2.9.2")

    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.10.3")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.0")

    implementation("br.com.swconsultoria:java-nfe:4.00.13")
    implementation("com.github.wmixvideo:nfe:3.0.6")
    implementation("br.com.swconsultoria:java-cte:3.00.6")


    implementation("org.hibernate", "hibernate-envers", "5.4.14.Final")
    implementation("com.vladmihalcea:hibernate-types-52:2.9.8")
    implementation("io.projectreactor.kotlin:reactor-kotlin-extensions:1.0.2.RELEASE")

//    implementation("javax.xml.bind:jaxb-api:2.3.1")
//    implementation("javax.activation:activation:1.1.1")
//    implementation("org.glassfish.jaxb:jaxb-runtime:3.0.0")
//
    implementation("javax.xml.bind:jaxb-api:2.3.0")
    implementation("javax.activation:activation:1.1.1")
    implementation("org.glassfish.jaxb:jaxb-runtime:2.3.0")

    implementation("io.github.microutils:kotlin-logging:1.7.9")

    implementation("org.apache.poi:poi:4.1.2")
    implementation("com.opencsv:opencsv:4.3")
    implementation("io.jsonwebtoken:jjwt:0.9.1")

    implementation("com.hazelcast:hazelcast:4.0.3")
    implementation("com.hazelcast:hazelcast-spring:4.0.3")
    implementation("org.postgresql:postgresql:42.2.18")


    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")

   //runtimeOnly("org.postgresql:postgresql")
    runtimeOnly("org.springframework.boot:spring-boot-devtools")
    testImplementation("org.springframework.boot:spring-boot-starter-test") {
        exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
    }
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.2.0")
    testImplementation("com.ninja-squad:springmockk:1.1.0")
    testImplementation("io.projectreactor:reactor-test:3.3.5.RELEASE")
    testImplementation("org.assertj:assertj-core:3.15.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.2.0")
    testImplementation("org.springframework.batch:spring-batch-test")

}

**Comment by Samuel-Oliveira** [comment]
@thomasmazon vc está importando a jaxb manualmente. Pode ser esse o conflito.
A lib nfe e cte já importa o jaxb

**Comment by Samuel-Oliveira** [comment]
@thomasmazon Resolveu? Se não for respondido em 3 dias irei fechar a Issue.
