### ISSUE TITLE
Erro ao enviar NFe

### ISSUE THREAD

**Issue by edivaldoms** [Samuel-Oliveira/Java_NFe#215]
Erro quando chama o método:
Nfe.montaNfe(configuracoesNfe, loteNotaSIGNED, true);

O log para depois dessa parte e não acontece mais nada:
####################################################################|#]
         Api Java Nfe - Vers?o 4.00.15-SNAPSHOT(B) - 01/04/2021       |#]
   Samuel Olivera - samuel@swconsultoria.com.br |#]
   Pasta Schemas: D:\TRABALHO\NFE\4.00\Schemas|#]
   Ambiente: Produ??o - Estado: Rio de Janeiro|#]
  ####################################################################|#]

**Comment by edivaldoms** [comment]
Aparece esse alerta antes do log acima:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by br.com.swconsultoria.nfe.dom.ConfiguracoesNfe (file:/D:/TRABALHO/EVOLI/evoli-003/NFe4/target/NFe4-3.0/WEB-INF/lib/java-nfe-4.00.15-20210401.172834-2.jar) to field java.nio.charset.Charset.defaultCharset
WARNING: Please consider reporting this to the maintainers of br.com.swconsultoria.nfe.dom.ConfiguracoesNfe
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by edivaldoms** [comment]
O problema está no CertificadoService.inicializaCertificado.
Na classe ConfiguracoesUtil.iniciaConfiguracoes linha: 69 ou 71
CertificadoService.inicializaCertificado(configuracoesNfe.getCertificado(),configuracoesNfe.getCacert());

**Comment by edivaldoms** [comment]
Quando NÃO informei o arquivo do cacerts, não apresenta erro, mas quando informei o arquivo cacerts:
br.com.swconsultoria.nfe.exception.NfeException: keystore password was incorrect
	at br.com.swconsultoria.nfe.util.ConfiguracoesUtil.iniciaConfiguracoes(ConfiguracoesUtil.java:74)

Como passar a senha do cacerts?

Já tentei gerar cacerts com senha "" (em branco), e também não deu certo.

**Comment by Samuel-Oliveira** [comment]
blz @edivaldoms?
Ao gerar o cacert vc tem que criar com a senha: changeit

Essa é a senha padrão dos Cacerts;

**Comment by edivaldoms** [comment]
Obrigado!

Gerei o cacert com essa senha, testei consultar a consulta da NF e funcionou, mas ao enviar apresentou exception que não esclarece o que pode ser.
####################################################################|#]
         Api Java Nfe - Vers?o 4.00.15-SNAPSHOT(B) - 01/04/2021       |#]
   Samuel Olivera - samuel@swconsultoria.com.br |#]
   Pasta Schemas: D:/TRABALHO/NFE/4.00/Schemas|#]
   Ambiente: Homologa??o - Estado: Rio de Janeiro|#]
  ####################################################################|#]
  000|#]
  111|#]
  111A|#]
  222|#]
  222B|#]
  333|#]
  [XML-ASSINADO]: <?xml version="1.0" encoding="UTF-8"?> ...
  444|#]
  555|#]
  666|#]
  111A|#]
  br.com.swconsultoria.nfe.exception.NfeException
	at br.com.swconsultoria.nfe.util.ConfiguracoesUtil.iniciaConfiguracoes(ConfiguracoesUtil.java:74)
	at br.com.swconsultoria.nfe.Nfe.enviarNfe(Nfe.java:142)

**Comment by edivaldoms** [comment]
Baixei o projeto Java_NFe, adicionei "e.printStackTrace();" na linha 74 do arquivo ConfiguracoesUtil.java

O exception acontece no projeto Java_Certificado:
br.com.swconsultoria.certificado.exception.CertificadoException
	at br.com.swconsultoria.certificado.CertificadoService.inicializaCertificado(CertificadoService.java:76)
	at br.com.swconsultoria.nfe.util.ConfiguracoesUtil.iniciaConfiguracoes(ConfiguracoesUtil.java:69)
	at br.com.swconsultoria.nfe.Nfe.enviarNfe(Nfe.java:142)

Baixei o projeto Java_Certificado 2.5-SNAPSHOT mas no arquivo:
br.com.swconsultoria.certificado.CertificadoService, linha 282:
Provider p = new sun.security.pkcs11.SunPKCS11(conf); O compilador indica que não tem esse parâmetro "conf" para esse construtor SunPKCS11.

Isolei esse trecho, mas não tenho o gpg instalado e deu erro na compilação.

**Comment by edivaldoms** [comment]
Isolei o gpg e consegui compilar o Java_Certificado
O Exception que ocorre é "java.io.EOFException" em:
br.com.swconsultoria.certificado.SocketFactoryDinamico, linha 75:
trustStore.load(fileCacerts, "changeit".toCharArray());


Mas o estranho que agora eu comentei o config.setCacert(...), para não informar o cacert e funcionou, consegui enviar a nota sem erros.

Acho que era problema de cache do Maven ou alguns problemas inexplicáveis de certificado.
