### ISSUE TITLE
Envio de eventos tenta assinar um XML já assinado

### ISSUE THREAD

**Issue by humbertosc** [Samuel-Oliveira/Java_NFe#217]
No ambiente que eu estou usando existe uma aplicação web e um microsserviço que trata o envio de NFe utilizando como dependência o Java_NFe.
Se não houver um certificado A1 informado para a empresa que está tentando emitir a nota o microsserviço usa o certificado da empresa que trabalho para se comunicar com a SEFAZ, portanto ele só pode ser utilizado na consulta de status e para a conexão segura com o web service da SEFAZ.
Quando um usuário não possui um certificado A1 o mesmo é assinado no navegador com o plugin WebPKI. Nesse cenário o XML é enviado já com a assinatura para o microsserviço. Na função de enviar uma NFe os métodos de assinar e de enviar são separados, o que me permite validar se existe uma assinatura e só assinar caso não haja. Já no método de enviar um evento a assinatura é feita dentro dos métodos da biblioteca, o que não me permite pular essa etapa quando o XML já está assinado.
Por causa deste comportamento ao tentar enviar o evento eu recebo o seguinte erro:
`Erro na validação: \n- Conteúdo inválido encontrado iniciando com o campo 'Signature'. No child element é esperado at this point.`

**Comment by Samuel-Oliveira** [comment]
Bom dia. @humbertosc 
Entendi seu ponto, vou providenciar agora um envio direto sem assinatura.
Na versão SNAPSHOT.
Entra aqui no discord pra lhe explicar como será: 
https://discord.gg/ZXpqnaV
