### ISSUE TITLE
Erro ao emitir nota em Santa Catarina

### ISSUE THREAD

**Issue by ArielAleksandrus** [Samuel-Oliveira/Java_NFe#218]
Ao tentar emitir uma nota fiscal para Santa Catarina, recebo o seguinte erro:

"WebService de URL_QRCODE não encontrado para Santa Catarina"

Aqui está o meu código

```
String qrCode = NFCeUtil.getCodeQRCode(
                    enviNFe.getNFe().get(0).getInfNFe().getId().substring(3),
                    config.getAmbiente().getCodigo(),
                    identificadorCSC,
                    codigoCSC,
                    WebServiceUtil.getUrl(config,DocumentoEnum.NFCE, ServicosEnum.URL_QRCODE));
```

Alguém tem alguma idéia do que pode estar acontecendo? Possivelmente, a url do WebService não está hardcoded nesta biblioteca, certo? Neste caso, como eu poderia adicionar manualmente?

**Comment by Samuel-Oliveira** [comment]
Blz @ArielAleksandrus ?
Até onde eu me lembro, SC era o ultimo estado a implementar NFCe.
Já entrou em produção?
Caso sim, me passa a URL do QrCode e A url de consulta NFCe que eu já adiciono pra vc.

**Comment by ArielAleksandrus** [comment]
Pois é, @Samuel-Oliveira 
Eles demoraram muito XD
Mas já está em produção sim. Parece que eles usam a do RS

https://www.nfe.fazenda.gov.br/portal/webServices.aspx?tipoConteudo=Wak0FwB7dKs=#SVRS


<img width="552" alt="Capturar" src="https://user-images.githubusercontent.com/10962902/121621317-53f2b780-ca42-11eb-90ea-a4bbd5136898.PNG">

**Comment by Samuel-Oliveira** [comment]
Esses já estão cadastrados, nfe já funciona a um tempo.
O que falta é a Url do QrCode e do Consulta NFCe.

**Comment by Samuel-Oliveira** [comment]
Achei elas aqui. Adicionado na versão 4.00.15-SNAPSHOT.

**Comment by ArielAleksandrus** [comment]
Olá, @Samuel-Oliveira 

Estou recebendo o seguinte erro:

`Erro:Status:397 - Motivo:Rejeicao: Parametro do QR-Code divergente da Nota Fiscal Param:1`

O qr code gerado ficou da seguinte forma:

`<infNFeSupl><qrCode>https://sat.sef.sc.gov.br/nfce/consulta?p=?p=42210631790513000177651170000000161197800340|2|1|1|56DE3B01E1F8086A7EF540A2B6FE62694FD258DA</qrCode><urlChave>https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao4.asmx</urlChave></infNFeSupl>`

Seria este o problema? O "?p=" duplicado em "/consulta?p=?p=42210631..."

**Comment by Samuel-Oliveira** [comment]
PArece

**Comment by ArielAleksandrus** [comment]
@Samuel-Oliveira Deu certo, meu amigo. O fix vai fazer funcionar ;)
