### ISSUE TITLE
NfeException: Connection has been shutdown: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by HudsonRomualdo** [Samuel-Oliveira/Java_NFe#219]
Olá.
Alguém mais está tendo problemas no ambiente da SEFAZ de Goiás.

O seguinte erro está ocorrendo:
NfeException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Tudo indica que trata-se de _cacert_. Um novo arquivo foi gerado e em homologação funciona normalmente. (emite NFe e NFCe)
Mas em produção, o erro acima está ocorrendo.

Alguém tem alguma dica?

**Comment by HudsonRomualdo** [comment]
O erro começou ontem as 20:00 hrs. Do nada!

Cliente trabalhou o dia todo e esse problema surgiu em uma nota que ele tentou emitir a noite.

**Comment by HudsonRomualdo** [comment]
Para gerar o Cacert, estou utilizando a classe "CacertUtil.java".

Depois configuro a JVM.
		System.setProperty("java.protocol.handler.pkgs", "com.sun.net.ssl.internal.www.protocol");    
		Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());    
		System.setProperty("javax.net.ssl.keyStoreType", "PKCS12");    
		System.setProperty("javax.net.ssl.keyStore", caminhoCertificado);
		System.setProperty("javax.net.ssl.keyStorePassword", senhaCertificadoDigital);    
		System.setProperty("javax.net.ssl.trustStoreType", "JKS");    
		System.setProperty("javax.net.ssl.trustStore", caminhoDoCacert);

**Comment by Samuel-Oliveira** [comment]
@HudsonRomualdo Use a Versão 4.00.15-SNAPSHOT que vai resolver seu problema!

**Comment by HudsonRomualdo** [comment]
Olá Samuel.
Obrigado pelo retorno.

Vixi...será uma atualização considerável. O projeto está ainda com a versão 4.00.7.

Bem, para que o sistema volte a funcionar para fazer essa migração com calma, seria viável gerar o JKS através desse novo projeto que você criou: "Java_Ceritificado"?

Funcionaria?

Abri o código aqui e nem tem mais a extensão ".jks".

**Comment by Samuel-Oliveira** [comment]
PAra que volte a funcioan vc tem que usar esse cacert: https://github.com/Samuel-Oliveira/Java_Certificado/blob/master/src/main/resources/cacert

**Comment by HudsonRomualdo** [comment]
Fiz o download e percebi que não temos mais a extensão ".jks".

O sistema espera extensão para fazer a atualização do Cacert.
Ao incluir essa extensão e o problema persistiu:  javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

O teste que fiz, gerar novamente o carcert utilizando a classe "CacertUtil.java" do projeto "Java_Certificado" também não funcionou.

**Comment by Samuel-Oliveira** [comment]
Se precisar d euma consultoria pra agilizar esse processo de atualização me chame no WhatsApp: 62 99306-6546

**Comment by HudsonRomualdo** [comment]
Olá Samuel.

O pessoal retorno que após a atualização o sistema voltou a enviar.
Solicitei que façam uma contribuição ao projeto.

Obrigado.
