### ISSUE TITLE
Problema de Validação ao passar pelo método que montar Nfe

### ISSUE THREAD

**Issue by ivanildos** [Samuel-Oliveira/Java_NFe#222]
Olá

Estou com um problema de validação.
Ao montar a nfe, onde não está reconhecendo caracteres especiais.
Segue o problema:

Erro na validação: 
- O valor 'NAVIRAÃ�' do elemento 'xMun' não é válido.

obs. O certo seria Naviraí, mas ao passar pelo método que monta a nfe ocorre esse problema.

Já viram algo parecido ou está faltando o 'charset=UTF-8' em algum lugar?

Desde já agradeço!

**Comment by Samuel-Oliveira** [comment]
Esse è um erro da nova versão 4.00.15
Use a versão 14 até eu criar a 16.
