### ISSUE TITLE
Problemas ao iniciar certificado NFe

### ISSUE THREAD

**Issue by YuriFernandes150** [Samuel-Oliveira/Java_NFe#223]
Boa tarde! Estou usando essa API para inicializar um certificado A3, mas ocorre o seguinte erro:

`br.com.swconsultoria.certificado.exception.CertificadoException: Erro ao carregar informações do certificado: Erro Ao pegar KeyStore: load failed`

Estou chamando o certificado e aplicando nas configs de NFe de acordo com o que foi mostrado [aqui](https://github.com/Samuel-Oliveira/Java_Certificado/wiki/03-:-A3-Com-1-Aparelho-na-Maquinal), e [aqui](https://github.com/Samuel-Oliveira/Java_NFe/wiki/01-:-Configuracoes)

Segue meu codigo:

> private static Certificado certificadoA3GemPC(String pass) throws CertificadoException {
String marcaA3 = TipoCertificadoA3.LEITOR_GEMPC_PERTO.getMarca();
String dllA3 = TipoCertificadoA3.LEITOR_GEMPC_PERTO.getDll();
return CertificadoService.certificadoA3(marcaA3, dllA3, pass);
 }

Eu uso esse metodo aqui:

> certificado = certificadoA3GemPC(pass);
                ConfiguracoesNfe config = ConfiguracoesNfe.criarConfiguracoes(EstadosEnum.SP, AmbienteEnum.PRODUCAO, certificado, CriaConfigs.raizSistema.getPath() + File.separator + "Fiscal" + File.separator + "NFe" + File.separator + "Schemas");
                System.out.println("Alias Certificado :" + certificado.getNome());
                System.out.println("Dias Restantes Certificado :" + certificado.getDiasRestantes());
                System.out.println("Validade Certificado :" + certificado.getVencimento());
                return config;

Estou usando ambas os JARs (sem Maven) no meu projeto no netbeansm sendo carregados na seguinte ordem:

`java_certificado-2.2.jar`
`java-nfe-4.00.15.jar`

Estou usando o Java 8 (32 bits)

Estou me esquecendo de algum passo para inicializar corretamente? Grato desde ja.

**Comment by Samuel-Oliveira** [comment]
A biblioteca de certificados ja esta embutida na NFe.
Vc importou uma versão mt antiga(2.2 atual 2.6)
Remova essa lib 2.2. q provavelmente vai resolver o problema!

**Comment by YuriFernandes150** [comment]
Opa! Testei aqui, removi a lib de certificados e testei com um A3 da certisign (SCR3310) e ainda ta com problema, o erro mudou para 
`Initialization Failed`
Dei uma pesquisada na net e vi que pode ser alguma DLL, mas a cmp11.dll esta certinho na sys32 e na syswow64, tem algo faltando?

**Comment by Samuel-Oliveira** [comment]
@YuriFernandes150 isso pode ser conflito tbm!
Algumas vezes quando duas marcas de A3 são instaladas na msm maquina pode acontecer este erro.
Sugiro que pegue uma maquina virgem, instale so o certificado que deseja e faça o Teste!
