### ISSUE TITLE
Lançar versão com a dependencia axis2 atualizada

### ISSUE THREAD

**Issue by allan-silva** [Samuel-Oliveira/Java_NFe#229]
Oi Pessoal, seria possível lançar uma versão da lib com a versão do  axis2 para no mínimo 1.7.6 ?

Com o objetivo de remediar a vulnerabilidade de segurança do `commons-fileupload:commons-fileupload 1.3.2` corrigida nesta versão 1.7.6

Refs:

https://axis.apache.org/axis2/java/core/release-notes/1.7.6.html
https://snyk.io/vuln/maven:commons-fileupload:commons-fileupload

**Comment by Samuel-Oliveira** [comment]
Atualizar a dependencia é mais complicado.
Eu fiz um exclude e essa versão não existe mais. Assim vc pode colocar a versão q deseja
