### ISSUE TITLE
Integração nativa com Android

### ISSUE THREAD

**Issue by joaoroyosilva** [Samuel-Oliveira/Java_NFe#233]
Boa tarde, há algum plano de tornar a lib compatível com android para emissão  dos documentos direto do dispositivo, inclusive contingência?

**Comment by fredwilliamtjr** [comment]
Esse é um sonho que eu também tenho, acho que poderia ser um serviço pago pra ajudar o Smuka.

**Comment by joaoroyosilva** [comment]
Eu consegui compilar utilizando o jar. Pelo gradle estava dando duplicidade nas dependências. Semana que vem eu vou tentar fazer o uso para ver se vai dar tudo certo.

**Comment by fredwilliamtjr** [comment]
Poxa que legal. precisando de ajuda me chama.

**Comment by Samuel-Oliveira** [comment]
Se este ISSUE não tiver resposta em 5 dias, será fechado por inatividade!

**Comment by lulukamagaiver** [comment]
@joaoroyosilva seria interessante ver essa duplicidade. No gradle você consegue remover ela mas tem que ver direitinho.
