### ISSUE TITLE
ConsCad -> UF: MS

### ISSUE THREAD

**Issue by sidneiklein83** [Samuel-Oliveira/Java_NFe#234]
Ao efetuar a consulta cadastro:
<?xml version="1.0" encoding="UTF-8"?><ConsCad versao="2.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infCons><xServ>CONS-CAD</xServ><UF>MS</UF><CNPJ>05607161000242</CNPJ></infCons></ConsCad>, 

recebemos o retorno:
<retConsCad xmlns="http://www.portalfiscal.inf.br/nfe" versao="2.00"><infCons><verAplic>MS_1.0.81</verAplic><cStat>404</cStat><xMotivo>Rejeicao: Uso de prefixo de namespace nao permitido</xMotivo><UF>MS</UF><CNPJ>05607161000242</CNPJ><dhCons>2022-03-09T18:29:03-04:00</dhCons><cUF>50</cUF></infCons></retConsCad>

Rejeição 404 - Rejeicao: Uso de prefixo de namespace nao permitido.
Percebi isto somente para o Estado de MS.

**Comment by Samuel-Oliveira** [comment]
Corrigido, versão 4.00.18-SNAPSHOT
