### ISSUE TITLE
URL de consulta a NFCe via QRCode foi alterada em MG

### ISSUE THREAD

**Issue by phillipig** [Samuel-Oliveira/Java_NFe#240]
Link para o aviso:
http://www.sped.fazenda.mg.gov.br/spedmg/nfce/

"• A URL de consulta a NFCe via QRCode foi alterada em PRODUÇÃO. A partir do dia 4/4/2022 a URL antiga foi desativada. Importante lembrar que a nova url deverá ser utilizada tanto no processo de consulta quanto de autorização.

A nova url a ser utilizada é: https://portalsped.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml"

**Comment by Samuel-Oliveira** [comment]
Implementado 4.00.18-SNAPSHOT
