### ISSUE TITLE
Como consultar notas de compra? [DÚVIDA]

### ISSUE THREAD

**Issue by ArielAleksandrus** [Samuel-Oliveira/Java_NFe#242]
Eu gostaria de fazer o download das notas de compra da empresa. Gostaria de saber como acesso as notas que foram emitidas no CNPJ da minha empresa.

Eu supus ser neste item da wiki: Download Nfe (DistDfe)
Inicialmente, coloquei como NSU: 000000000000001

Recebi a mensagem que não havia documentos para este NSU.
Assim, resolvi fazer com o próximo NSU: 000000000000002

Recebi então a mensagem: Status: 656 - Rejeicao: Consumo Indevido (Deve ser utilizado o ultNSU nas solicitacoes subsequentes. Tente apos 1 hora)

Este download de DistDfe é das notas da minha compra ou da minha venda? Qual o jeito correto para puxar as compras da empresa?

Alguém por gentileza poderia me ajudar?

**Comment by Samuel-Oliveira** [comment]
Blz? 
O NSU inicial deve ser : 000000000000000.

O Download é feito para notas de compras.
Segue Wiki: https://github.com/Samuel-Oliveira/Java_NFe/wiki/12-:-Download-Nfe-(DistDfe)

Tbm segue video de uma live onde implementei um sistema de download: https://www.youtube.com/watch?v=JtvNMPH2eqY

**Comment by ArielAleksandrus** [comment]
Olá, @Samuel-Oliveira ! Usar o NSU inicial com zeros deu certo, mas as notas que estou recebendo são da versão resumida. Foi informado que preciso criar uma Manifestacao para pegar o XML completo. Estou seguindo o tutorial no link https://github.com/Samuel-Oliveira/Java_NFe/wiki/11-:-Manifestacao-Nfe

mas não estou vendo como faço para pegar o xml completo na variável "resultado". No exemplo, é printada apenas a chave, o status e o protocolo. Por favor, poderia me informar como faço para baixar o XML completo das notas de entrada?

**Comment by fredwilliamtjr** [comment]
Olá @ArielAleksandrus você não vai receber o XML completo quando efetuar a manifestação. você ira receber nas próximas consultas feitas no distribuicaoDfe.

1 - Você recebe o resumo no distribuicaoDfe.
2 - Você manifesta no mínimo ciência.
3 - Na próxima consulta ao distribuicaoDfe você receberá os XMLs completos das notas que você manifestou.

**Comment by ArielAleksandrus** [comment]
Boa noite. A solução dada por ti, @fredwilliamtjr , funcionou muito bem no começo, mas agora estou recebendo o erro: Rejeicao: Consumo Indevido (Deve ser utilizado o ultNSU nas solicitacoes subsequentes. Tente apos 1 hora)

Então, setarei o NSU como UltNSU, no meu caso: 000000000003515
Porém, não tem funcionado. Creio que é por causa do MaxNSU, que está como 000000000000000.
Devo setar o MaxNSU também, certo? Eu estava pensando em ser no valor de 100 a mais do que o UltNSU. No caso, seria:
000000000003615

É dessa forma que devo proceder, @fredwilliamtjr @Samuel-Oliveira ? Como vocês me recomendam?
