### ISSUE TITLE
Como consultar de Nota de Compra (parte 2) [DÚVIDA]

### ISSUE THREAD

**Issue by ArielAleksandrus** [Samuel-Oliveira/Java_NFe#247]
Boa noite. A solução dada no [issue 242](https://github.com/Samuel-Oliveira/Java_NFe/issues/242) , funcionou muito bem no começo, mas agora estou recebendo o erro: Rejeicao: Consumo Indevido (Deve ser utilizado o ultNSU nas solicitacoes subsequentes. Tente apos 1 hora)

Então, setarei o NSU como UltNSU, no meu caso: 000000000003515
Porém, não tem funcionado. Creio que é por causa do MaxNSU, que está como 000000000000000.
Devo setar o MaxNSU também, certo? Eu estava pensando em ser no valor de 50 a mais do que o UltNSU. No caso, seria:
000000000003565

Então, seria da seguinte forma: 

    String nsu = "000000000003515";
    RetDistDFeInt retorno = Nfe.distribuicaoDfe(config, PessoaEnum.JURIDICA, cnpj, ConsultaDFeEnum.NSU, nsu);
    int nsuInt = Integer.parseInt(nsu);
    if(nsuInt > 0) {
        int maxNsuInt = nsuInt + 50;
        String maxNsu = String.valueOf(maxNsuInt);
        for(int i = 0; i < nsu.length() - maxNsu.length(); i++) {
            maxNsu = "0" + maxNsu;
        }
        retorno.setMaxNSU(maxNsu);
    }

É dessa forma que devo proceder? Como vocês me recomendam?

**Comment by ArielAleksandrus** [comment]
Obrigado por me alertar. Mexer com software do governo é uma bosta mesmo.

**Comment by Samuel-Oliveira** [comment]
Podemos fechar o Issue?

**Comment by ArielAleksandrus** [comment]
@Samuel-Oliveira se realmente não tem saída parq a consulta de nota de compras, pode fechar o issue sim
