### ISSUE TITLE
[RESOLVIDO] Conflito com org.bouncycastle (culpado: JSSC)

### ISSUE THREAD

**Issue by YuriFernandes150** [Samuel-Oliveira/Java_NFe#249]
Ola Samuel, poderia me dar uma ajudinha? Eu adicionei sua lib no meu projeto Maven, mas ocorre o seguinte erro:
`Caused by: java.lang.SecurityException: class "org.bouncycastle.asn1.ASN1Object"'s signer information does not match signer information of other classes in the same package`

Isso ocorre quando tento buscar os certificados do Windows:

`import br.com.swconsultoria.certificado.Certificado;
import br.com.swconsultoria.certificado.CertificadoService; 
java.util.List<Certificado> listaCertificadosWindows = CertificadoService.listaCertificadosWindows();`

Estou usando o JDK 18.

Dei uma olhada nos issues aqui e não encontrei nada parecido.
Grato desde ja.

**Comment by Samuel-Oliveira** [comment]
Tudo Bom?

A Libs de Certificados usa uma versão mais nova da bcprov da bouncycastle (jdk16), sendo assim, toda vez que uma Lib adicionada antes tiver uma versão anterior a Lib de certificado ocorre erro. Para resolver isso vc deve dar um exclude na biblioteca que ocorre isso. Os casos mais conhecidos são:
- JasperReports
- IText

Para fazer o exclude, adiciona dentro da dependency:

<exclusions>
                <exclusion>
                    <artifactId>bcprov-jdk15on</artifactId>
                    <groupId>org.bouncycastle</groupId>
                </exclusion>
            </exclusions>

Qlq dúvida entra lá no Discord q te explico:
https://discord.gg/ZXpqnaV

**Comment by YuriFernandes150** [comment]
Obrigado pela resposta! Vou testar assim que possivel.
