### ISSUE TITLE
Mensagem ao utilizar NfeDistribuicaoDfe

### ISSUE THREAD

**Issue by jonasrotilli** [Samuel-Oliveira/Java_NFe#251]
Alguém já recebeu a mensagem, poderia dar uma luz/direção do que se trata?

Login failed for user 'ws_NfeDistribuicaoDfe'. Reason: The account is disabled.

Acontece depois da consulta de distribuição (Nfe.distribuicaoDfe(config, PessoaEnum.FISICA, cnpj, ConsultaDFeEnum.CHAVE, chave);)

**Comment by jonasrotilli** [comment]
Site da sefaz está fora do ar.. deve ser isso. 
Vou aguardar um pouco e confirmar aqui que era isso.

**Comment by Samuel-Oliveira** [comment]
Sefaz ficou Offline hoje!
