### ISSUE TITLE
Monitorar nota emitida para meu CNPJ

### ISSUE THREAD

**Issue by hermesalvesbr** [Samuel-Oliveira/Java_NFe#252]
Boa tarde pessoal,

Poderiam me indicar alguma lib/sdk que permita via meu certificado digital que eu monitore as notas fiscais emitidas para o meu CNPJ?

Gostaria de saber quando alguém emitir uma nota fiscal de venda para o meu cnpj. 

Pode ser em outra linguagem, não tem problemas. 

Agradeço desde já qualquer contribuição,

**Comment by robertodpassos** [comment]
Boa tarde!
Aqui
https://www.youtube.com/watch?v=JtvNMPH2eqY&t=79s
