### ISSUE TITLE
Pergunta: Baixar NFes emitidas contra CNPJ

### ISSUE THREAD

**Issue by cfontes** [Samuel-Oliveira/Java_NFe#253]
Bom dia, obrigado pelo projeto.

Antes de tentar uma integração gostaria de pedir uma ajuda já que seu conhecimento no assunto é grande deve ser uma resposta fácil para você.

Com seu projeto é possível baixar as notas emitidas contra meu CNPJ em paralelo com outros sistemas? Pelo que li na API existe um numero que registra onde você parou de baixar e me parece que existem problemas quando 2 consumidores tentam ao mesmo tempo baixar as NFs de um mesmo CNPJ.

Estou enganado? 

Poderia me direcionar para a melhor forma de integrar sua Lib com um backend java para esse tipo de funcionalidade, basicamente baixar todas as notas incrementalmente emitidas contra um CNPJ sem repetições se possível pela API.

Obrigado

**Comment by robertodpassos** [comment]
Bom dia!

Aqui você tem um exemplo de como utilizar a API
https://www.youtube.com/watch?v=JtvNMPH2eqY&t=79s

Aqui para dúvidas
https://discord.gg/ZXpqnaV

Mas já adianto, dois sistemas diferentes baixa notas é o maior problema que tu vai arrumar.
Não tem como devido aos controles de uso indevido da receita.

Abraço!

**Comment by cfontes** [comment]
ou seja tem que ser uma chave por applicação?

**Comment by robertodpassos** [comment]
Bom dia!
É pior, não tem como.
A baixa de notas é pelo NSU que é gerado pela receita.
É tipo um sequencial para cada movimentação que for realizada. 
Então vamos dizer que alguém emite uma nota para o CNPJ, a receita vai gerar o NSU 10.
Ai um sistema vai la e baixa este movimento do NSU 10 e o outro fica chupando o dedo, kkkk

**Comment by cfontes** [comment]
Que bom que nossos impostos estão sendo usado em uma API tão eficiente... Otimo.

**Comment by robertodpassos** [comment]
KKKK
mas da uma olhada no video lá que explica melhor.
Tem baixa por NSU, por Chave também
E qualquer coisa entra la no Discord que fica mais fácil de tirar as dúvidas

**Comment by jonasrotilli** [comment]
> Que bom que nossos impostos estão sendo usados em uma API tão eficiente... Otimo.

Para piorar um pouco: 
a receita no ultimo mês está limitando a consulta pro chave para no máximo 20 por hora para o CNPJ/CPF, mesmo sem NSU consultando chave a chave...

**Comment by Samuel-Oliveira** [comment]
Finalizada Por Inatividade
