### ISSUE TITLE
download xml nfce

### ISSUE THREAD

**Issue by PedroCavalcanti0001** [Samuel-Oliveira/Java_NFe#257]
também é possivel fazer o download do xml de NFCE?

**Comment by Samuel-Oliveira** [comment]
Não! A sefaz não disponibiliza nada para NFCe.

**Comment by PedroCavalcanti0001** [comment]
Através desse portal é possivel fazer download do xml de NFCE https://dfe-portal.svrs.rs.gov.br/NfceSSL/DownloadXmlDfe

**Comment by Samuel-Oliveira** [comment]
Sim , o Downlaod Manual.
Se tem um Captcha quer dizer que uma maquina/sistema não é autorizado a usar tal serviço!
