### ISSUE TITLE
Problema na consulta via chave

### ISSUE THREAD

**Issue by jhonattan471** [Samuel-Oliveira/Java_NFe#26]
Motivo : Rejeicao: Cabecalho - Versao do arquivo XML nao suportada

**Comment by jhonattan471** [comment]
DistDFeInt distDFeInt = new DistDFeInt();
			distDFeInt.setVersao("3.10");
			distDFeInt.setTpAmb(config.getAmbiente());
			distDFeInt.setCUFAutor(config.getEstado().getCodigoIbge());
			//Substitua os X pelo CNPJ
			distDFeInt.setCNPJ("...");
			
			DistNSU distNSU = new DistNSU();
			ConsChNFe chNFe = new ConsChNFe();

			chNFe.setChNFe("...");
			distDFeInt.setConsChNFe(chNFe);
			
			//Informe false para não fazer a validação do XML - Ganho De tempo.
			RetDistDFeInt retorno = Nfe.distribuicaoDfe(distDFeInt,false);
			System.out.println("Status:" + retorno.getCStat());
			System.out.println("Motivo:" + retorno.getXMotivo());

			List<DocZip> listaDoc =  retorno.getLoteDistDFeInt().getDocZip();
			
			for (DocZip docZip : listaDoc) {
				System.out.println("Schema: "+docZip.getSchema());
				System.out.println("NSU:" + docZip.getNSU());
				System.out.println("XML: "+XmlUtil.gZipToXml(docZip.getValue()));
			}

**Comment by Samuel-Oliveira** [comment]
Abriu e Fechou?
Já descobriu o que vc errou?

A versão do Distribuicao Dfe é 1.01;

**Comment by jhonattan471** [comment]
Eae, pode me dar uma ajuda?
Estou tentando consultar o xml d euma nfc... esse era o problema, modelo não é 55...

Quero fazer a consulta no PR

.

**Comment by Samuel-Oliveira** [comment]
Add no Skype : samuk.exe@hotmail.com
