### ISSUE TITLE
Problemas no android

### ISSUE THREAD

**Issue by SuportecTL** [Samuel-Oliveira/Java_NFe#261]
Bom dia, eu consegui resolver os conflitos de dependência para uso no android via gradle, porém está dando problemas devido ao android não ter provider "JKS". No caso o erro dá na lib do certificado, na classe  SocketFactoryDinamico, na linha 74 ( KeyStore trustStore = KeyStore.getInstance("JKS");).  Dei uma pesquisada na internet e em outro caso resolveram mudando para 

 KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());

Eu baixei os fontes das libs de certificado e nfe, porém não consigo gerar o .jar completo novamente. Alguém sabe alguma maneira de contornar isso? Agradeço desde já

**Comment by SuportecTL** [comment]
O link para issue que resolve esse problema no outro caso que eu falei. O erro atual é o mesmo JSK not found

https://github.com/Adyen/adyen-java-api-library/issues/383

**Comment by Samuel-Oliveira** [comment]
Opa, tudo bem? 
Queria entender algumas coisas, entrar lá no Discord e me chame em um tópico por favor.
https://discord.gg/ZXpqnaV
