### ISSUE TITLE
Endereço de homologação DF

### ISSUE THREAD

**Issue by egioncpdsi** [Samuel-Oliveira/Java_NFe#262]
Olá, estou com um problema um tanto estranho, qualquer nfce que emito em ambiente de homologacao me retorna a rejeição 395, "Endereco do site da UF da consulta via QR-Code diverge do previsto ", eu chequei os endereços, validei no site da sefaz, porém não consegui enxergar o erro, no caso estou usando o pacote original, sem nenhuma modificação no WebServices.ini

![image](https://user-images.githubusercontent.com/19985109/223419834-487fc02f-5eda-4535-987c-9e3d0b4a893b.png)

se alguém souber como devo prosseguir para conseguir solucionar agradeço

**Comment by rodrigocananea** [comment]
Pelo que vi no site Sefaz DF eles parecem estar com problemas nessa url de QrCode e pedem para informar a antiga por enquanto:
http://dec.fazenda.df.gov.br/ConsultarNFCe.aspx?

Consegue testar isso ai?

**Comment by egioncpdsi** [comment]
> Pelo que vi no site Sefaz DF eles parecem estar com problemas nessa url de QrCode e pedem para informar a antiga por enquanto: `http://dec.fazenda.df.gov.br/ConsultarNFCe.aspx?`
> 
> Consegue testar isso ai?

deu certinho muito obrigado meu querido
