### ISSUE TITLE
Ola.. estou com erro na leitura do certificadao no Config

### ISSUE THREAD

**Issue by ricasht** [Samuel-Oliveira/Java_NFe#269]
Erro o Config do Certificado
class org.bouncycastle.asn1.DERPrintableString cannot be cast to class org.bouncycastle.asn1.ASN1TaggedObject (org.bouncycastle.asn1.DERPrintableString and org.bouncycastle.asn1.ASN1TaggedObject are in unnamed module of loader

Estou usando servidor WildFly 29 e Jakarta

**Comment by Samuel-Oliveira** [comment]
Blz? Qual versao do Java? 
As bibliotecas de compatibilidade até a versão do Java 17.

**Comment by ricasht** [comment]
Tudo certo.. estou com a 11

**Comment by ricasht** [comment]
16:22:33,210 ERROR [stderr] (default task-3) java.lang.ClassCastException: class org.bouncycastle.asn1.DERPrintableString cannot be cast to class org.bouncycastle.asn1.ASN1TaggedObject (org.bouncycastle.asn1.DERPrintableString and org.bouncycastle.asn1.ASN1TaggedObject are in unnamed module of loader 'deployment.BergaSoft.war' @6f4833be)
16:22:33,210 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.swconsultoria.certificado.CertificadoService.lambda$getDocumentoFromCertificado$9(CertificadoService.java:407)
16:22:33,210 ERROR [stderr] (default task-3) 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
16:22:33,210 ERROR [stderr] (default task-3) 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
16:22:33,211 ERROR [stderr] (default task-3) 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
16:22:33,211 ERROR [stderr] (default task-3) 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
16:22:33,211 ERROR [stderr] (default task-3) 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
16:22:33,211 ERROR [stderr] (default task-3) 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
16:22:33,211 ERROR [stderr] (default task-3) 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
16:22:33,211 ERROR [stderr] (default task-3) 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
16:22:33,211 ERROR [stderr] (default task-3) 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
16:22:33,211 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.swconsultoria.certificado.CertificadoService.lambda$getDocumentoFromCertificado$10(CertificadoService.java:399)
16:22:33,212 ERROR [stderr] (default task-3) 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
16:22:33,212 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.swconsultoria.certificado.CertificadoService.getDocumentoFromCertificado(CertificadoService.java:398)
16:22:33,212 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.swconsultoria.certificado.CertificadoService.setDadosCertificado(CertificadoService.java:107)
16:22:33,212 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.swconsultoria.certificado.CertificadoService.certificadoPfx(CertificadoService.java:132)
16:22:33,212 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.berga.soft.nfe.NFeConfig.certifidoA1Pfx(NFeConfig.java:95)
16:22:33,212 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.berga.soft.nfe.NFeConfig.iniciaConfiguracoes(NFeConfig.java:37)
16:22:33,212 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.berga.soft.nfe.NfceEnvia.envia(NfceEnvia.java:222)
16:22:33,212 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.berga.soft.vendas.VendasFaz.NfeEnvia(VendasFaz.java:369)
16:22:33,212 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.berga.soft.vendas.VendasFaz.vendaFinaliza(VendasFaz.java:432)
16:22:33,213 ERROR [stderr] (default task-3) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
16:22:33,213 ERROR [stderr] (default task-3) 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
16:22:33,213 ERROR [stderr] (default task-3) 	at org.glassfish.expressly@5.0.0//org.glassfish.expressly.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:186)
16:22:33,213 ERROR [stderr] (default task-3) 	at org.glassfish.expressly@5.0.0//org.glassfish.expressly.parser.AstValue.invoke(AstValue.java:253)
16:22:33,213 ERROR [stderr] (default task-3) 	at org.glassfish.expressly@5.0.0//org.glassfish.expressly.MethodExpressionImpl.invoke(MethodExpressionImpl.java:248)
16:22:33,213 ERROR [stderr] (default task-3) 	at org.jboss.weld.core@5.1.1.SP1//org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
16:22:33,213 ERROR [stderr] (default task-3) 	at org.jboss.weld.core@5.1.1.SP1//org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
16:22:33,213 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//jakarta.faces.event.MethodExpressionActionListener.processAction(MethodExpressionActionListener.java:109)
16:22:33,213 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//jakarta.faces.event.ActionEvent.processListener(ActionEvent.java:72)
16:22:33,214 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//jakarta.faces.component.UIComponentBase.broadcast(UIComponentBase.java:480)
16:22:33,214 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//jakarta.faces.component.UICommand.broadcast(UICommand.java:197)
16:22:33,214 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//jakarta.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:858)
16:22:33,214 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//jakarta.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1332)
16:22:33,214 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:56)
16:22:33,214 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
16:22:33,214 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
16:22:33,214 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
16:22:33,215 ERROR [stderr] (default task-3) 	at jakarta.faces.impl@4.0.2//jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
16:22:33,215 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
16:22:33,215 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
16:22:33,215 ERROR [stderr] (default task-3) 	at deployment.BergaSoft.war//br.com.berga.soft.filtro.FiltroAdmin.doFilter(FiltroAdmin.java:47)
16:22:33,215 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
16:22:33,215 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
16:22:33,215 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
16:22:33,215 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
16:22:33,215 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
16:22:33,215 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
16:22:33,216 ERROR [stderr] (default task-3) 	at org.wildfly.security.elytron-web.undertow-server@4.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
16:22:33,216 ERROR [stderr] (default task-3) 	at org.wildfly.security.elytron-base@2.2.1.Final//org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
16:22:33,216 ERROR [stderr] (default task-3) 	at org.wildfly.security.elytron-base@2.2.1.Final//org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
16:22:33,216 ERROR [stderr] (default task-3) 	at org.wildfly.security.elytron-base@2.2.1.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
16:22:33,216 ERROR [stderr] (default task-3) 	at org.wildfly.security.elytron-web.undertow-server@4.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
16:22:33,216 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
16:22:33,216 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
16:22:33,216 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
16:22:33,216 ERROR [stderr] (default task-3) 	at io.undertow.core@2.3.7.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:22:33,217 ERROR [stderr] (default task-3) 	at io.undertow.core@2.3.7.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
16:22:33,217 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
16:22:33,217 ERROR [stderr] (default task-3) 	at io.undertow.core@2.3.7.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
16:22:33,217 ERROR [stderr] (default task-3) 	at org.wildfly.security.elytron-web.undertow-server-servlet@4.0.0.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
16:22:33,217 ERROR [stderr] (default task-3) 	at io.undertow.core@2.3.7.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:22:33,217 ERROR [stderr] (default task-3) 	at org.wildfly.extension.undertow@29.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
16:22:33,217 ERROR [stderr] (default task-3) 	at io.undertow.core@2.3.7.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:22:33,217 ERROR [stderr] (default task-3) 	at org.wildfly.extension.undertow@29.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
16:22:33,217 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
16:22:33,217 ERROR [stderr] (default task-3) 	at io.undertow.core@2.3.7.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:22:33,218 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:276)
16:22:33,218 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
16:22:33,218 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:132)
16:22:33,218 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
16:22:33,218 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
16:22:33,218 ERROR [stderr] (default task-3) 	at org.wildfly.extension.undertow@29.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
16:22:33,218 ERROR [stderr] (default task-3) 	at org.wildfly.extension.undertow@29.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
16:22:33,218 ERROR [stderr] (default task-3) 	at org.wildfly.extension.undertow@29.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
16:22:33,218 ERROR [stderr] (default task-3) 	at org.wildfly.extension.undertow@29.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
16:22:33,219 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:256)
16:22:33,219 ERROR [stderr] (default task-3) 	at io.undertow.servlet@2.3.7.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:101)
16:22:33,219 ERROR [stderr] (default task-3) 	at io.undertow.core@2.3.7.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
16:22:33,219 ERROR [stderr] (default task-3) 	at io.undertow.core@2.3.7.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
16:22:33,219 ERROR [stderr] (default task-3) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
16:22:33,219 ERROR [stderr] (default task-3) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
16:22:33,219 ERROR [stderr] (default task-3) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
16:22:33,219 ERROR [stderr] (default task-3) 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
16:22:33,219 ERROR [stderr] (default task-3) 	at org.jboss.xnio@3.8.9.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
16:22:33,219 ERROR [stderr] (default task-3) 	at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by th1m0r** [comment]
o certiciado que voce esta usando é o A1? esta no formato pfx?

**Comment by th1m0r** [comment]
Aparentemente o certificado não esta conseguindo ser lido. voce esta colocando ele dentro do jar/war? se for esse o caso, deixa ele numa pasta fora do jar/war e tenta ler. ou instala ele na maquina e pega pelo repositório do windows.

**Comment by ricasht** [comment]
Bom dia.. Ele esta sendo lido pq faço uma validação na inserção do certificado..
Essa aplicação sera web, então não tem como utilizar o repositorio.

**Comment by th1m0r** [comment]
mas se voce ta colocando o certificado dentro do war/jar, ele nao vai ler direito. pq a pasta schemas se tiver la dentro tambem da problema. eu deixo isso fora do war/jar. e funciona certinho.

`private Certificado certificadoA1() throws FileNotFoundException, CertificadoException {
    return CertificadoService.certificadoPfx(caminhoPadrao + "\\Certificado\\" + certificadoNome, certificadoSenha);
}`

**Comment by ricasht** [comment]
public class NFeConfig {
      public static ConfiguracoesNfe iniciaConfiguracoes() throws NfeException, CertificadoException, FileNotFoundException, URISyntaxException {
	
        String tipoCert = "0";
        Certificado certificado =  certifidoA1Pfx();
          
        AmbienteEnum ambiente = AmbienteEnum.HOMOLOGACAO;
        
	
         long idEmpresa = Long.parseLong( (String) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("empresa_id"));
 		
 		try {
 			Session session = HibernateUtil.getSessionFactory().openSession();  
 		  	Transaction t = session.beginTransaction();
 		  	
 		  	Empresas em = (Empresas)session.load(Empresas.class, Long.valueOf(idEmpresa));	
 			if (em.isProducao()) {
 				ambiente = AmbienteEnum.PRODUCAO;
			}else {
				ambiente = AmbienteEnum.HOMOLOGACAO;
			}
 			
 			t.commit();
 			session.close();	
 			
 			
 		} catch (Exception e) {
 			e.printStackTrace();
 			
 	
 		}        
 		ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
		String SCHEMAS_PATH  = servletContext.getRealPath("")+"/arquivos/" + "Schemas";
	return ConfiguracoesNfe.criarConfiguracoes(EstadosEnum.RS , ambiente,
			certificado, SCHEMAS_PATH);
    }
      
   private static Certificado certifidoA1Pfx() throws CertificadoException, FileNotFoundException {
	   long idEmpresa = Long.parseLong( (String) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("empresa_id"));
	   ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();  
	   String caminhoArquivo = servletContext.getRealPath("")+"/arquivos/" + "certificado/"+idEmpresa+"/";
	   
	   String nomeCertificado = "";
	   String senhaDoCertificadoDoCliente = ""; 
	   
	   try {
			Session session = HibernateUtil.getSessionFactory().openSession();  
	      	Transaction t = session.beginTransaction();
	      	
	    	Empresas emp = (Empresas)session.load(Empresas.class, Long.valueOf(idEmpresa));
	    	nomeCertificado = emp.getCertificado();
	    	senhaDoCertificadoDoCliente = emp.getCertificadoSenha();
	      	session.update(emp);
	      	
	      	t.commit();  
			session.close();
		} catch (Exception e) {
		}
	   
	   
	   caminhoArquivo = caminhoArquivo+nomeCertificado;
	   System.out.println("EEEEEEEEEEEEEEEEEEEEEEEEEEEEE "+caminhoArquivo);

       return CertificadoService.certificadoPfx(caminhoArquivo, senhaDoCertificadoDoCliente);
}
}

**Comment by ricasht** [comment]
Esse é o codigo para verificação do certificado no Upload e para consulta de validação


public void carregaValores() {
		long idEmpresa = Long.parseLong((String) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("empresa_id"));
		SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
	    SimpleDateFormat dateCompara = new SimpleDateFormat("yyyyMMdd"); 

    	ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
		String caminhoArquivo = servletContext.getRealPath("")+"/arquivos/" + "certificado/"+idEmpresa+"/";
		
		String certificadoNome = "";
    	String certificadoSenha = "";
    	
    	certificadoInfoCor = "green";
    	
    	senhaExibeEdicao = false;
    	
		try {
			Session session = HibernateUtil.getSessionFactory().openSession();  
	      	Transaction t = session.beginTransaction();
	      	
	    	Empresas emp = (Empresas)session.load(Empresas.class, Long.valueOf(idEmpresa));
	    	certificadoNome = emp.getCertificado();
	    	certificadoSenha = emp.getCertificadoSenha();
	    	qrIdToken = String.valueOf(emp.getQrIdToken());
	    	csc = emp.getQrCsc();
	    	crt = emp.getCrt();
	    	
	    	certificadoInfo = certificadoNome;
	    	
	      	session.update(emp);
	      	t.commit();  
			session.close();
		} catch (Exception e) {
		}
		try {
			
	    	KeyStore keystore = KeyStore.getInstance(("PKCS12"));    
            keystore.load(new FileInputStream(caminhoArquivo + certificadoNome), certificadoSenha.toCharArray());    
            
            Enumeration<String> eAliases = keystore.aliases();    
                
            while (eAliases.hasMoreElements()) {    
                String alias = (String) eAliases.nextElement();    
                Certificate certificado = (Certificate) keystore.getCertificate(alias);    
                
                //certificadoInfo= alias+"<br />";//alias
                //info("Aliais: " + alias); 
                X509Certificate cert = (X509Certificate) certificado;    
                
                String[] nomeDesmembrado = cert.getSubjectDN().getName().split("\\,");
               
                certificadoInfo = nomeDesmembrado[0].replace("CN=", "")+"<br />";
                //info(cert.getSubjectDN().getName());
                
                certificadoInfo= certificadoInfo + "Data Inicial: " + dateFormat.format(cert.getNotBefore())+"<br />";
                //info("Válido a partir de..: " + dateFormat.format(cert.getNotBefore()));  
                
                certificadoInfo= certificadoInfo + "Vencimento: " +  dateFormat.format(cert.getNotAfter())+"<br />";
                //info("Válido até..........: " + dateFormat.format(cert.getNotAfter()));
                
                int dataVencimento = Integer.parseInt(dateCompara.format(cert.getNotAfter()));
                int dataHoje = Integer.parseInt(dateCompara.format(new Date()));
                               
                if (dataVencimento < dataHoje) {
                	certificadoInfo="Certifiado vencido em: " + dateFormat.format(cert.getNotAfter());
                	certificadoInfoCor = "red";
                }else {
                	int diferencaDatas = new CalculaDiferencaDias().calcula( cert.getNotAfter(), new Date());
                    certificadoInfo = certificadoInfo + "Restam ainda " + String.valueOf(diferencaDatas) + " dias";
                }
                
                
            }
		} catch (Exception e) {
			e.printStackTrace();

			certificadoInfoCor = "red";
			
			if (e.toString().contains("keystore password was incorrect")) {
				senhaExibeEdicao = true;
				certificadoInfo="Certificado Presente, mas com senha incorreta";
            }
            if (e.toString().contains("No such file or directory")  || e.toString().contains("Arquivo ou diretório inexistente")) {
                certificadoInfo="Certificado não encontrado";
            }
		}
		
		
		
	}

**Comment by ricasht** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>br.com.berga.soft</groupId>
  <artifactId>BergaSoft</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>war</packaging>
  
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.source>11</maven.compiler.source>
  </properties>
	
	<dependencies>
		  <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>10.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.faces</groupId>
            <artifactId>jakarta.faces-api</artifactId>
            <version>3.0.0</version>
            <scope>provided</scope>
        </dependency>
      
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <version>12.0.0</version>
            <classifier>jakarta</classifier>
        </dependency>
   		<dependency>
		    <groupId>org.mariadb.jdbc</groupId>
		    <artifactId>mariadb-java-client</artifactId>
		    <version>3.2.0</version>
		</dependency>
		   
		<dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
            <version>2.0.1.Final</version>
        </dependency>   
		   
		
   		<dependency>
		    <groupId>org.hibernate</groupId>
		    <artifactId>hibernate-entitymanager</artifactId>
		    <version>5.6.15.Final</version>
		</dependency>

		
		<dependency>
		    <groupId>com.zaxxer</groupId>
		    <artifactId>HikariCP</artifactId>
		    <version>5.0.1</version>
		</dependency>
		
		<dependency>
		    <groupId>org.hibernate</groupId>
		    <artifactId>hibernate-hikaricp</artifactId>
		    <version>5.6.15.Final</version>
		</dependency>
		
		
		<dependency>
		    <groupId>br.com.swconsultoria</groupId>
		    <artifactId>java-nfe</artifactId>
		    <version>4.00.26</version>
		</dependency>
		
		
		
		<dependency>
		    <groupId>com.google.zxing</groupId>
		    <artifactId>core</artifactId>
		    <version>3.5.2</version>
		</dependency>
		<dependency>
		    <groupId>com.google.zxing</groupId>
		    <artifactId>javase</artifactId>
		    <version>3.5.2</version>
		</dependency>
		
		
		<dependency>
		    <groupId>com.itextpdf</groupId>
		    <artifactId>itextpdf</artifactId>
		    <version>5.5.13.3</version>
		</dependency>
	 </dependencies> 
	
 <build>
	<finalName>BergaSoft</finalName>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-war-plugin</artifactId>
            <version>3.3.2</version>
        </plugin>
    </plugins>
</build>
</project>

**Comment by ricasht** [comment]
Precisa de mais alguma coisa?

**Comment by ricasht** [comment]
Conseguiram achar onde esta o erro?

**Comment by Samuel-Oliveira** [comment]
Boa tarde. Problema fdoi resolvido? 
Caso não resposta o topico será fechado por inatividade!

**Comment by ricasht** [comment]
Ola.. verificarei e lhe retorno

**Comment by andrespy00** [comment]
Também estou com o mesmo erro. 
Estranho pois no projeto Java_Cte inicializo o certificado da mesma forma mas não ocorre erro. 
Já no Java_NFe aparece
class org.bouncycastle.asn1.DERPrintableString cannot be cast to class org.bouncycastle.asn1.ASN1TaggedObject (org.bouncycastle.asn1.DERPrintableString and org.bouncycastle.asn1.ASN1TaggedObject are in unnamed module of loader

**Comment by Samuel-Oliveira** [comment]
Fechado por inatividade
