### ISSUE TITLE
NFe Sefaz MT  erro em Homologação Connection or outbound has closed

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#270]
Olá samu, creio que estamos com problema no Cacert para MT em homologação, estamos a uns 5 dias que não conseguimos comunicação com o servidor de homologação. 
Erro--->> br.com.swconsultoria.nfe.exception.NfeException: Connection or outbound has closed

**Comment by Samuel-Oliveira** [comment]
Fala @resplandes Atualizei e liberei na versao 4.00.27
