### ISSUE TITLE
Implementar 2023.004 e 2019.001 - Mudanca Layout (25/04/2024)

### ISSUE THREAD

**Issue by Samuel-Oliveira** [Samuel-Oliveira/Java_NFe#271]
Para lembrar

**Comment by resplandes** [comment]
@Samuel-Oliveira  te lembrando

**Comment by Samuel-Oliveira** [comment]
O Evento ECONF foi removido dessa NT. Será trtado posteriormente.
Agora temos apenas modificacao de layout. Nova data Homologacao 11/03/24.

**Comment by Samuel-Oliveira** [comment]
O Layout da 2019.001 tbm será alterado em 11/03/24. Tratar essas duas NT juntas.

**Comment by Samuel-Oliveira** [comment]
Ambas as NT foram prorrogadas para:
- Homologacao : 25/03/2024
- Producao:  06/05/2024

E vamos empurrando ocm a barriga!
Vou implementar no dia 15/04. 
Vai que eles alterem o layout novamente.

**Comment by Samuel-Oliveira** [comment]
Ja esta disponivel na versao 4.00.34.
