### ISSUE TITLE
Erro de formatação de XML ao enviar NFe e NFCe no MT tanto em produçaõ como 

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#273]
Ao tentar enviar uma NFCe ou NFe recebemos o erro de formatação invalida!

![image](https://github.com/Samuel-Oliveira/Java_NFe/assets/3025776/489d753b-2839-48b5-b67a-9d3ca808edf0)

**Comment by Samuel-Oliveira** [comment]
Isso era erro vindo da sua aamada Sefaz MT kkkkkkk
