### ISSUE TITLE
Timeout estourando no retorno de autorização de NFe sefaz MT

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#274]
Olá Samuel, o evento de autorização de nfe no MT esta estourando timeout em produção.
veja imagem abaixo.
![WhatsApp Image 2024-01-23 at 17 51 43](https://github.com/Samuel-Oliveira/Java_NFe/assets/3025776/1278fa41-5023-402d-9b0a-5d1e5e6ee4b1)

**Comment by resplandes** [comment]
Temos algum novidade ? Visto que a Sefaz-MT informa está com todos seus serviços em pleno funcionamento.

**Comment by resplandes** [comment]
![Screenshot_4](https://github.com/Samuel-Oliveira/Java_NFe/assets/3025776/3113a89d-d0d8-43a8-8c74-149ff757d544)
Mas acredito que seja o timeout de retorno estourando mesmo.

**Comment by resplandes** [comment]
É Inacreditável esse processo de monitoramento da sefaz MT :| o pessoal está com problemas e não sabem ?
![Screenshot_5](https://github.com/Samuel-Oliveira/Java_NFe/assets/3025776/9b527d0b-f643-47c4-8553-3afb1942dc35)

**Comment by robertodpassos** [comment]
Mas se tu alterar o timeout não tem que resolver isso ai?

**Comment by Samuel-Oliveira** [comment]
@resplandes tem duas variaveis na LIB. 
Timeout e Retry. 
Recomendo colocar o timeout de 1 min. e um retry de 5.

**Comment by resplandes** [comment]
o timeout está com milisegundos ? pois inclui 500 e fica super rápido!

**Comment by resplandes** [comment]
Aumentei o timeout para 5 minutos,  ai sim passou.

**Comment by resplandes** [comment]
Tive que aumentar o timeout para 5 minutos.
