### ISSUE TITLE
Implementar a PL_009m_NT2023_004_v101_e_NT2019_001_v160 - Estado MT 01-04-2024

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#276]
Implementar a **PL_009m_NT2023_004_v101_e_NT2019_001_v160** visto que tem mudanças no layout de emissão de nfe e nfce, envolvendo por exemplo o destaque do CNPJ do estabelecimento que recebeu o pagamento e o a uf que ocorreu o pagamento no grupo de DetPag.

[Link da PL para dowload ](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=rRDFjf1Ps7M=)

[PL_009m_NT2023_004_v101_e_NT2019_001_v160.zip](https://github.com/Samuel-Oliveira/Java_NFe/files/14394055/PL_009m_NT2023_004_v101_e_NT2019_001_v160.zip)
![Screenshot_1](https://github.com/Samuel-Oliveira/Java_NFe/assets/3025776/f3abc2c5-2fe1-4d94-a08d-3adf3303de2a)

**Comment by Samuel-Oliveira** [comment]
Duplicado @resplandes 
https://github.com/Samuel-Oliveira/Java_NFe/issues/271
