### ISSUE TITLE
Estado do MT com problemas na cadeia de certificados, deve-se atualizar!

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#277]
Caused by: java.net.ConnectException: Connection refused: connect

Resposta da Sefaz-MT;

**Boa tarde,

Foi atualizada as cadeias dos certificados?

 Autoridade certificadora: AC SOLUTI SSL EV G4 (https://www.gov.br/iti/pt-br/assuntos/repositorio/ac-soluti)
   Autoridade certificadora Raiz: Autoridade Certificadora Raiz Brasileira v10 (https://www.gov.br/iti/pt-br/assuntos/repositorio/repositorio-ac-raiz)

Obs. Esses dois certificados já permitem a comunicação com a SEFAZ-MT, porém recomendamos que seja mantido TODOS os certificados de autoridades certificadoras da ICP-Brasil nos sistema emissor disponível em arquivo compactado (https://www.gov.br/iti/pt-br/assuntos/repositorio/certificados-das-acs-da-icp-brasil-arquivo-unico-compactado).

Att,

Niangela Oliveira
Central de Serviços de TI
Coordenadoria de Serviços de TI – CSTI
Secretaria de Estado de Fazenda de Mato Grosso
E-mail: atendimento.ti@sefaz.mt.gov.br 
Atendimento WhatsApp de TI: https://wa.me/556536172080 
Sefaz para Você: https://sac.sefaz.mt.gov.br/citsmart/login/login.load**

**Comment by Samuel-Oliveira** [comment]
Corrigido versao 4.00.30
