### ISSUE TITLE
Inclusão dos Schemas

### ISSUE THREAD

**Issue by bpalermo** [Samuel-Oliveira/Java_NFe#28]
Boa noite,

Algum motivo específico para não incluir os schemas na biblioteca como resource?

Obrigado,
Bruno

**Comment by Samuel-Oliveira** [comment]
Olá!
A Api é usada como Dependência, então fica compactada dentro de um JAR.
Para todos os efeitos, você não consegue usar qualquer arquivo que esteja dentro do Jar, então para funcionar eu teria que descompactar os schemas dentro de uma pasta temporária só pra depois poder utilizada. Nisso perde-se muito tempo. Por isso, os Schemas devem ficar dentro do seu projeto e não dentro da API.

**Comment by bpalermo** [comment]
Agradeço o esclarecimento!
