### ISSUE TITLE
Nota Técnica 2019.001 Inclusão de grupo opcional após o campo cBenef contendo campos para as informações do crédito presumido:

### ISSUE THREAD

**Issue by edivaldoms** [Samuel-Oliveira/Java_NFe#283]
Nota Técnica 2019.001 1.60
Inclusão de grupo opcional após o campo cBenef contendo campos para as informações do crédito presumido:
cCredPresumido, pCredPresumido e vCredPresumido.

Inclusão do campo cBenefRBC após o campo pRedBC para informar código de benefício fiscal de redução de base de cálculo dentro do CST51 quando acumular com o diferimento:
6.4 Grupo N07. Grupo Tributação do ICMS= 51

**Comment by Samuel-Oliveira** [comment]
Ja esta disponivel na versao 4.00.34.
