### ISSUE TITLE
ICMS 41 - Não tributado

### ISSUE THREAD

**Issue by jonasrotilli** [Samuel-Oliveira/Java_NFe#288]
Alguém sabe como devo enviar no caso do ICMS ser 41 - Não tributado?

Vejo TNFe.InfNFe.Det.Imposto.ICMS.ICMS40 e depois pula para TNFe.InfNFe.Det.Imposto.ICMS.ICMS51, mas o 41 eu não acho.

Desde de já, obrigado e parabéns pelo ótimo trabalho!

**Comment by resplandes** [comment]
Bom dia, você usa o ICMS40 mas o codigo do CST é 41
pode fazer assim que da bom.

**Comment by resplandes** [comment]
@Samuel-Oliveira  o @jonasrotilli é meu contarraneo, tenho que tratar ele bem kkkk

**Comment by jonasrotilli** [comment]
@resplandes  deu certo! Muito obrigado!
