### ISSUE TITLE
migração para jakarta

### ISSUE THREAD

**Issue by rmalavazigalli** [Samuel-Oliveira/Java_NFe#289]
bom dia.

Tem alguma previsão de migrar as libs usadas para a nova nomenclatura jakarta?

**Comment by Samuel-Oliveira** [comment]
Tudo bem? 

Nenhuma previsão. 
Jakarta não é nativo no Java 8.

E 90% da base de usuários utiliza Java 8.

Então não vejo motivos para migração.

**Comment by Samuel-Oliveira** [comment]
@rmalavazigalli me confirma sanei sua dúvida por favor e feche a issue.
Caso não responda em 3 dias ela será fechada automaticamente.

**Comment by Samuel-Oliveira** [comment]
Fechado por inatividade!
