### ISSUE TITLE
CNPJ Alfanumérico

### ISSUE THREAD

**Issue by cleitonFranca** [Samuel-Oliveira/Java_NFe#290]
Já temos alguma documentação oficial dos órgãos estaduais ou federais à respeito do CNPJ alfanumérico? 

Novo formato alfanumérico

Para evitar o esgotamento de números de CNPJ, a RFB adotou um projeto para transformar o CNPJ em um identificador alfanumérico. Essa mudança permitirá uma quantidade quase infinita de combinações, aumentando a capacidade de identificação em 6.561 vezes.

Atualmente, o CNPJ é um identificador numérico composto por 14 dígitos, divididos em três partes:

    Número raiz: 8 dígitos que identificam a pessoa jurídica.
    Número de ordem: 4 dígitos após a barra que identificam estabelecimentos.
    Dígitos Verificadores (DV): 2 dígitos finais usados para validação.

O novo CNPJ alfanumérico manterá 14 posições:

    Oito primeiras posições: caracteres alfanuméricos identificando a raiz.
    Quatro posições seguintes: caracteres alfanuméricos para ordem do estabelecimento.
    Duas últimas posições: numéricas, identificando os dígitos verificadores.

![image](https://github.com/Samuel-Oliveira/Java_NFe/assets/3201833/974a37b2-2e9d-4fb2-b417-9a0c9a0d0dcf)

Quando começará a implementação do CNPJ alfanumérico?

A implementação do CNPJ alfanumérico será realizada em fases, com um tempo estimado de 18 meses para conclusão. Essa transição será feita de forma a minimizar o impacto sobre a sociedade e sistemas informatizados, garantindo a coexistência do atual formato numérico.

![image](https://github.com/Samuel-Oliveira/Java_NFe/assets/3201833/1b139899-1e99-4fd3-b84e-00a9c6bf17bd)

A implantação completa do novo formato está prevista para janeiro de 2026, com um cronograma de implementação detalhado que será divulgado pela Receita Federal do Brasil.

Fonte: https://treeunfe.com.br/blog/receita-federal-anuncia-cnpj-alfanumerico/

**Comment by marcelocaser** [comment]
Por hora temos uma nota técnica, que traz além desses detalhes, traz também informações sobre a validação do dígito verificador. Continuando da mesma forma.

[Nota Corat/Suara/RFB no 145, de 12 de abril de 2024](https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comite-gestor-do-programa-de-produtividade-da-receita-federal/NotasTecnicas/3.pdf)

**Comment by Samuel-Oliveira** [comment]
Guys, acho ok divulgar a noticia. (Ja haviamos discutido isso, inclusive no Discord)
Mas vou fechar essa Issue pq n tem nada que temos que modificar na Biblioteca até que lance uma layout da NFe com alteraçao
O que deve acontecer somente em 2025.
