### ISSUE TITLE
Dúvida avulsa: MDFe

### ISSUE THREAD

**Issue by jonasrotilli** [Samuel-Oliveira/Java_NFe#292]
Sei que este git é sobre NFe (que é excelente), mas o documento MDFe é meio interligado em muitos casos, onde o emissor transporta a própria carga.

Alguém têm alguma sugestão de uma biblioteca para isso parecida com esta aqui, para emitir MDFe?

**Comment by lucassilva1609** [comment]
Me chama que eu te ajudo  ou posso te chamar no email ?

**Comment by jonasrotilli** [comment]
Pode me chamar, não localizei teu e-mail. O meu é jonasrotillI@gmail.com

**Comment by lucassilva1609** [comment]
Ou melhor procure no Discord como Java Brasil ali tem uma comunidade que consegue lhe ajudar até o próprio Samuel

**Comment by jonasrotilli** [comment]
Ótimo, aqui não é o lugar disso mesmo.
Obrigado.
