### ISSUE TITLE
Dúvida: Inutilização de NFe com CPF

### ISSUE THREAD

**Issue by henrque** [Samuel-Oliveira/Java_NFe#294]
Como inutilizar uma NFe emitida por uma pessoa física, na qual o emitente possui um CPF em vez do CNPJ?
Utilizando essa biblioteca percebi que é cancelar uma NFe utilizando o CPF porém o mesmo não é verdade para o caso de inutilizar a NFe pois o InutilizacaoUtil não possui o atributo CPF, e caso eu passe o CPF no lugar do CNPJ ele retorna o erro falando que o valor informado não é um CNPJ válido.

**Comment by Samuel-Oliveira** [comment]
De acordo com o MOC e os Schemas disponibilizados pela Sefaz no ambiente nacional não está previsto inutilização de numeração para Pessoa Física.
