### ISSUE TITLE
Problema de leitura de dados na consulta de uma NF-e

### ISSUE THREAD

**Issue by rodrigo7797** [Samuel-Oliveira/Java_NFe#298]
Ao consultar a situação de uma NF-e, quando a mesma está cancelada, os dados de detEvento { descEvento e xJust } não estão sendo populados.

Segue imagem com o exemplo
![ConsultaNfe](https://github.com/user-attachments/assets/dbace7a9-9510-48da-b658-e87e3e3c360e)

**Comment by Samuel-Oliveira** [comment]
Blz? O Any é o padrao de retorno. 
Se observar o XSD vai ver que está correto. 

O que tem que fazer nesse caso é converter o Any para o retorno do evento desejado.
Se tiver duvida nos acione via discord.
