### ISSUE TITLE
Maven Config

### ISSUE THREAD

**Issue by claudsan** [Samuel-Oliveira/Java_NFe#30]
Não baixa pelo repositório do maven:
`Missing artifact br.com.samuelweb:java-nfe:jar:3.10.8`

**Comment by Samuel-Oliveira** [comment]
Na tela proncipal é bem clara, vc tem que adicionar o Repositorio que esta a API.
`<repository>
	         <name>Repositorio Autocom SnapShot</name>
	         <id>Snapshot</id>
                 <url>http://www.autocomsistemas.com.br:8081/nexus/content/repositories/autocom/</url>
</repository>`

**Comment by claudsan** [comment]
Após alguns minutos deu certo, vlw
