### ISSUE TITLE
Branch_4.0 está sem suporte ao certificado A1/pfx?

### ISSUE THREAD

**Issue by edivaldoms** [Samuel-Oliveira/Java_NFe#31]
A classe CertificadoUtil.java está diferente da classe na Branch_3.10.8

https://github.com/Samuel-Oliveira/Java_NFe/blob/Branch_4.0/src/main/java/br/com/samuelweb/nfe/util/CertificadoUtil.java

https://github.com/Samuel-Oliveira/Java_NFe/blob/Branch_3.10.8/src/main/java/br/com/samuelweb/nfe/util/CertificadoUtil.java

**Comment by Samuel-Oliveira** [comment]
Na versão 4.00 Foi removido o controle do certificado na API. Ele esta sendo feito externamente.
Então não será mais utilizado CertificadoUtil, utilize CertificadoService no lugar.

Ex:
CertificadoService.certificadoPfx(caminhoCertificado, senha);
