### ISSUE TITLE
WebService de URL-QRCode não encontrado para Rio Grande do Sul

### ISSUE THREAD

**Issue by Bonissauro** [Samuel-Oliveira/Java_NFe#33]
Estou conseguindo gerar, assinar e transmitir uma NFE (modelo 55), mas na hora de gerar o qrCode dela, recebo a mensagem "WebService de URL-QRCode não encontrado para Rio Grande do Sul". 

`String qrCodeChaveSemNfe = infNFe.getId().substring(3);  
            String qrCodeVersao = "100";  
            String qrCodeAmbiente = config.getAmbiente();  
            String qrCodeCpfCnpj = (dest!=null?Ferramentas.apenasNumeros(dest.getCNPJ() == null ? dest.getCPF() : dest.getCNPJ()):"");  
            String qrCodeDtEmissao = ide.getDhEmi();  
            String qrCodeVnf = total.getICMSTot().getVNF();  
            String qrCodeVicms = total.getICMSTot().getVICMS();  
            String qrCodeBase64 = Base64.getEncoder().encodeToString(enviNFe.getNFe().get(0).getSignature().getSignedInfo().getReference().getDigestValue());  
                      
            String qrCode = NFCeUtil.getCodeQRCode(  
                    qrCodeChaveSemNfe,   
                    qrCodeVersao,   
                    qrCodeAmbiente,   
                    qrCodeCpfCnpj,   
                    qrCodeDtEmissao,   
                    qrCodeVnf,   
                    qrCodeVicms,  
                    qrCodeBase64,   
                    idToken,   
                    csc,   
                    getUrl(ConstantesUtil.NFE, ConstantesUtil.SERVICOS.URL_QRCODE));  `

Interessante é que quando, no "getURL", seleciono ConstantesUtil.NFC dá tudo certo e sem erros.

**Comment by Samuel-Oliveira** [comment]
Não Existe QRCode Em Modelo 55 (NFe)
