### ISSUE TITLE
CertificadoUtil: métodos faltando

### ISSUE THREAD

**Issue by ViniciusAzevedo** [Samuel-Oliveira/Java_NFe#39]
Olá,
Estão faltando os métodos: listaCertificadosWindows() e certificadoPfx() na classe CertificadoUtil
De modo que não consigo configurar a API como orienta o wiki: https://github.com/Samuel-Oliveira/Java_NFe/wiki/01-:-Configuracoes

Att

**Comment by Samuel-Oliveira** [comment]
Obrigado Pelo aviso, foi alterado de CertificadoUtil para CertificadoService e esqueci de alterar a Wiki.
