### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by cassiobt** [Samuel-Oliveira/Java_NFe#40]
É possível setar um timeout personalizado de espera do retorno da manifestação?

**Comment by Samuel-Oliveira** [comment]
Interessante!
Vou implementar na Nova Versão, que irá sair essa semana!

**Comment by Samuel-Oliveira** [comment]
Adicionado a versão 4.00.2.
Após iniciar as Configurações, use o comando para setar o TimeOut em milisegundos: 

    configuracoesIniciaisNfe.setTimeout(5000)

**Comment by pedrohlira** [comment]
Olá, como capturar o erro de timeout, pois mesmo mudando para 30000 (30 segundos) ainda pode ocorrer, a ideia é tomar uma ação neste caso, pois possivelmente a nota foi autorizada na sefaz, mas ela não respondeu ao meu servidor com o XML resultante.

Ao usar este método: TRetEnviNFe retorno = Nfe.enviarNfe(NFe.CONFIG, enviNFe, DocumentoEnum.NFCE); como pegar o erro correto de timeout 12002 e assim fazer o devido tratamento ?

Obrigado.
