### ISSUE TITLE
Adicionar CONSUMO_INDEVIDO("656") em StatusEnum.java

### ISSUE THREAD

**Issue by fredwilliamtjr** [Samuel-Oliveira/Java_NFe#42]
Se adicionar CONSUMO_INDEVIDO("656") em StatusEnum.java.

Obrigado!

**Comment by Samuel-Oliveira** [comment]
Será adicionado na proxima versão!

**Comment by fredwilliamtjr** [comment]
Obrigado Samuel!

**Comment by Samuel-Oliveira** [comment]
Feito, Disponibilizado na Branch Desenvolvimento (https://github.com/Samuel-Oliveira/Java_NFe/tree/Desenvolvimento ) em breve na Oficial.
