### ISSUE TITLE
Sugestão para adicionar no XmlUtil

### ISSUE THREAD

**Issue by edivaldoms** [Samuel-Oliveira/Java_NFe#47]
Sugiro adicionar transformar o Objeto em XML(String) do retorno da consulta da situação da NFe

Ex.: 
private static final String SITUACAO_NFE_RET = "TRetConsSitNFe";
...
public static <T> String objectToXml(Object obj) throws JAXBException, NfeException {
...
case SITUACAO_NFE_RET:
                context = JAXBContext.newInstance(TRetConsSitNFe.class);
                element = new br.inf.portalfiscal.nfe.schema_4.retConsSitNFe.ObjectFactory().createRetConsSitNFe((TRetConsSitNFe) obj);
                break;
..

**Comment by Samuel-Oliveira** [comment]
Tudo Bom? Perfeito, será adicionado!

**Comment by Samuel-Oliveira** [comment]
Feito, Disponibilizado na Branch Desenvolvimento (https://github.com/Samuel-Oliveira/Java_NFe/tree/Desenvolvimento ) em breve na Oficial.
