### ISSUE TITLE
Caminho de Schemas com acento e Ç 

### ISSUE THREAD

**Issue by san0suke** [Samuel-Oliveira/Java_NFe#55]
Olá, eu estou realizando alguns testes e coloquei a pasta do projeto em um caminho com acento e Ç: 
`"D:\Downloads\Teste Instalação\glassfish5\"  `

O projeto funciona normalmente em um caminho sem espaço e sem esses caracteres, como por exemplo: 
`"D:\Downloads\TesteInstalacao\glassfish5\"  `

Mas no caminho com estes caracteres especiais ele ocasiona o seguinte erro: 
`Erro Na Validação do Xml: schema_reference.4: Falha ao ler o documento do esquema '/D:/Downloads/Teste Instalação/glassfish5/glassfish/domains/domain1/applications/meuprojeto/WEB-INF/classes/Schemas/enviNFe_v3.10.xsd' porque 1) não foi possível encontrar o documento; 2) não foi possível ler o documento; 3) o elemento-raiz do documento não é . cvc-elt.1: Não pode localizar a declaração do elemento 'enviNFe'.  `

Eu depurei o código e acredito que o erro esteja acontecendo ao executar a seguinte linha de código: 
```
ConfiguracoesIniciaisNfe.iniciaConfiguracoes(estado, ambiente,  
                certificado, getPathSchemas(), ConstantesUtil.VERSAO.V3_10);  
```

Alguém sabe dizer o que estou fazendo de errado?

**Comment by Samuel-Oliveira** [comment]
Tudo bom?
O problema não parece ter relação a Acentos, e sim pelo motivo de ter colocado os XSD dentro do WAR.
Assim a aplicação não consegue encontra-los.

Coloque em umas pasta externa ou Mude a maneira de passar o caminho dos XSD

**Comment by fredwilliamtjr** [comment]
@san0suke eu coloco os XSDs dentro do projeto, eu coloco eles na pasta main\resources\SchemasNfe400\

Eu uso isso para devolver o caminho:

> public static String caminhoSchemasNfe400() {
        String realPath = "";
        FacesContext facesContext = FacesContext.getCurrentInstance();
        if (facesContext != null) {
            ServletContext context = (ServletContext) facesContext.getExternalContext().getContext();
            realPath = context.getRealPath("/WEB-INF/classes/SchemasNfe400");
        }
        return realPath;
    }

Espero ter ajudado!
