### ISSUE TITLE
Inutilizacao de numeração de NFEc - Exemplo 

### ISSUE THREAD

**Issue by Bonissauro** [Samuel-Oliveira/Java_NFe#56]
Samuel!

Nao estou encontrando jeito de usar esse parametro id do exemplo de inutilizacao.

Por exemplo, seu eu quiser inutilizar do numero 3 até o 19 da serie 4 do modelo 65 de uma empresa, como devo especificar o id para submeter? 

Tentei de tudo que foi jeito aqui (menos o certo, aparentemente, kkkk)!

**Comment by Samuel-Oliveira** [comment]
Tudo Bom?
Segundo o Manual do Contrinuinte: 
Id de Inutilização é formado Por:
com Código da UF + Ano (2 posições) + CNPJ
+ modelo + série + número inicial e número final
precedida do literal “ID”

Então No seu caso:
ID52189999999999999965004000000003000000019
Onde:
52 - Codigo do Estado (mude para seu Estado)
18 - Ano
99999999999999 - Cnpj (Mude para seu CNPJ)
65 - Modelo NFCe
004 - Serie
000000003 - Numeração Inicial
000000019 - Numeração Final

**Comment by Bonissauro** [comment]
Caramba! Deu até vergonha! Não tinha visto isso. Kkkkk!

Obrigado, Samuel!
