### ISSUE TITLE
Erro - WebService de NfeAutorizacao_4.00 não encontrado para Rio Grande do Sul

### ISSUE THREAD

**Issue by Bonissauro** [Samuel-Oliveira/Java_NFe#57]
Samuel,

atualizei pra versao 4 da tua biblioteca, fiz os acertos e as notas estao funcionando aqui para o DF. Todavia, quando tento utilizar em um cliente do RS, recebo a mensagem
 
WebService de NfeAutorizacao_4.00 não encontrado para Rio Grande do Sul

Já atualizei a pasta Schemas, mas o erro persiste.

O que pode estar ocorrendo?

**Comment by Samuel-Oliveira** [comment]
Beleza, Quando você executa ele printa varias informações no Console, pode me mostrar tudo que ele printou por favor?

**Comment by Bonissauro** [comment]
Cara, quando tu falou na console, percebi que eu estava com a opcao de debug da tua classe ConfiguracoesIniciais desativada. Fui la e ativei.

Quando rodei ele printou o ambiente e percebi de cara que eu estava rodando com o token de homologacao no ambiente de producao. Morreu o problema.

Obrigado!

PS: Vai chegar o dia em que minha consciência vai me OBRIGAR a te mandar um presentaço aí pro Goiás, meu! Kkkkkk!!! Se vingar esse meu projeto, isso vai acontecer.
