### ISSUE TITLE
Forma de pagamento não é impressa no Danfe consultado!

### ISSUE THREAD

**Issue by Bonissauro** [Samuel-Oliveira/Java_NFe#60]
Oi, Samuel!

Após transmitir a nota com sucesso, ler o QrCode e chegar ao site da Sefaz (RS e DF), percebo que a forma de pagamento da venda não é exibida.

Seguindo os exemplos da wiki, estou fazendo assim:

String codigoTipoPagamentoNfe = "01";
String valorPagamento = "20.00";
		
Pag pag = new Pag();
		
Pag.DetPag detPag = new Pag.DetPag();
detPag.setTPag(codigoTipoPagamentoNfe);
detPag.setVPag(valorPagamento);
        
pag.getDetPag().add(detPag);
        
infNFe.setPag(pag);
        
nfe.setInfNFe(infNFe);

A área pertinente do xml fica assim:

`<pag>
      <detPag>
            <tPag>01</tPag>
            <vPag>20.00</vPag>
      </detPag>
</pag>
`

Mas ao consultar a coisa lendo o qrcode, a forma de pagamento e valor pago nao sao exibidos:

![img_8628](https://user-images.githubusercontent.com/21696978/38838588-40296eae-41ad-11e8-80af-0eeab1b9c767.jpg)

O que posso ter deixado passar?

**Comment by Samuel-Oliveira** [comment]
Bom Dia.
Olhe no Xml Se contem os Dados.
Caso sim, o problema é no site visualizador!
