### ISSUE TITLE
Consulta cadastro não aceita versão diferente de 4.0.0  

### ISSUE THREAD

**Issue by barceloscbc** [Samuel-Oliveira/Java_NFe#62]
Como e fixo o parâmetro de consulta cadastro, para os estado cuja consulta cadastro não e 4.0 o sistema ocorre o erro de não encontrar o propriedade.

String CONSULTA_CADASTRO = "NfeConsultaCadastro_4.00";

**Comment by Samuel-Oliveira** [comment]
Oks, Em breve vou ver a Possibilidade!

**Comment by Samuel-Oliveira** [comment]
Adicionado o Consulta Cadastro 4.00 a todos os estados!
