### ISSUE TITLE
Exemplo de uso do framework

### ISSUE THREAD

**Issue by cgarrotti** [Samuel-Oliveira/Java_NFe#64]
Olá amigo, há algum exemplo de uso do framework ? Sou novo no java, vindo do Delphi, precisaria de um exemplo do uso do framework, pode ser até mesmo algo como verificar o Status do servidor da Receita.

**Comment by Samuel-Oliveira** [comment]
Hm... Você olhou a Wiki?

https://github.com/Samuel-Oliveira/Java_NFe/wiki

**Comment by cgarrotti** [comment]
>

**Comment by cgarrotti** [comment]
Tem alguma função para gerara chave da NFe ? aquela de 44 digitos ?

**Comment by Samuel-Oliveira** [comment]
Você quer dizer o digito verificado certo?
Por que a chave você que gera com seus dados.

`public static int modulo11(String chave) {
		int total = 0;
		int peso = 2;

		for (int i = 0; i < chave.length(); i++) {
			total += (chave.charAt((chave.length() - 1) - i) - '0') * peso;
			peso++;
			if (peso == 10)
				peso = 2;
		}
		int resto = total % 11;
		return (resto == 0 || resto == 1) ? 0 : (11 - resto);
	}`
