### ISSUE TITLE
IPI

### ISSUE THREAD

**Issue by egioncpdsi** [Samuel-Oliveira/Java_NFe#68]
Olá Samuel, estou com problemas para encontrar/usar o método de IPI, estava tentando usar da mesma forma que os demais Impostos ICMS, PIS e Cofins, poderia me explicar como funciona como essa tag é inserida?
Agradeço desde já!

**Comment by Samuel-Oliveira** [comment]
Beleza? 

Aqui exemplo de como Pegar: http://www.javac.com.br/jc/posts/list/2571-pegar-valor-do-ipi-resolvido.page

Como atribuir: http://www.javac.com.br/jc/posts/list/2605-lib-nfe-xml-pl008h-nao-tem-a-classe-ipi-resolvido.page

Abraços!

**Comment by egioncpdsi** [comment]
Olá Samuel beleza ? 
Desculpe mas tive que reabrir esse issue ><
Ainda to apanhando pra esse imposto ç-ç
Eu vi e revi os fóruns que falam a respeito da criação dessas tags 
Acabei me deparando com o tal erro:

> nfe br.inf.portalfiscal.nfe.schema_4.nfe.TIpi is not known to this context

Fiz a partir dos links que tu tinhas me mandado anteriormente : 
[http://www.javac.com.br/jc/posts/list/2605-lib-nfe-xml-pl008h-nao-tem-a-classe-ipi-resolvido.page](url) e [http://www.javac.com.br/jc/posts/list/1986-gerar-xml-na-parte-de-imposto-310-resolvido.page](url) (que estava nos posts)

Estou construindo dessa forma : 

`//Construcao do ipi`
`TIpi ipi = new TIpi();
        IPINT ipiTrib = new IPINT();
        ipi.setCEnq("999");
        ipiTrib.setCST(item.getCstIpi());
        ipi.setIPINT(ipiTrib);`

E inserindo no elemento imposto : 

`JAXBElement<TIpi> ipiElement = new JAXBElement<TIpi>(new QName("IPI"), TIpi.class, ipi);
        imposto.getContent().add(ipiElement);`

E utilizando o seguinte import do ipi:

`import br.inf.portalfiscal.nfe.schema_4.nfe.TIpi;
import br.inf.portalfiscal.nfe.schema_4.nfe.TIpi.IPINT;`

O xml está sendo construído normalmente quando não coloca essas tags, a partir do momento que insiro essas informações de IPI...
Já agradeço pela resposta ! <3

**Comment by rreynoud** [comment]
Me passe o teu skype, eu acho que tive o mesmo "problema", mas consegui resolver tem tudo na biblioteca, da forma como o Samuel falou, a lib é bem completa! Parabéns Samuel!
vou te passar mais ou menos o código que eu fiz, e qualquer coisa pode me adicionar no skype e perguntar algo no meu skype Rafael R. B. rafareypy.

so que o meu codigo esta em kotlin
`` ipi = ipiService!!.createIPI(nfTeorema, produto)

        if (ipi != null) {
            val ipiElement = JAXBElement(QName("IPI"), TIpi::class.java, ipi)
            imposto.content.add(ipiElement)
        }

metodo que que cria o ipi

    override fun createIPI(nfTeorema: NotaFiscal, produto: Produto): TIpi? {
        var ipi: TIpi? = null

        val ipiTeorema = produto.ipi

        if (ipiTeorema != null && ipiTeorema.cst != null && ipiTeorema.cst != EdocConstants.Ipi.ipiNaoIncide) {
            ipi = TIpi()

            if (ipiTeorema.codigoEnquadramento != null)
                ipi.cEnq = ipiTeorema.codigoEnquadramento

            if (ipiTeorema.cnpjProdutor != null)
                ipi.cnpjProd = ipiTeorema.cnpjProdutor

            if (ipiTeorema.codigoSelo != null)
                ipi.cSelo = ipiTeorema.codigoSelo

            if (ipiTeorema.quantidadeSelo != null)
                ipi.qSelo = ipiTeorema.quantidadeSelo

            if (listIpiTrib.contains(ipiTeorema.cst))
                ipi.ipiTrib = this.createIPITrib(ipiTeorema)
            else if (listIpiInt.contains(ipiTeorema.cst))
                ipi.ipint = this.createIPINT(ipiTeorema)

        }
        return ipi
    }

``

Espero ter ajudado!

**Comment by egioncpdsi** [comment]
Opa valeu pela ajuda rreynoud.
Pelo que eu li e entendi o teu código ta bem parecido com o meu. Estou fazendo basicamente da mesma forma , construo o objeto Ipi alimento ele com as informações e depois insiro no List de imposto. 
Quando chamo o método de colocar esse xml em string que acontece isso, indicando que ele não está esperando esse IPI...

**Comment by rreynoud** [comment]
Que coisa vc pode passar um pouco mais de como esta o teu codigo?
Assim podemos ver melhor e ate mesmo eu posso colocar ele aqui na minha api e testar.

**Comment by egioncpdsi** [comment]
Rapaz acabei de resolver kkkkk.
Sabia que era uma coisa idiota...
Já que o IPI é usado de diversas formas pela api, tem várias classes com esse nome
O que estava no meu código para importar era: 

`import br.inf.portalfiscal.nfe.schema_4.nfe.TIpi;`

e o certo é :

` import br.inf.portalfiscal.nfe.schema_4.enviNFe.TIpi;`

Foi um erro idiota da minha parte hehehe
Mas obrigado rreynoud pela ajuda ! <3

**Comment by rreynoud** [comment]
Que sorte que funcionou!
Pior que eu tbm tive o mesmo problema e não me lembrei em te avisar!
