### ISSUE TITLE
Urls Amazonas

### ISSUE THREAD

**Issue by lyonfreitas** [Samuel-Oliveira/Java_NFe#69]
Boa noite, segue as urls de amazonas para adicionar ao projeto.

Excelente trabalho!

NfeInutilizacao | 4.00 | https://nfe.sefaz.am.gov.br/services2/services/NfeInutilizacao4
NfeConsultaProtocolo | 4.00 | https://nfe.sefaz.am.gov.br/services2/services/NfeConsulta4
NfeStatusServico | 4.00 | https://nfe.sefaz.am.gov.br/services2/services/NfeStatusServico4
RecepcaoEvento | 4.00 | https://nfe.sefaz.am.gov.br/services2/services/RecepcaoEvento4
NFeAutorizacao | 4.00 | https://nfe.sefaz.am.gov.br/services2/services/NfeAutorizacao4
NFeRetAutorizacao | 4.00 | https://nfe.sefaz.am.gov.br/services2/services/NfeRetAutorizacao4

**Comment by Samuel-Oliveira** [comment]
Adicionado , Esta na Branch de Produção!
