### ISSUE TITLE
Criar novos métodos para XmlUtil, para montar os Proc do Inutilizar, Cancelar e Evento.

### ISSUE THREAD

**Issue by pedrohlira** [Samuel-Oliveira/Java_NFe#71]
Olá assim como existe o método abaixo poderia ter mais alguns:

**`public static String criaNfeProc(TEnviNFe enviNfe, Object retorno) throws JAXBException, NfeException {}`**

`public static String criaInutProc(TEnviNFe enviNfe, Object retorno) throws JAXBException, NfeException {}`

`public static String criaCancProc(TEnviNFe enviNfe, Object retorno) throws JAXBException, NfeException {}`

`public static String criaEventoProc(TEnviNFe enviNfe, Object retorno) throws JAXBException, NfeException {}`

Pois é necessário os arquivos XML para a contabilidade.

**Comment by Samuel-Oliveira** [comment]
Na Wiki, ja possui exemplo de como gerar o Proc de cada um desses!
