### ISSUE TITLE
Contingência EPEC

### ISSUE THREAD

**Issue by pedrohlira** [Samuel-Oliveira/Java_NFe#72]
Existe esta possibilidade dentro da API ? ou seria uma nova funcionalidade a ser desenvolvida ?

Obrigado.

PS: eu tenho isso desenvolvido na versão NFe 3.10, mas como estou migrando para NFe 4.00 e achei sua API fantástica, achei melhor usar a sua que migrar tudo.

Ex:

> protected String getEpec(InfNFe infNFe) throws Excecao {
        try {
            // desmembra a chave
            String uf = chave.substring(0, 2);
            String cnpj = chave.substring(6, 20);
            int modelo = Integer.valueOf(chave.substring(20, 22));
            String data = NFe.formatarData(Util.getCalendario().getTime());
            String tipo = "110140";
            // destinatario
            com.nugovbr.nfe.envepec.TEvento.InfEvento.DetEvento.Dest destEvento = new com.nugovbr.nfe.envepec.TEvento.InfEvento.DetEvento.Dest();
            destEvento.setUF(com.nugovbr.nfe.envepec.TUf.valueOf(infNFe.getDest().getEnderDest().getUF().value()));
            if (infNFe.getDest().getCPF() != null) {
                destEvento.setCPF(infNFe.getDest().getCPF());
            } else {
                destEvento.setCNPJ(infNFe.getDest().getCNPJ());
                destEvento.setIE(infNFe.getDest().getIE());
            }
            destEvento.setVNF(infNFe.getTotal().getICMSTot().getVNF());
            destEvento.setVICMS(infNFe.getTotal().getICMSTot().getVICMS());
            destEvento.setVST(infNFe.getTotal().getICMSTot().getVST());
            // descricao
            com.nugovbr.nfe.envepec.TEvento.InfEvento.DetEvento detEvento = new com.nugovbr.nfe.envepec.TEvento.InfEvento.DetEvento();
            detEvento.setVersao(NFe.EVENTO);
            detEvento.setDescEvento("EPEC");
            detEvento.setCOrgaoAutor(uf);
            detEvento.setTpAutor("1");
            detEvento.setVerAplic("mysig.com.br");
            detEvento.setDhEmi(data);
            detEvento.setTpNF(infNFe.getIde().getTpNF());
            detEvento.setIE(infNFe.getEmit().getIE());
            detEvento.setDest(destEvento);
            // gera o objeto
            com.nugovbr.nfe.envepec.TEvento.InfEvento infEvento = new com.nugovbr.nfe.envepec.TEvento.InfEvento();
            infEvento.setId("ID" + tipo + chave + "01");
            infEvento.setCOrgao("91");
            infEvento.setTpAmb(NFe.AMBIENTE);
            infEvento.setCNPJ(cnpj);
            infEvento.setChNFe(chave);
            infEvento.setDhEvento(data);
            infEvento.setTpEvento(tipo);
            infEvento.setNSeqEvento("1");
            infEvento.setVerEvento(NFe.EVENTO);
            infEvento.setDetEvento(detEvento);
            // evento
            com.nugovbr.nfe.envepec.TEvento evento = new com.nugovbr.nfe.envepec.TEvento();
            evento.setInfEvento(infEvento);
            evento.setVersao(NFe.EVENTO);
            // envio do evento
            com.nugovbr.nfe.envepec.TEnvEvento envio = new com.nugovbr.nfe.envepec.TEnvEvento();
            envio.setIdLote(new Date().getTime() + "");
            envio.setVersao(NFe.EVENTO);
            envio.getEvento().add(evento);
            JAXBElement<com.nugovbr.nfe.envepec.TEnvEvento> element = new com.nugovbr.nfe.envepec.ObjectFactory().createEnvEvento(envio);
            String xml = NFe.objToXml(element, "com.nugovbr.nfe.envepec");
            // assina e envia
            xml = NFe.assinar(xml, Situacao.EVENTO, cnpj);
            procEpec = NFe.evento(xml, uf, tipo, modelo);
            // analisa o retorno e seta os status
            com.nugovbr.nfe.retenvepec.TRetEnvEvento ret = NFe.xmlToObj(procEpec, "com.nugovbr.nfe.retenvepec");
            // verifica se sucesso
            if (ret.getCStat().equals("128")) {
                if (ret.getRetEvento().get(0).getInfEvento().getCStat().equals("136")) {
                    protocolo = ret.getRetEvento().get(0).getInfEvento().getNProt();
                    return NFe.montarProcEvento(xml, procEpec);
                } else {
                    throw new Excecao(ret.getRetEvento().get(0).getInfEvento().getXMotivo());
                }
            } else {
                throw new Excecao(ret.getXMotivo() + xml);
            }
        } catch (Exception ex) {
            Util.LOG.error("Problemas ao emitir a nota em EPEC :: ", ex);
            throw new Excecao("Problemas ao emitir a nota em EPEC :: " + ex.getMessage());
        }
    }

**Comment by Samuel-Oliveira** [comment]
Opa, Beleza?

Nâo. Não tem nada de EPEC... Esse evento irá funcionar na versão 4.00?

**Comment by pedrohlira** [comment]
Opa, blz.

Tudo indica que sim, pois não houve mudança sobre ela eis o link do schema

Esquemas XML NF-e - Pacote de Liberação Evento EPEC v1.01 (30/05/2014) (ZIP)

[http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=HcoVPI2JvY0=](url)

**Comment by Samuel-Oliveira** [comment]
OKs. Esse Exemplo que vc postou ai está funcional?
Me adicione no Skype (samuk.exe@hotmail.com)
Vou liberar ele no Sabado para vc testar, e tem q ser logo por que no domingo vou lançar nova versão.
Dai se não conseguir testar no sabado só na proxima versão.

**Comment by Samuel-Oliveira** [comment]
Feito. Adicionado a versão 4.00.5 
Exemplo : https://github.com/Samuel-Oliveira/Java_NFe/wiki/14-:-Envio-Epec

**Comment by henriquemeira** [comment]
Estou testando o envio deste evento, mas obtenho o seguinte erro:

WebService - https://homologacao.nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx
Status:491 - Motivo:Rejeição: tpEvento informado é inválido

O código para transmitir é uma cópia deste: https://github.com/Samuel-Oliveira/Java_NFe/wiki/14-:-Envio-Epec

**Comment by Samuel-Oliveira** [comment]
Beleza @henriquemeira ?
Evite colocar qlq problema em uma Isseu já fechada, sempre abra uma nova OK?
Vou Reabrir desta vez.

Peço que poste aqui o codigo que vc fez para dar esse erro, e o Xml que apareceu no console.

**Comment by henriquemeira** [comment]
Olá Samuel, tudo joia! Eu realmente fiquei na dúvida se deveria abrir uma nova issue... enfim...

Fiz alguns testes, e me parece que o problema pode estar relacionado com o servidor selecionado, quando utiliza o SVCRS a mensagem é mais "adequada", pois rejeita a UF informada (estou testando SP), já o servidor SVCAN apenas diz que o TpEvento é inválido.

Não quero dizer que a API está selecionando o servidor errado, mas que o servidor SVCAN está com problemas.

Seguem classe de teste:

`
package br.com.samuelweb.nfe;

import br.com.samuelweb.certificado.Certificado;
import br.com.samuelweb.certificado.CertificadoService;
import br.com.samuelweb.certificado.exception.CertificadoException;
import br.com.samuelweb.nfe.dom.ConfiguracoesIniciaisNfe;
import br.com.samuelweb.nfe.dom.Enum.StatusEnum;
import br.com.samuelweb.nfe.exception.NfeException;
import br.com.samuelweb.nfe.util.ConstantesUtil;
import br.com.samuelweb.nfe.util.Estados;
import br.com.samuelweb.nfe.util.XmlUtil;
import br.inf.portalfiscal.nfe.schema.envEpec.TEnvEvento;
import br.inf.portalfiscal.nfe.schema.envEpec.TEvento;
import br.inf.portalfiscal.nfe.schema.envEpec.TProcEvento;
import br.inf.portalfiscal.nfe.schema.envEpec.TRetEnvEvento;
import br.inf.portalfiscal.nfe.schema.envEpec.TUf;
import java.io.FileInputStream;
import javax.xml.bind.JAXBException;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;

public class EpecTest {

    public EpecTest() {
    }

    @BeforeClass
    public static void setUpClass() {
    }

    @AfterClass
    public static void tearDownClass() {
    }

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }
    
    private ConfiguracoesIniciaisNfe iniciaConfiguracoes(Estados uf, String ambiente) throws Exception {

        String caminhoCertificado = "ARQUIVO.pfx";
        String senha = "SENHA";
        
        Certificado certificado = CertificadoService.certificadoPfx(caminhoCertificado, senha);
        certificado.setAtivarProperties(true);

        FileInputStream cacert = new FileInputStream("Cacert");

        //CertificadoService.inicializaCertificado(certificado, CertificadoUtil.class.getResourceAsStream("/Cacert"));
        CertificadoService.inicializaCertificado(certificado, cacert);

        return ConfiguracoesIniciaisNfe.iniciaConfiguracoes(uf , ambiente,
			certificado, "C:\\SRA\\Nfe\\Schemas");
    }
    

    /**
     * Test of eventoEpec method, of class Epec.
     */
    @Test
    public void testEventoEpec() throws Exception {
        try {

            // Inicia As Configurações
            ConfiguracoesIniciaisNfe config = iniciaConfiguracoes(Estados.SP, ConstantesUtil.AMBIENTE.HOMOLOGACAO);

            String chave = "35180903073999000999550010000000024000110010";
            String cnpj = "03073999000999";
            String ie = "115261223999";
            
            
            String id = "ID" + ConstantesUtil.EVENTO.EPEC + chave + "01";

            TEnvEvento enviEvento = new TEnvEvento();
            enviEvento.setVersao(ConstantesUtil.VERSAO.EVENTO_EPEC);
            enviEvento.setIdLote("1");

            TEvento eventoEpec = new TEvento();
            eventoEpec.setVersao(ConstantesUtil.VERSAO.EVENTO_EPEC);

            TEvento.InfEvento infoEvento = new TEvento.InfEvento();
            infoEvento.setId(id);
            infoEvento.setCOrgao(String.valueOf(config.getEstado().getCodigoIbge()));
            infoEvento.setTpAmb(config.getAmbiente());
            infoEvento.setCNPJ(cnpj);
            infoEvento.setChNFe(chave);
            infoEvento.setDhEvento(XmlUtil.dataNfe());
            infoEvento.setTpEvento(ConstantesUtil.EVENTO.EPEC);
            infoEvento.setNSeqEvento("1");
            infoEvento.setVerEvento(ConstantesUtil.VERSAO.EVENTO_EPEC);

            TEvento.InfEvento.DetEvento detEvento = new TEvento.InfEvento.DetEvento();
            detEvento.setVersao(ConstantesUtil.VERSAO.EVENTO_EPEC);
            detEvento.setDescEvento("EPEC");
            detEvento.setCOrgaoAutor(config.getEstado().getCodigoIbge());
            detEvento.setTpAutor("1");
            detEvento.setVerAplic("1.0.0");
            detEvento.setDhEmi(XmlUtil.dataNfe());
            detEvento.setTpNF("1");
            detEvento.setIE(ie);

            TEvento.InfEvento.DetEvento.Dest dest = new TEvento.InfEvento.DetEvento.Dest();
            dest.setUF(TUf.SP);
            dest.setCNPJ(cnpj);
            dest.setIE(ie);
            dest.setVNF("100.00");
            dest.setVICMS("0.00");
            dest.setVST("0.00");
            detEvento.setDest(dest);

            infoEvento.setDetEvento(detEvento);
            eventoEpec.setInfEvento(infoEvento);
            enviEvento.getEvento().add(eventoEpec);

            TRetEnvEvento retorno = Nfe.enviarEpec(enviEvento, false, ConstantesUtil.NFE);

            if (!StatusEnum.LOTE_EVENTO_PROCESSADO.getCodigo().equals(retorno.getCStat())) {
                throw new NfeException("Status:" + retorno.getCStat() + " - Motivo:" + retorno.getXMotivo());

            }

            if (!StatusEnum.EVENTO_REGISTRADO_NAO_VINCULADO.getCodigo().equals(retorno.getRetEvento().get(0).getInfEvento().getCStat())) {
                throw new NfeException("Status:" + retorno.getRetEvento().get(0).getInfEvento().getCStat() + " - Motivo:" + retorno.getRetEvento().get(0).getInfEvento().getXMotivo());
            }

            System.out.println("Status:" + retorno.getRetEvento().get(0).getInfEvento().getCStat());
            System.out.println("Motivo:" + retorno.getRetEvento().get(0).getInfEvento().getXMotivo());
            System.out.println("Data:" + retorno.getRetEvento().get(0).getInfEvento().getDhRegEvento());

            // Cria TProcEventoNFe
            TProcEvento procEvento = new TProcEvento();
            procEvento.setVersao("1.00");
            procEvento.setEvento(enviEvento.getEvento().get(0));
            procEvento.setRetEvento(retorno.getRetEvento().get(0));

            System.out.println(XmlUtil.objectToXml(procEvento));

        } catch (CertificadoException | NfeException | JAXBException e) {
            System.err.println(e.getMessage());
        }

    }

}`

E aqui o resultado:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running br.com.samuelweb.nfe.EpecTest
Api Java Nfe Versão 4.00.7 - Samuel Olivera - samuk.exe@hotmail.com
Certificado: ARQUIVO - {91050DD9-E86C-4AFE-92E6-2C95D8AF6EAB} - Vencimento: 2019-07-10
Ambiente: Homologação - Estado: São Paulo
Xml Evento:
`<?xml version="1.0" encoding="UTF-8"?><envEvento xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00"><idLote>1</idLote><evento versao="1.00" xmlns="http://www.portalfiscal.inf.br/nfe"><infEvento Id="ID1101403518090307399900099955001000000002400011001001"><cOrgao>35</cOrgao><tpAmb>2</tpAmb><CNPJ>03073999000999</CNPJ><chNFe>35180903073999000999550010000000024000110010</chNFe><dhEvento>2018-09-04T09:48:06-03:00</dhEvento><tpEvento>110140</tpEvento><nSeqEvento>1</nSeqEvento><verEvento>1.00</verEvento><detEvento versao="1.00"><descEvento>EPEC</descEvento><cOrgaoAutor>35</cOrgaoAutor><tpAutor>1</tpAutor><verAplic>1.0.0</verAplic><dhEmi>2018-09-04T09:48:06-03:00</dhEmi><tpNF>1</tpNF><IE>115261223999</IE><dest><UF>SP</UF><CNPJ>03073999000999</CNPJ><IE>115261223999</IE><vNF>100.00</vNF><vICMS>0.00</vICMS><vST>0.00</vST></dest></detEvento></infEvento><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#ID1101403518090307399900099955001000000002400011001001"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>BK8R0scEGQBPhkERtH9M6OfUjgI=</DigestValue></Reference></SignedInfo><SignatureValue>g2LOnHyVjtjv3GME1rE3a3KuK9wragK6CB5cRZNjkBLhbV...</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHyTCCBbGgAwIBAgIQf1XMrTANBgkqhkiG9w0BAQsFADB0MQswCQY...</X509Certificate></X509Data></KeyInfo></Signature></evento></envEvento>`

WebService - https://homologacao.nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx
Status:491 - Motivo:Rejeição: tpEvento informado é inválido
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.844 sec

**Comment by Samuel-Oliveira** [comment]
Teve confirmação se era erro do servidor mesmo @henriquemeira ?

**Comment by henriquemeira** [comment]
Continua o erro quando transmitido para empresa de SP.

Em seu teste você realiza o envio para GO? E o resultado é de sucesso? 
Se for de sucesso, qual o URL do WebService é utilizado?

**Comment by Samuel-Oliveira** [comment]
Eu na verdade não testei.
Foi o @pedrohlira , pode nos ajudar quanto a isso?

**Comment by henriquemeira** [comment]
Você fez o teste com qual UF @pedrohlira ?

**Comment by Samuel-Oliveira** [comment]
Teve algum feed back sobre o probelma @henriquemeira?

**Comment by henriquemeira** [comment]
Oi @Samuel-Oliveira , sem feedback.
Fiz o teste hoje novamente e a rejeição é a mesma 491.
Se preferir, pode finalizar esta issue, e quando eu conseguir identificar o problema lhe retorno com a informação.

**Comment by Samuel-Oliveira** [comment]
Perfeito. So avisar q eu reabro
