### ISSUE TITLE
Contribuição Projeto

### ISSUE THREAD

**Issue by rafaeldalbosco** [Samuel-Oliveira/Java_NFe#73]
Olá Samuel, estou estudando o seu projeto e verifiquei que algumas dependências abaixo não estão open source são eles nfe-wsdl e nfe-xsd seria possível disponibiliza-los?

Estou pensando em trabalhar com o projeto e verificar o que posso melhorar nas validações do parse XML com XSD para que fique mais amigável ao usuário mostrando a descrição do campo, certamente depois de pronto e testado se for de interesse eu estaria disposto a contribuir com o projeto enviando um pull request para analisar a possibilidade de incorporar.

**Comment by Samuel-Oliveira** [comment]
Beleza?
Tanto o WSDL como o XSD são projetos sem código.
São apenas jar gerados com a conversão dos Objetos.

Use o Axis 2 e o Jaxb que vai ter o mesmo resultado.
Abraços!
