### ISSUE TITLE
Sugestão: implementar retornos em XmlUtil.objectToXml

### ISSUE THREAD

**Issue by lmfardin** [Samuel-Oliveira/Java_NFe#78]
Olá!

Gostaria de sugerir que o método XmlUtil.objectToXml também fosse implementado para parâmetros do tipo TRetEnvEvento e TRetInutNFe.
O motivo é que o sistema onde trabalho precisa guardar o XML de retorno dos eventos de cancelamento e inutilização.
Reparei que os métodos Cancelar.eventoCancelamento e Inutilizar.inutiliza geram um XML e no final convertem para objetos dos tipos que mencionei acima. De repente, seria legal ter uma opção para guardar o XML antes da conversão, ou retornar o XML e converter para o objeto depois.

**Comment by Samuel-Oliveira** [comment]
Beleza? Segunda a Legislação vc deve armazenar o  processamento dos eventos. (Proc) 
E o Proc tanto do Cancelamento qnd da Inutilziação ja estão disponiveis para conversão.

Nos exemplo da Wiki vc tem como fazer o Proc.

Sendo assim só o TRet se torna insuficiente e incompleto, não acha?

**Comment by Samuel-Oliveira** [comment]
Olá! Aguardo resposta sobre esse tópico em 5 dias, ou irei fecha-lo!

**Comment by Samuel-Oliveira** [comment]
Fechado por inatividade!
