### ISSUE TITLE
Schemas foram atualizados para 1.50 ?

### ISSUE THREAD

**Issue by pedrohlira** [Samuel-Oliveira/Java_NFe#80]
Olá Samuel, bom dia.

Baixando a nova versão 4.00.5 e baixando o arquivo schema.rar para atualizar os XSDs verifiquei que muitos arquivos não vem neste pacote e pelo visto foi adicionado somente os referentes ao evento EPEC, como fica os XSDs para validar a NFe 4.0 na versao NT 2016.002 v.1.50 ?

Baixei daqui https://github.com/Samuel-Oliveira/Java_NFe/raw/master/Schemas.rar (só como exemplo não achei dentro deste pacote o arquivo leiauteNFe_v4.00.xsd )

Esquemas XML NF-e - Pacote de Liberação No. 9 (Novo leiaute da NF-e, NT 2016.002 v.1.50) (27/04/2017) [(ZIP)]
http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=s5ZFDP5OpTU=

**Comment by Samuel-Oliveira** [comment]
Olá Pedro, realmente ocorreu um erro na Hora de Subir e foram adicionados os XSD errados.
Já foi corrigido e em breve já irei adicionar junto aos XSD da v.1.60

**Comment by pedrohlira** [comment]
Boa noite Samuel, vai publicar hoje a novar versão ?

**Comment by Samuel-Oliveira** [comment]
Foi Lançado um novo Layout : http://www.nfe.fazenda.gov.br/portal/informe.aspx?ehCTG=false#520
Então até quase ja atualizo com o novo!

**Comment by Samuel-Oliveira** [comment]
Implementado
