### ISSUE TITLE
Alteração dos WS NFC-e MT

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#81]
**Bom dia, preciso que seja alterado os endereços dos WS de NFCe do estado de MT, alterou algumas url, segue as URL corretas.**

 
**Webservices Homologação**
 
**Mato Grosso	Versão	URL**
NFeAutorizacao	4.00	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao4
NFeRetAutorizacao	4.00	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao4
NfeInutilizacao	4.00	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeInutilizacao4
NfeConsultaProtocolo	4.00	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeConsulta4
NfeStatusServico	4.00	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeStatusServico4
RecepcaoEvento	4.00	https://homologacao.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento4
NFeAutorizacao	3.10	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao
NFeRetAutorizacao	3.10	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao
NfeInutilizacao	3.10	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeInutilizacao2
NfeConsultaProtocolo	3.10	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeConsulta2
NfeStatusServico	3.10	https://homologacao.sefaz.mt.gov.br/nfcews/services/NfeStatusServico2
RecepcaoEvento	3.10	https://homologacao.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento
 
**Webservices Produção**

**Mato Grosso	Versão	URL**
NFeAutorizacao	4.00	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao4
NFeRetAutorizacao	4.00	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao4
NfeInutilizacao	4.00	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeInutilizacao4
NfeConsultaProtocolo	4.00	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeConsulta4
NfeStatusServico	4.00	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeStatusServico4
RecepcaoEvento	4.00	https://nfce.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento4
NFeAutorizacao	3.10	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeAutorizacao?wsdl
NFeRetAutorizacao	3.10	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeRetAutorizacao?wsdl
NfeInutilizacao	2.00 / 3.10	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeInutilizacao2?wsdl
NfeConsultaProtocolo	2.00 / 3.10	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeConsulta2?wsdl
NfeStatusServico	2.00 / 3.10	https://nfce.sefaz.mt.gov.br/nfcews/services/NfeStatusServico2?wsdl
RecepcaoEvento	2.00 / 3.10	https://nfce.sefaz.mt.gov.br/nfcews/services/RecepcaoEvento?wsdl

**Endereço de consulta:**
Ambiente de Homologação (testes):
http://homologacao.sefaz.mt.gov.br/nfce/consultanfce
**Ambiente Produção:**
http://www.sefaz.mt.gov.br/nfce/consultanfce

**Comment by resplandes** [comment]
Bom dia, tem alguma previsão de entrega com essa atualização ?

**Comment by resplandes** [comment]
Perfeito Samuel, funcionou, obrigado!

**Comment by Samuel-Oliveira** [comment]
Implementado
