### ISSUE TITLE
Qual ICMS eu devo usar se o código for 300?

### ISSUE THREAD

**Issue by ArielAleksandrus** [Samuel-Oliveira/Java_NFe#82]
Para o 102, eu tenho que usar o ICMSSN102, para o 500, tenho que usar o ICMSSN500. No exemplo dado, usa-se o ICMS60, mas como faço se o ICMS é o 300 (imune)?

**Comment by Samuel-Oliveira** [comment]
Tudo Bom? Essas informações vc encontra no Manual da Nfe!

Para os CSOSN=102, 103, 300 ou 400 use ICMSSN102
