### ISSUE TITLE
Sugestão: Adicionar classe para gerar id da nfe

### ISSUE THREAD

**Issue by ArielAleksandrus** [Samuel-Oliveira/Java_NFe#84]
Eu estou tendo problemas com o código verificador na hora de gerar a id da nfe.

Eu vi um código na internet mas este código também gera a id com o código verificador inválido. Acho que seria uma boa adicionar no projeto uma classe que gera a id (já que ela é calculada)

Um exemplo de classe (que está dando problema no dígito verificador) é esta: https://gist.github.com/ArielAleksandrus/1e31b7d2d397481ad2cfa73c9c81b246

**Comment by resplandes** [comment]
Legal.

**Comment by ArielAleksandrus** [comment]
@resplandes eu acho que esse método de calcular o dígito verificador está correto. olhei nas calculadoras online de módulo 11 e todas retornavam o mesmo valor. Você consegue verificar pra mim por favor?

**Comment by ArielAleksandrus** [comment]
Ao que acabei de verificar, o cálculo está realmente correto. Não sei por que estou recebendo o erro: Erro:Status:253 - Motivo:Rejeição: Digito Verificador da chave de acesso composta inválida

**Comment by Samuel-Oliveira** [comment]
Beleza ? 
Não irei implementar pelo mesmo motivo que esta dando erro.
O método seria inválido por que vc precisa de 2 retornos, a chave e o digito verificador.

Seu erro Ariel, deve ser que vc não esta colocando o digito verificador que está na chave, no corpo da nota. Exatamente no campo ide.setCDV("xxx");

Dai sua chave fica com um código e no corpo fica com o Outro.
Então o que vc precisa é apenas o método que calcula o DV (Que vc já tem).

E não irei criar um método apena pra concatenar String né...

Abraços!

**Comment by ArielAleksandrus** [comment]
realmente, eu não imaginava q tinha q setar ele novamente. pelo amor de Deus esses softwares do governo heim... mas sobre o método, eu achei interessante pq tem toda uma ordem dos atributos pra concatenar. isso facilitaria pro desenvolvedor não precisar verificar o manual (até pq tinha um jeito antes que o cNF tinha 9 caracteres, e agora usa tpEmis + o cNF de 8 caracteres). se vc não se importar eu abro um PR, o que acha?

**Comment by Samuel-Oliveira** [comment]
Sem problema... Monta o Pull e me manda!
Ai analisamos!

**Comment by ArielAleksandrus** [comment]
#85

**Comment by Samuel-Oliveira** [comment]
Implementado!
