### ISSUE TITLE
Erro:Status:685 - Motivo:Rejeição: Total do Valor Aproximado dos Tributos difere do somatório dos itens

### ISSUE THREAD

**Issue by ArielAleksandrus** [Samuel-Oliveira/Java_NFe#86]
Na tag imposto (referente a produto), além do icms, pis e cofins, tem também vTotTrib, como na imagem abaixo:

![screenshot from 2018-06-29 13 34 53](https://user-images.githubusercontent.com/10962902/42104005-6a2922b6-7ba1-11e8-98df-7338056645fa.png)

Mas não tem esse método na classe Imposto, para setar o vTotTrib
![screenshot from 2018-06-29 13 37 10](https://user-images.githubusercontent.com/10962902/42104037-90c80d6a-7ba1-11e8-8457-c3965f626c8b.png)

Por isso eu creio que está dando este erro. Porque ele tenta achar o somatório do vTotTrib da tag imposto de cada produto, e compara com a vTotTrib da tag ICMSTot
Como eu faço pra setar o vTotTrib?

_P.S.: desculpa estar te incomodando abrindo tantos issues_

**Comment by resplandes** [comment]
Olá Ariel, para você inserir o imposto do item é só fazer o seguinte.
`imposto.getContent().add(new ObjectFactory().createTNFeInfNFeDetImpostoVTotTrib("0.00");
        `
Abraços.

**Comment by Samuel-Oliveira** [comment]
Duvida respondida!
