### ISSUE TITLE
Criar arquivo xml 

### ISSUE THREAD

**Issue by egioncpdsi** [Samuel-Oliveira/Java_NFe#88]
Olá Samuel tudo bem ? Procurei aqui pelos issues e não encontrei, tem alguma função na api pra fazer um arquivo xml a partir de um objeto Nfe ? 
Desde já Agradeço pela paciência

**Comment by Samuel-Oliveira** [comment]
Beleza?
Para Tranformar os Objetos  em xml (String) use o XmlUtil.objectToXml.

Agora para gerar arquivo, é algo muito relacionado a regra de negocio.
Então tudo que é mt especifico não vai para API, assim como impressão.
Como cada um faz diferente não compensa manter.
Mas deixo aqui um exemplo de uma método que grava arquivo:

 /**
     * Cria um arquivo com os dados passados
     */
    public static void criarPastaArquivo(String pasta, String arquivo, String conteudo){

        File folder = new File(pasta);
        if(!folder.exists()){
            folder.mkdirs();
        }

        FileWriter fileWriter;
        try {
            fileWriter = new FileWriter(new File(pasta+"/"+arquivo));
            fileWriter.write(conteudo);
            fileWriter.close();
        } catch (Exception e) {
            TRatar erro aqui
        }
    } 


Caso tenha resolvido a duvida por favor feche a Issue!
