### ISSUE TITLE
Emissão de NFCe em Contingencia na UF Bahia

### ISSUE THREAD

**Issue by GabrielReboucas** [Samuel-Oliveira/Java_NFe#90]
Ao tentar fazer a emissão em contingência tenho o seguinte mensagem abaixo: 

"WebService de URL-QRCode não encontrado para Bahia"

Obs: Quando não é em contingência esta autorizando normal.

**Comment by Samuel-Oliveira** [comment]
Beleza? Estou em viagem, e sem pc para olhar!
Assim que voltar eu testo.

**Comment by GabrielReboucas** [comment]
Ok, obrigado

**Comment by GabrielReboucas** [comment]
Isso mesmo, Contigencia OffLine.

A exceção esta acontecendo quando ao gerar o qrCode no metodo " WebServiceUtil.getUrl(config ,ConstantesUtil.NFCE, ConstantesUtil.SERVICOS.URL_QRCODE))"

Quando não seto o "config.setContigenciaSCAN(true)" a emissão vai normal.

`//QRCODE
            String qrCode = NFCeUtil.getCodeQRCode(
                    infNFe.getId().substring(3),
                    "100",
                    ide.getTpAmb(),
                    dest.getCNPJ() == null ? dest.getCPF() : dest.getCNPJ(),
                    ide.getDhEmi(),
                    total.getICMSTot().getVNF(),
                    total.getICMSTot().getVICMS(),
                    Base64.getEncoder().encodeToString(enviNFe.getNFe().get(0).getSignature().getSignedInfo().getReference().getDigestValue()),
                    idToken,
                    csc,
                    WebServiceUtil.getUrl(config ,ConstantesUtil.NFCE, ConstantesUtil.SERVICOS.URL_QRCODE));`

**Comment by Samuel-Oliveira** [comment]
Bom, Ai esta seu Erro.
Vc esta habilitando Contigencia SCAN, que é somente para NFe.

Contigencia Offline (NFCe) vc não precisa ativar nada, apenas não enviar, e depois que voltar a intenet, evniar normalmente,

**Comment by GabrielReboucas** [comment]
Blz Cara.

Entendi, Obrigado
