### ISSUE TITLE
Preenchimento dos campos FCP NF-e 4.00

### ISSUE THREAD

**Issue by leoyuji** [Samuel-Oliveira/Java_NFe#92]
Olá, tudo bem?

  Sou desenvolvedor, porém não tenho muita experiência em relação a NF-e, e estou realizando alterações em um sistema que emite notas na versão 3.10 e passei a utilizar sua biblioteca para emitir notas na versão 4.00.
  Estou com dúvida nos campos relacionados ao FCP. Emiti notas com emitente e destinatários residentes em SP, em ambiente de homologação, utilizando produtos com NCM 22.03 (bebidas alcoólicas) e NCM 24 (fumo e seus sucedâneos manufaturados), e nos campos vFCP, vFCPUFDest, vFCPST e vFCPSTRet do ICMSTot, preenchi tudo com "0.00", acreditando assim que a nota seria rejeitada por não ter aplicado o FCP de 2.00. Porém, a nota foi aceita sem nenhum problema.
  Estou fazendo algo de errado? Se precisar, posso enviar o xml das notas em questão.

**Comment by lmfardin** [comment]
Eu também aprovei notas em homologação com os campos do FCP zerados. Acho que, para fins de testes, não tem nada de errado nisso.
    Em quinta-feira, 19 de julho de 2018 11:53:24 BRT, leoyuji <notifications@github.com> escreveu:  
 
 
Olá, tudo bem?

Sou desenvolvedor, porém não tenho muita experiência em relação a NF-e, e estou realizando alterações em um sistema que emite notas na versão 3.10 e passei a utilizar sua biblioteca para emitir notas na versão 4.00.
Estou com dúvida nos campos relacionados ao FCP. Emiti notas com emitente e destinatários residentes em SP, em ambiente de homologação, utilizando produtos com NCM 22.03 (bebidas alcoólicas) e NCM 24 (fumo e seus sucedâneos manufaturados), e nos campos vFCP, vFCPUFDest, vFCPST e vFCPSTRet do ICMSTot, preenchi tudo com "0.00", acreditando assim que a nota seria rejeitada por não ter aplicado o FCP de 2.00. Porém, a nota foi aceita sem nenhum problema.
Estou fazendo algo de errado? Se precisar, posso enviar o xml das notas em questão.

**Comment by Samuel-Oliveira** [comment]
Beleza?

Os campos do FCP não são Obrigatorios, por isso não são validados qnt ao conteudo.
Porem vc deve se atentar ao seguinte:
No totalizador vc pode sim colocar eles zarados. Mas nas tributações ICMS não. Se ele for zerado vc não deve preencher as Tags, como vc fez (mesmo sem saber);

E o fato da nota ser aceita sem FCP não te Isenta da responsabilidade.
Se os NCM dos produtos se enquadrão no FCP do seu estado ver (http://blog.oobj.com.br/fundo-de-combate-pobreza-fcp-nfe-4-0/#fcp-estado) você deve sim, preencher os dados do FCP no ICMS. Senão estrá passível de multas.

Sempre consulte o contador qnt a isso!

Irei fechar qlq coisa, abra novamente.
