### ISSUE TITLE
Xml da NFe não está sendo montado corretamente para versão 4.0

### ISSUE THREAD

**Issue by naiteon** [Samuel-Oliveira/Java_NFe#93]
Segue meu codigo e o erro obtido:

//Impostos
            Imposto imposto = new Imposto();
            ICMS icms = new ICMS();
            ICMSSN500 icmssn500 = new ICMSSN500();
            icmssn500.setOrig("0");  //origem da mercadoria: 0 - Nacional 1 - Estrangeira - Importação direta 2 - Estrangeira - Adquirida no mercado interno
            icmssn500.setCSOSN("500");  //500 – ICMS cobrado anterirmente por substituição tributária (substituído) ou por antecipação (v.2.0)

            PIS pis = new PIS();
            PISAliq pisAliq = new PISAliq();
            pisAliq.setCST("99");
            pisAliq.setVBC("10.00");
            pisAliq.setPPIS("0.65");
            pisAliq.setVPIS("0.07");
            pis.setPISAliq(pisAliq);

            COFINS cofins = new COFINS();
            COFINSAliq cofinsAliq = new COFINSAliq();
            cofinsAliq.setCST("99");
            cofinsAliq.setVBC("10.0");
            cofinsAliq.setPCOFINS("3.0");
            cofinsAliq.setVCOFINS("0.30");
            cofins.setCOFINSAliq(cofinsAliq);

br.com.samuelweb.nfe.exception.NfeValidacaoException: Erro Na Validação do Xml: 
- The content do campo 'ICMS' is not complete. Campo(s) 'ICMS00, ICMS10, ICMS20, ICMS30, ICMS40, ICMS51, ICMS60, ICMS70, ICMS90, ICMSPart, ICMSST, ICMSSN101, ICMSSN102, ICMSSN201, ICMSSN202, ICMSSN500, ICMSSN900' é obrigatorio.
- O valor '99' do campo 'CST' nao é valido.
- O valor '99' do campo 'CST' nao é valido.
- O valor '10.0' do campo 'vBC' nao é valido.
- O valor '3.0' do campo 'pCOFINS' nao é valido.
- O valor '10.0' do campo 'vNF' nao é valido.
- O valor '10.0' do campo 'vPag' nao é valido.

**Comment by Samuel-Oliveira** [comment]
beleza?

Ta, criou o Imposto e o ICMS.
Mas vc não mostra que coloca o icms no Imposto, e o imposto no pai.

**Comment by naiteon** [comment]
JAXBElement<ICMS> icmsElement = new JAXBElement<ICMS>(new QName("ICMS"), ICMS.class, icms);
            imposto.getContent().add(icmsElement);

            JAXBElement<PIS> pisElement = new JAXBElement<PIS>(new QName("PIS"), PIS.class, pis);
            imposto.getContent().add(pisElement);

            JAXBElement<COFINS> cofinsElement = new JAXBElement<COFINS>(new QName("COFINS"), COFINS.class, cofins);
            imposto.getContent().add(cofinsElement);

            det.setImposto(imposto);
            infNFe.getDet().add(det);

**Comment by Samuel-Oliveira** [comment]
Ta, E onde vc esta colocando o icmssn500 dentro de ICMS?

**Comment by naiteon** [comment]
Realmente o erro do icms foi cagada minha! A proposito parabens cara pelo seu trabalho, nem tive tempo de te falar isso. 
Cara eu saquei fora essa linha sem querer, botando ela, voltou a funcionar:
icms.setICMSSN500(icmssn500);

Os erros agora sao sobre a cst e vProd. E o numero da nfe.

Segue:

InfNFe infNFe = new InfNFe();
            infNFe.setId("NFe43180727776421000165650010000001009999999993");   // Informar a Chave de Acesso precedida do literal ‘NFe’, 
            infNFe.setVersao("4.00");  // versao NFC-e

            // Informações NFCe
            Ide ide = new Ide();
            ide.setCUF("43");  // IBGE 43 = RS
            ide.setCNF("99999999"); // numero aleatorio para cada nfe 8 dig maximo
            ide.setNatOp("VENDA");  // natureza operação 
            ide.setMod("65");
            ide.setSerie("1");   // serie
            ide.setNNF("000000100");
   
E nos impostos isso:

PIS pis = new PIS();
            PISAliq pisAliq = new PISAliq();
            pisAliq.setCST("99");
            pisAliq.setVBC("10.00");
            pisAliq.setPPIS("0.65");
            pisAliq.setVPIS("0.07");
            pis.setPISAliq(pisAliq);

            COFINS cofins = new COFINS();
            COFINSAliq cofinsAliq = new COFINSAliq();
            cofinsAliq.setCST("99");
            cofinsAliq.setVBC("10.0");
            cofinsAliq.setPCOFINS("3.0");
            cofinsAliq.setVCOFINS("0.30");
            cofins.setCOFINSAliq(cofinsAliq);


E no totalizador isso:
ICMSTot icmstot = new ICMSTot();
            icmstot.setVBC("0");
            icmstot.setVICMS("0");
            icmstot.setVICMSDeson("0");
            icmstot.setVFCP("0");
            icmstot.setVFCPST("0");
            icmstot.setVFCPSTRet("0");
            icmstot.setVBCST("0");
            icmstot.setVST("0");
            icmstot.setVProd("10.00");
            icmstot.setVFrete("0");
            icmstot.setVSeg("0.00");
            icmstot.setVDesc("0");
            icmstot.setVII("0");
            icmstot.setVIPI("0");
            icmstot.setVIPIDevol("0");
            icmstot.setVPIS("0.07");
            icmstot.setVCOFINS("0.30");
            icmstot.setVOutro("0");
            icmstot.setVNF("10.0");
            total.setICMSTot(icmstot);
            infNFe.setTotal(total);


RESULTADO

- O valor '000000100' do campo 'nNF' nao é valido.
- O valor '99' do campo 'CST' nao é valido.
- O valor '99' do campo 'CST' nao é valido.
- O valor '10.0' do campo 'vBC' nao é valido.
- O valor '3.0' do campo 'pCOFINS' nao é valido.
- O valor '10.0' do campo 'vNF' nao é valido.
- O valor '10.0' do campo 'vPag' nao é valido.

**Comment by naiteon** [comment]
Os valores float eu estava passando somente 1 casa decimal e era por isso. So ficou esse erro da CST e numero da NFe

- O valor '000000100' do campo 'nNF' nao é valido.
- O valor '99' do campo 'CST' nao é valido.
- O valor '99' do campo 'CST' nao é valido.

**Comment by Samuel-Oliveira** [comment]
Beleza!

Cara agora é vc colocar os dados de forma correta, sempre seguindo o manual.
por exemplo: 
- O Numero é campo numerico, então não pode ter zero a esquerda.
- PisAliq não pode ter CST 99, somente 01 ou 02. Para cst 99 use PisOutr
- Os campos de Valores tem que ter 2 casas decimais.

Etc,..

Vou fechar o topico. Abraços!

**Comment by naiteon** [comment]
Claro e me desculpa! Cara, eu to quase conseguindo. Mas to tendo um problema tão bizarro que estou chegando a acreditar que o certificado que uso em PRODUCAO deve ser diferente do de HOMOLOGACAO... Pq o erro que estou tendo é esse agora:

Status:598 - Motivo:Rejeicao: NF-e emitida em ambiente de homologacao com Razao Social diferente de NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL

Só que eu estou informando isso:
emit.setXNome("NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL");

Se tento deixar o CNPJ no formato 99999999000191 ou vazio, ou a I.E vazia como sugerido no manual, dai recebo um erro dizendo que IE é obrigatoria e que o CNPJ nao bate com o certificado.... 
Se deixo a IE e o CNPJ certos, dai recebo o status  598 ali em cima MESMO tendo posto aquele xNome.

**Comment by naiteon** [comment]
Valeu Rreynoud! Vou tentar isso obrigado!

**Comment by ADSRP** [comment]
Estou com um problema parecido:
- O valor '07' do elemento 'CST' não é válido.
- O valor '07' do elemento 'CST' não é válido. ==> 
     ==> br.com.swconsultoria.nfe.Enviar.montaNfe(Enviar.java:76)
     ==> br.com.swconsultoria.nfe.Nfe.montaNfe(Nfe.java:124)
     
Você fez o que para resolver?
