### ISSUE TITLE
Geração de Danfe NFC-e

### ISSUE THREAD

**Issue by ArielAleksandrus** [Samuel-Oliveira/Java_NFe#94]
Bom dia, pessoal.

Eu acompanhei o outro issue de por que não é incluída uma classe que gera os danfes, mas eu não to achando nenhum projeto que faça a geração. Como vocês fazem pra gerar a de vocês? Vocês mesmos implementaram? Se sim, alguém tem como me dar mais orientações? Tipo um tutorial, etc?

**Comment by rreynoud** [comment]
Opa bom dia, nos temos uma implementação que da impressão desde o xml, não sei se esse seria o teu caso.
Para não perder tempo eu criei um repositório na minha conta do github https://github.com/rreynoud/danfe, pode dar uma olhada nesse.
Obs: depois com tempo vou fazer uma documentação etc, agora foi rapidão para so para tentar de ajudar. Ate mesmo eu posso fazer um fork do projeto do Samuel na minha conta ou podemos ver com ele, de colocar os arquivos no projeto Java_NFE, 
Espero ter ajudado qualquer coisa pode entrar em contato, email rafael@teorema.inf.br e skype rafareypy
Abraço!

**Comment by Samuel-Oliveira** [comment]
Foi finalizada a duvida?

Se este tópico não for respondido em 3 dias Será fechado!

**Comment by ArielAleksandrus** [comment]
Por favor, reabra o issue. O projeto do @rreynoud não está funcionando pra mim e não to conseguindo de forma nenhuna gerar o danfe. Como vc faz, samuel? Vc pode me ajudar por favor?

**Comment by resplandes** [comment]
Qual seu problema ?



*Willian Resplandes Matias*

Professor Esp. em Tecnologias para desenvolvimento de Aplicações Web e
Docência no Ensino Superior

Sócio Proprietário da SoftJava – Programador Java Sênior

SoftJava Consultoria e Serviços em Informática

( Fone: 66.3575.266

( Celular: 66 99971-6730 <(66)%2099971-6730>

Skype: willian.matias.frialto

w <willian.matias@frialto.com.br>illianresplandes@gmail.com

Antes de imprimir, lembre-se do seu compromisso com o meio ambiente




Em sex, 28 de set de 2018 às 19:01, Ariel Aleksandrus <
notifications@github.com> escreveu:

**Comment by ArielAleksandrus** [comment]
@resplandes não consigo gerar o danfe a partir do xml. Os projetos q eu vejo usam um tal de jasper, mas nunca nem ouvo falar dele. Fui tentar pesquisar sobre, mas n entendi. Preciso gerar danfe nfce a partir de xml. N tem um programinha java q faz isso?

**Comment by resplandes** [comment]
Certo, eu uso, tenho uma classe lá forum JavaC que faz isso, Jasper é uma
ferramenta para desenvolver Relatórios, já programa em java a muito tempo ?
Não não tem um programinha não Ariel



*Willian Resplandes Matias*

Professor Esp. em Tecnologias para desenvolvimento de Aplicações Web e
Docência no Ensino Superior

Sócio Proprietário da SoftJava – Programador Java Sênior

SoftJava Consultoria e Serviços em Informática

( Fone: 66.3575.266

( Celular: 66 99971-6730 <(66)%2099971-6730>

Skype: willian.matias.frialto

w <willian.matias@frialto.com.br>illianresplandes@gmail.com

Antes de imprimir, lembre-se do seu compromisso com o meio ambiente




Em sex, 28 de set de 2018 às 19:39, Ariel Aleksandrus <
notifications@github.com> escreveu:

**Comment by fiabani** [comment]
Eu estou usando nfephp para gerar os danfes pois não encontrei nenhuma saída viável em java. Se alguém tiver uma solução para DANFE e DANFCE, fico agradecido se puder compartilhar.

**Comment by ArielAleksandrus** [comment]
@resplandes me add no skype por favor: arialeksandrus

@fiabani se não der certo o Java acho que vou ter que usar o php. To tentando evitar ao máximo por enquanto kkk

**Comment by resplandes** [comment]
Conforme citado, segue o link do post que compartilhei um exemplo de
geração de DANFe através do XML.


http://www.javac.com.br/jc/posts/list/2468-resolvidogerar-danfe-nfe-apartir-do-xml.page

*Willian Resplandes Matias*

Professor Esp. em Tecnologias para desenvolvimento de Aplicações Web e
Docência no Ensino Superior

Sócio Proprietário da SoftJava – Programador Java Sênior

SoftJava Consultoria e Serviços em Informática

( Fone: 66.3575.266

( Celular: 66 99971-6730 <(66)%2099971-6730>

Skype: willian.matias.frialto

w <willian.matias@frialto.com.br>illianresplandes@gmail.com

Antes de imprimir, lembre-se do seu compromisso com o meio ambiente




Em sáb, 29 de set de 2018 às 10:42, Ariel Aleksandrus <
notifications@github.com> escreveu:

**Comment by ArielAleksandrus** [comment]
Pessoal, fiz um exemplo bem simples, bem minimalista e que até onde eu vi funciona legal. @Samuel-Oliveira depois dá uma olhada e deixa pelo menos como exemplo no tutorial para ajudar a galera. Valeew

https://github.com/ArielAleksandrus/danfe
