### ISSUE TITLE
Validação NFE

### ISSUE THREAD

**Issue by TiagoZaro** [Samuel-Oliveira/Java_NFe#95]
Na UF para RS (onde testei) estou com um problema na seguinte chamada:
`NfeWeb.montaNfe(configs, enviNFe, true);`
Neste método quando chamado para validar(true) está retornando que o vDesc '0.00' é inválido. Porém na geração da fatura para documento 15 caso este valor não seja informado o sefaz está recusando a nota.

Para poder usar estou chamando o método sem as validações(false):
...
`NfeWeb.montaNfe(configs, enviNFe, false);`
....
`Fat fatura = new Fat();`
`if (greaterThanZero(getTotalizador(VALOR_TOTAIS_DESCONTOS))) {`
`	fatura.setVDesc(gerarDuasCasas(getTotalizador(VALOR_TOTAIS_DESCONTOS)).toString());`
`} else {`
`	fatura.setVDesc("0.00");`
`});`
....

Não sei se é algo específico do RS, mas será que neste caso a validação não deveria permitir o vDesc = "0.00" ?

**PS: Versão: v4.00.6 - Ambiente PROD e TESTE**

**Comment by Samuel-Oliveira** [comment]
Beleza @TiagoZaro ?

A validação é feita através dos arquivos XSD que são disponibilizados da Sefaz.
Então não é a API que permite ou não um valor.

Nesse caso o que parece ser, é que vc está com os XSD desatualizados.

**Comment by TiagoZaro** [comment]
@Samuel-Oliveira realmente, acredito que foi atualizado no projeto e no servidor não. Muito Obrigado pela ajuda.
