### ISSUE TITLE
Retornar XML ao Enviar NFe

### ISSUE THREAD

**Issue by andersonscherrrer** [Samuel-Oliveira/Java_NFe#96]
Preciso pegar o XML de Retorno da Sefaz ao enviar um lote para autorizar. 
Temos o seguinte Método da Classe Enviar.java:
static TRetEnviNFe enviaNfe(ConfiguracoesNfe config, TEnviNFe enviNFe, String tipo) 
**Problema:**

**1** -  br.inf.portalfiscal.nfe.schema_4.enviNFe.TRetEnviNFe, eu não consigo transformar em Xml;

### Soluções no meu entendimento:

**1** - Aceitar um callback:
TRetEnviNFe enviaNfe(ConfiguracoesNfe config, TEnviNFe enviNFe, String tipo, Callback callbackXml) 
para retornar result.getExtraElement().toString();

**2** - Retornoar TRetEnviNFe do pacote br.inf.portalfiscal.nfe.schema_4.retEnviNFe. Pois este eu consigo transformar em XML

**Comment by Samuel-Oliveira** [comment]
Beleza?

Experimentou isso?

String xml = XmlUtil.objectToXml(retorno);

**Comment by resplandes** [comment]
Eu consigo transformar sim o retorno em xml, da seguinte maneira.
`gravarXML(XmlUtil.objectToXml(retorno.getProtNFe()), nfe.getInfNFe().getId() + "-ERROR.xml");`

`\\Método usado para gravar meu xml

private static void gravarXML(String xmlNFe, String nomeXML) {
        try {
            System.out.println("Gravando xml da NFe");
            File diretorio = new File(new File(".").getCanonicalPath() + File.separator + "Temp");
            if (!diretorio.exists()) {
                System.out.println("Criando diretorio temp da aplicação");
                diretorio.mkdirs();
            }
            String path = System.getProperty("java.io.tmpdir") + File.separator + nomeXML;
            String pathTempApp = PathAplicacao.path() + File.separator + "temp" + File.separator + nomeXML;
            byte[] xml = xmlNFe.getBytes();
            File arquivo = new File(path);
            File arquivoTemp = new File(pathTempApp);

            new GravarArquivoEmDisco(arquivo, xml).gravar();
            new GravarArquivoEmDisco(arquivoTemp, xml).gravar();
        } catch (Exception e) {
            FormAguarde.getInstancia().setAlwaysOnTop(false);
            DialogExcecao.show(e);
        }
    }`

**Comment by andersonscherrrer** [comment]
Oloko tentei isso há algum tempo e dava erro, mas blz vou fechar a issue equivocada kkk.

**Comment by Samuel-Oliveira** [comment]
O Método objectToXml só converte objetos pre configurados, talvez quando tentou o retorno não esta incluído. E não me esqueci do Modulo Web do Cte @andersonscherrrer ! Vou fazer!

**Comment by andersonscherrrer** [comment]
Sem pressa, entendo que teve os B.O. da NFe 4.0 aí. Qualquer dúvida ou ajuda estou à disposição.
