### ISSUE TITLE
Da versão 4.00.3 para a 4.00.6 o sistema parou de reconhecer meu certificado A1

### ISSUE THREAD

**Issue by Bonissauro** [Samuel-Oliveira/Java_NFe#97]
Buenas, Samuel!

Quando atualizei em meu projeto a versão de tua biblioteca, não consigo mais usar meu certificado A1 para assinar as NFC. Uso o java abaixo, num mac:

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Trecho do código onde a coisa para:

**Certificado certificado = CertificadoService.certificadoPfx(nomeArquivoCertificadoComPath, senha);**
			
Exception recebida:

Caused by: java.lang.NoClassDefFoundError: sun/security/pkcs11/wrapper/PKCS11Exception

**Comment by Samuel-Oliveira** [comment]
Tem sim, claro. 
Mas, ou vc deve ter mantido a versão anterior, ou está setando o java_certificado manualmente.
Manda a lista completa de Libs q vc tem dentro de  webinf/lib

**Comment by Samuel-Oliveira** [comment]
Se este tópico não for respondido em 3 dias, será fechado!

**Comment by Bonissauro** [comment]
O animal aqui Tinha te respondido no e-mail em vez de fazer pela via correta.

**Comment by Bonissauro** [comment]
base64coder.jar
commons-fileupload-1.3.2.jar
cors-filter-2.4.jar
iText-blablabla
java-nfe-4.00.3.jar
java-nfe-4.00.6.jar.old
java-property-utils-1.10.jar

**Comment by Bonissauro** [comment]
Mas tá como old!!!! 

Em todo caso, vou remover o arquivo e tentar hoje à noite.

**Comment by Bonissauro** [comment]
Removi a outra biblioteca jar que estava como old e o erro persiste, Samuel!

A mesma PKCS11Exception.

**Comment by Samuel-Oliveira** [comment]
Beleza, Me mostra novamente como esta sua pasta LIbs por favor.

**Comment by Bonissauro** [comment]
Samuel,

agora ela está assim (apenas tirei aquela old).

WEB-INF\lib\base64coder.jar
WEB-INF\lib\commons-fileupload-1.3.2.jar
WEB-INF\lib\cors-filter-2.4.jar
WEB-INF\lib\iText-blablabla
WEB-INF\lib\java-nfe-4.00.6.jar
WEB-INF\lib\java-property-utils-1.10.jar

**Comment by Samuel-Oliveira** [comment]
Vamos ter q olhar seu problema mais de perto, me adicione ao skype por favor (samuk.exe@hotmail.com)

**Comment by Samuel-Oliveira** [comment]
Se este topico não for respondido em 3 dias, será FInalizado!

**Comment by Samuel-Oliveira** [comment]
Fechado por inatividade

**Comment by Bonissauro** [comment]
Samuel,

voltei ao mesmo problema. Preciso gerar o qrCode 2 e, ao tentar usar a tua biblioteca, voltei a me deparar com o erro desta thread!
