### ISSUE TITLE
Nfe Cancelada

### ISSUE THREAD

**Issue by john182** [Samuel-Oliveira/Java_NFe#98]
Boa tarde qual seria o procedimento pra era  o xml com o protocolo de cancelamento.

**Comment by Samuel-Oliveira** [comment]
Blz John? Ve se é o que precisa, sua pergunta ficou confusa.

            // Cria TProcEventoNFe
            TProcEvento procEvento = new TProcEvento();
            procEvento.setVersao("1.00");
            procEvento.setEvento(enviEvento.getEvento().get(0));
            procEvento.setRetEvento(retorno.getRetEvento().get(0));

            System.out.println(XmlUtil.objectToXml(procEvento));

**Comment by john182** [comment]
Bom dia Samuel então la no procedimento de envio ao ser autorizado é criado uma uma NFe processada, então os contadores estão querendo o mesmo.

**Comment by resplandes** [comment]
@john182  segue o meu código de como pego o XML de retorno da NFe enviada para Segaz.

`
retorno = Nfe.enviarNfe(enviNFe, ConstantesUtil.NFE);
 gravarXML(XmlUtil.objectToXml(retorno.getProtNFe()), "NOME_DA_NFE_COM_CHAVE_E_ETC.xml");

`

**Comment by john182** [comment]
opa a nota autorizada é de boa o lance é as canceladas.

**Comment by resplandes** [comment]
quer so o XML de cancelamento ? aquele que fala Evento registrado com sucesso...

**Comment by john182** [comment]
só a parte eu já eu pego conforme @Samuel-Oliveira discriminou, porem os contadores querem anexado com a nota como é o caso da nota processada, onde quando é autorizado pegamos o protocolo e criamos outro objeto e geramos o xml.

**Comment by Samuel-Oliveira** [comment]
Entendi John, eu tive alguns contadores que pediram o mesmo. 
Segue minha solução com o layout solicitado:

        //Aqui ppego o xml Autorizado e transforme em Proc.
        TNfeProc nfe = XmlUtil.xmlToObject(XmlUtil.leXml(caminhoXml), TNfeProc.class);
                                                                                       nfe.getProtNFe().getInfProt().setNProt(retornoCancelamento.getRetEvento().get(0).getInfEvento().getNProt());
        nfe.getProtNFe().getInfProt().setCStat("101"); // 101
        nfe.getProtNFe().getInfProt().setDhRecbto(retornoCancelamento.getRetEvento().get(0).getInfEvento().getDhRegEvento());
        nfe.getProtNFe().getInfProt().setXMotivo("NF-e Cancelada"); // NF-e Cancelada

        String xml = XmlUtil.objectToXml(nfe);

**Comment by john182** [comment]
Opa vlw irei testa tem um ajuste aqui que  fiz aqui no controle do Cdata se quiser passo ai o que fiz.

**Comment by Samuel-Oliveira** [comment]
Duvida Sanada?
Se esse topico n for respondido em 3 dias será fechado!

**Comment by john182** [comment]
sim pode encerrar
